const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

const htmlDir = path.join(__dirname, 'public/11th-munitorum-field-manual');
const files = fs.readdirSync(htmlDir).filter(f => f.endsWith('.html'));

const factionMap = {
  "ADEPTUS MECHANICUS": "Adeptus Mechanicus",
  "ADEPTUS SORORITAS": "Adepta Sororitas",
  "AELDARI": "Aeldari",
  "ASTRA MILITARUM": "Astra Militarum",
  "BLACK TEMPLARS": "Black Templars",
  "BLOOD ANGELS": "Blood Angels",
  "CHAOS DEMONS": "Chaos Daemons",
  "CHAOS KNIGHTS": "Chaos Knights",
  "CHAOS SPACE MARINES": "Chaos Space Marines",
  "CHAOS TITAN LEGIONS": "Chaos Titan Legions",
  "CUSTODES": "Adeptus Custodes",
  "DARK ANGELS": "Dark Angels",
  "DEATH GUARD": "Death Guard",
  "DEATHWATCH": "Deathwatch",
  "DRUKHARI": "Drukhari",
  "EMPERORS CHILDREN": "Emperor's Children",
  "GENESTEALER CULTS": "Genestealer Cults",
  "GREY KNIGHTS": "Grey Knights",
  "IMPERIAL AGENTS": "Agents of the Imperium",
  "IMPERIAL KNIGHTS": "Imperial Knights",
  "LEAGUES OF VOTANN": "Leagues of Votann",
  "NECRONS": "Necrons",
  "ORKS": "Orks",
  "SPACE MARINES": "Space Marines",
  "SPACE WOLVES": "Space Wolves",
  "TAU": "T'au Empire",
  "THOUSAND SONS": "Thousand Sons",
  "TITAN LEGIONS": "Titan Legions",
  "TYRANIDS": "Tyranids",
  "WORLD EATERS": "World Eaters"
};

let sqlOutput = `
-- 11th Edition Munitorum Field Manual Units
-- Generated by parse_mfm_html.cjs

-- Add wargear options column if it doesn't exist
ALTER TABLE public.unit_points ADD COLUMN IF NOT EXISTS wargear_options JSONB DEFAULT '[]'::jsonb;

DELETE FROM public.unit_points;

`;

let totalUnits = 0;

for (const file of files) {
  const filePath = path.join(htmlDir, file);
  const html = fs.readFileSync(filePath, 'utf8');
  const $ = cheerio.load(html);

  // 1. Resolve Suspense Templates
  $('script').each((i, el) => {
    const scriptContent = $(el).html();
    if (scriptContent && scriptContent.includes('$RS(')) {
      const match = scriptContent.match(/\$RS\("([^"]+)","([^"]+)"\)/);
      if (match) {
        const sourceId = match[1];
        const targetId = match[2];
        const sourceContent = $(`[id="${sourceId}"]`).html();
        const targetElement = $(`[id="${targetId}"]`);
        if (sourceContent && targetElement.length > 0) {
          targetElement.replaceWith(sourceContent);
        }
      }
    }
  });

  // 2. Find Faction Name
  let factionRaw = $('.font-header.text-4xl').first().text().trim();
  if (!factionRaw) {
    console.error(`Could not find faction name in ${file}`);
    continue;
  }
  const factionName = factionMap[factionRaw] || factionRaw;

  // 3. Find UNITS section
  let foundUnitsHeader = false;
  let unitsCards = [];
  
  $('h3.text-4xl.font-header').each((i, el) => {
    if ($(el).text().trim() === 'UNITS') {
      foundUnitsHeader = true;
      // The sibling div contains the grid of units
      const grid = $(el).nextAll('div').first().find('div.flex.flex-col.space-y-1.m-1');
      if (grid.length === 0) {
        // Alternative structure
        $(el).parent().find('div.flex.flex-col.space-y-1.m-1').each((j, card) => {
            unitsCards.push(card);
        });
      } else {
        grid.each((j, card) => {
          unitsCards.push(card);
        });
      }
    }
  });

  if (!foundUnitsHeader || unitsCards.length === 0) {
    console.error(`Could not find UNITS in ${file}`);
    // Try to find them without the header
    $('div.flex.flex-col.space-y-1.m-1').each((i, el) => {
        if ($(el).find('div.bg-slate-500').length > 0) {
            unitsCards.push(el);
        }
    });
  }

  // Deduplicate cards (Cheerio can sometimes return duplicates if querying loosely)
  const processedUnits = new Set();

  for (const card of unitsCards) {
    const $card = $(card);
    const unitName = $card.find('div.bg-slate-500').first().text().trim().replace(/'/g, "''");
    
    if (!unitName || processedUnits.has(unitName)) continue;
    processedUnits.add(unitName);

    const costTiers = [];
    const wargearOptions = [];

    $card.find('div.space-y-1').each((i, block) => {
      const $block = $(block);
      const headerText = $block.find('div.bg-slate-200 span').length > 0 
        ? $block.find('div.bg-slate-200 span').first().text().trim()
        : $block.find('div.bg-slate-200').first().text().trim();

      if (!headerText) return;

      if (headerText.includes('WARGEAR OPTIONS')) {
        $block.find('ul.leaders li').each((j, li) => {
          const spans = $(li).find('span');
          if (spans.length >= 2) {
            const wargearName = $(spans[0]).text().trim().replace(/'/g, "''");
            const pointsText = $(spans[1]).text().replace(/[^0-9]/g, '');
            if (wargearName && pointsText) {
                wargearOptions.push({
                    name: wargearName,
                    points: parseInt(pointsText, 10)
                });
            }
          }
        });
      } else if (headerText.includes('UNIT COSTS') || headerText.includes('UNITS COST')) {
        let escalation = null;
        if (headerText.includes('YOUR 2ND +')) escalation = '2nd+';
        else if (headerText.includes('YOUR 3RD +')) escalation = '3rd+';
        else if (headerText.includes('YOUR 4TH +')) escalation = '4th+';

        $block.find('ul.leaders li').each((j, li) => {
          const spans = $(li).find('span');
          if (spans.length >= 2) {
            const modelsText = $(spans[0]).text().replace(/[^0-9]/g, '');
            const pointsText = $(spans[1]).text().replace(/[^0-9]/g, '');
            if (modelsText && pointsText) {
              costTiers.push({
                models: parseInt(modelsText, 10) || 1, // some say "1 model" or "1 vehicle"
                points: parseInt(pointsText, 10),
                escalation: escalation
              });
            }
          }
        });
      }
    });

    if (costTiers.length > 0) {
      const basePoints = costTiers[0].points;
      const costTiersJson = JSON.stringify(costTiers).replace(/'/g, "''");
      const wargearJson = JSON.stringify(wargearOptions).replace(/'/g, "''");

      sqlOutput += `INSERT INTO public.unit_points (faction, unit_name, base_points, cost_tiers, wargear_options) VALUES ('${factionName}', '${unitName}', ${basePoints}, '${costTiersJson}'::jsonb, '${wargearJson}'::jsonb);\n`;
      totalUnits++;
    }
  }
}

fs.writeFileSync('seed_units_11th.sql', sqlOutput);
console.log(`Successfully generated seed_units_11th.sql with ${totalUnits} units.`);
