-- Divergent Space Marine Chapters Registry Override
DELETE FROM unit_points WHERE faction IN ('Blood Angels', 'Dark Angels', 'Space Wolves', 'Black Templars', 'Deathwatch');
INSERT INTO unit_points (faction, unit_name, base_points, cost_tiers) VALUES
  ('Black Templars', 'Anvil Siege Force2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Black Templars', 'Armoured Speartip3dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Black Templars', 'Bastion Task Force3dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Black Templars', 'Ceramite Sentinels3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Black Templars', 'Companions of Vehemence2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Black Templars', 'Firestorm Assault Force2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Black Templars', 'Fulguris Task Force1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Black Templars', 'Gladius Task Force3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Black Templars', 'Godhammer Assault Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Black Templars', 'Headhunter Task Force2dp', 40, '[{"models":1,"points":40,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Black Templars', 'Ironstorm Spearhead2dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Black Templars', 'Marshal''s Household1dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Black Templars', 'Orbital Assault Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Black Templars', 'Stormlance Task Force2dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Black Templars', 'Subversion Assets1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Black Templars', 'The Living Miracle1dp', 15, '[{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Black Templars', 'Vanguard Spearhead2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Black Templars', 'Vindication Task Force2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Black Templars', 'Wrathful Procession1dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Black Templars', 'Castellan', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Black Templars', 'Chaplain Grimaldus', 110, '[{"models":4,"points":110,"escalation":null}]'::jsonb),
  ('Black Templars', 'Crusade Ancient', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Black Templars', 'Emperor’s Champion', 100, '[{"models":1,"points":100,"escalation":null}]'::jsonb),
  ('Black Templars', 'Execrator', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Black Templars', 'Gladiator Lancer', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Gladiator Reaper', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Gladiator Valiant', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'High Marshal Helbrecht', 120, '[{"models":1,"points":120,"escalation":null}]'::jsonb),
  ('Black Templars', 'Impulsor', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Black Templars', 'Land Raider Crusader', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Marshal', 80, '[{"models":1,"points":80,"escalation":null},{"models":1,"points":90,"escalation":null}]'::jsonb),
  ('Black Templars', 'Repulsor', 170, '[{"models":1,"points":170,"escalation":null},{"models":1,"points":190,"escalation":null},{"models":1,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Repulsor Executioner', 245, '[{"models":1,"points":245,"escalation":null},{"models":1,"points":265,"escalation":null},{"models":1,"points":265,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Sternguard Veteran Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":160,"escalation":null}]'::jsonb),
  ('Black Templars', 'Sword Brethren Squad', 105, '[{"models":4,"points":105,"escalation":null},{"models":5,"points":130,"escalation":null},{"models":9,"points":235,"escalation":null},{"models":10,"points":260,"escalation":null},{"models":4,"points":120,"escalation":null},{"models":5,"points":145,"escalation":null},{"models":9,"points":250,"escalation":null},{"models":10,"points":275,"escalation":null},{"models":4,"points":120,"escalation":"3rd+"},{"models":5,"points":145,"escalation":"3rd+"},{"models":9,"points":250,"escalation":"3rd+"},{"models":10,"points":275,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Terminator Squad', 160, '[{"models":5,"points":160,"escalation":null},{"models":10,"points":320,"escalation":null}]'::jsonb),
  ('Black Templars', 'Aggressor Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Black Templars', 'Ancient in Terminator Armour', 65, '[{"models":1,"points":65,"escalation":null}]'::jsonb),
  ('Black Templars', 'Apothecary', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Black Templars', 'Apothecary Biologis', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Black Templars', 'Assault Intercessor Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Black Templars', 'Assault Intercessors with Jump Packs', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":170,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Astraeus', 525, '[{"models":1,"points":525,"escalation":null},{"models":1,"points":575,"escalation":null}]'::jsonb),
  ('Black Templars', 'Ballistus Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Bladeguard Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Black Templars', 'Bladeguard Veteran Squad', 80, '[{"models":3,"points":80,"escalation":null},{"models":6,"points":160,"escalation":null},{"models":3,"points":90,"escalation":null},{"models":6,"points":170,"escalation":null},{"models":3,"points":90,"escalation":"3rd+"},{"models":6,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Brutalis Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Captain', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Black Templars', 'Captain in Gravis Armour', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Black Templars', 'Captain in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Black Templars', 'Captain in Terminator Armour', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Black Templars', 'Captain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Black Templars', 'Centurion Assault Squad', 150, '[{"models":3,"points":150,"escalation":null},{"models":6,"points":300,"escalation":null}]'::jsonb),
  ('Black Templars', 'Centurion Devastator Squad', 175, '[{"models":3,"points":175,"escalation":null},{"models":6,"points":350,"escalation":null}]'::jsonb),
  ('Black Templars', 'Chaplain', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Black Templars', 'Chaplain in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Black Templars', 'Chaplain on Bike', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Black Templars', 'Chaplain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Black Templars', 'Company Heroes', 105, '[{"models":4,"points":105,"escalation":null}]'::jsonb),
  ('Black Templars', 'Desolation Squad', 180, '[{"models":5,"points":180,"escalation":null},{"models":5,"points":210,"escalation":null}]'::jsonb),
  ('Black Templars', 'Devastator Squad', 120, '[{"models":5,"points":120,"escalation":null},{"models":10,"points":200,"escalation":null}]'::jsonb),
  ('Black Templars', 'Dreadnought', 135, '[{"models":1,"points":135,"escalation":null}]'::jsonb),
  ('Black Templars', 'Drop Pod', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Black Templars', 'Eliminator Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Black Templars', 'Eradicator Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Eradicator Squad with Heavy Bolters', 70, '[{"models":3,"points":70,"escalation":null},{"models":3,"points":80,"escalation":null},{"models":3,"points":80,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Firestrike Servo-turrets', 75, '[{"models":1,"points":75,"escalation":null},{"models":2,"points":150,"escalation":null}]'::jsonb),
  ('Black Templars', 'Hammerfall Bunker', 175, '[{"models":1,"points":175,"escalation":null}]'::jsonb),
  ('Black Templars', 'Heavy Intercessor Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null}]'::jsonb),
  ('Black Templars', 'Hellblaster Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":220,"escalation":null}]'::jsonb),
  ('Black Templars', 'Inceptor Squad', 120, '[{"models":3,"points":120,"escalation":null},{"models":6,"points":240,"escalation":null},{"models":3,"points":135,"escalation":null},{"models":6,"points":255,"escalation":null},{"models":3,"points":135,"escalation":"3rd+"},{"models":6,"points":255,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Incursor Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":150,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Infernus Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":170,"escalation":null}]'::jsonb),
  ('Black Templars', 'Infiltrator Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":180,"escalation":null},{"models":5,"points":120,"escalation":null},{"models":10,"points":190,"escalation":null},{"models":5,"points":120,"escalation":"3rd+"},{"models":10,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Intercessor Squad', 80, '[{"models":5,"points":80,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Black Templars', 'Invader Atv', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Black Templars', 'Invictor Tactical Warsuit', 125, '[{"models":1,"points":125,"escalation":null}]'::jsonb),
  ('Black Templars', 'Judiciar', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Black Templars', 'Land Raider', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Land Raider Redeemer', 250, '[{"models":1,"points":250,"escalation":null},{"models":1,"points":270,"escalation":null},{"models":1,"points":270,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Land Speeder', 95, '[{"models":1,"points":95,"escalation":null},{"models":1,"points":105,"escalation":null},{"models":1,"points":105,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Lieutenant', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Black Templars', 'Lieutenant in Phobos Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Black Templars', 'Lieutenant in Reiver Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Black Templars', 'Lieutenant with Combi-weapon', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Black Templars', 'Outrider Squad', 70, '[{"models":3,"points":70,"escalation":null},{"models":6,"points":140,"escalation":null},{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Black Templars', 'Predator Annihilator', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Predator Destructor', 140, '[{"models":1,"points":140,"escalation":null},{"models":1,"points":150,"escalation":null},{"models":1,"points":150,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Razorback', 95, '[{"models":1,"points":95,"escalation":null}]'::jsonb),
  ('Black Templars', 'Redemptor Dreadnought', 195, '[{"models":1,"points":195,"escalation":null},{"models":1,"points":210,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Reiver Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Black Templars', 'Rhino', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Black Templars', 'Scout Squad', 65, '[{"models":5,"points":65,"escalation":null},{"models":10,"points":120,"escalation":null},{"models":5,"points":75,"escalation":null},{"models":10,"points":130,"escalation":null},{"models":5,"points":75,"escalation":"3rd+"},{"models":10,"points":130,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Stormhawk Interceptor', 155, '[{"models":1,"points":155,"escalation":null}]'::jsonb),
  ('Black Templars', 'Stormraven Gunship', 280, '[{"models":1,"points":280,"escalation":null},{"models":1,"points":300,"escalation":null}]'::jsonb),
  ('Black Templars', 'Storm Speeder Hailstrike', 105, '[{"models":1,"points":105,"escalation":null},{"models":1,"points":115,"escalation":null},{"models":1,"points":115,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Storm Speeder Hammerstrike', 130, '[{"models":1,"points":130,"escalation":null},{"models":1,"points":140,"escalation":null},{"models":1,"points":140,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Storm Speeder Thunderstrike', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Stormtalon Gunship', 165, '[{"models":1,"points":165,"escalation":null}]'::jsonb),
  ('Black Templars', 'Suppressor Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Black Templars', 'Tactical Squad', 140, '[{"models":10,"points":140,"escalation":null}]'::jsonb),
  ('Black Templars', 'Techmarine', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Black Templars', 'Terminator Assault Squad', 155, '[{"models":5,"points":155,"escalation":null},{"models":10,"points":310,"escalation":null},{"models":1,"points":5,"escalation":null}]'::jsonb),
  ('Black Templars', 'Thunderhawk Gunship', 840, '[{"models":1,"points":840,"escalation":null}]'::jsonb),
  ('Black Templars', 'Vanguard Veteran Squad with Jump Packs', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null},{"models":5,"points":110,"escalation":null},{"models":10,"points":210,"escalation":null},{"models":5,"points":110,"escalation":"3rd+"},{"models":10,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Vindicator', 185, '[{"models":1,"points":185,"escalation":null},{"models":1,"points":200,"escalation":null},{"models":1,"points":200,"escalation":"3rd+"}]'::jsonb),
  ('Black Templars', 'Whirlwind', 175, '[{"models":1,"points":175,"escalation":null},{"models":1,"points":195,"escalation":null}]'::jsonb),
  ('Blood Angels', '1st Company Task Force2dp', 30, '[{"models":1,"points":30,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Angelic Inheritors3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Anvil Siege Force2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Armoured Speartip3dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Bastion Task Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Ceramite Sentinels3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Encarmine Speartip1dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Firestorm Assault Force2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Fulguris Task Force1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Gladius Task Force3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Headhunter Task Force2dp', 40, '[{"models":1,"points":40,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Ironstorm Spearhead2dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Legacy of Grace1dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Liberator Assault Group3dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":35,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Librarius Conclave1dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Orbital Assault Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Rage-cursed Onslaught3dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":35,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Stormlance Task Force2dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Subversion Assets1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Blood Angels', 'The Angelic Host2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Blood Angels', 'The Lost Brethren2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Vanguard Spearhead2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Wrath of the Doomed1dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Astorath', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Baal Predator', 125, '[{"models":1,"points":125,"escalation":null},{"models":1,"points":135,"escalation":null},{"models":1,"points":135,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Blood Angels Captain', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Commander Dante', 125, '[{"models":1,"points":125,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Death Company Captain', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Death Company Captain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Death Company Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Death Company Marines', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":170,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Death Company Marines with Bolt Rifles', 80, '[{"models":5,"points":80,"escalation":null},{"models":10,"points":155,"escalation":null},{"models":5,"points":90,"escalation":null},{"models":10,"points":165,"escalation":null},{"models":5,"points":90,"escalation":"3rd+"},{"models":10,"points":165,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Death Company Marines with Jump Packs', 120, '[{"models":5,"points":120,"escalation":null},{"models":10,"points":230,"escalation":null},{"models":5,"points":135,"escalation":null},{"models":10,"points":245,"escalation":null},{"models":5,"points":135,"escalation":"3rd+"},{"models":10,"points":245,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Lemartes', 100, '[{"models":1,"points":100,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Sanguinary Guard', 125, '[{"models":3,"points":125,"escalation":null},{"models":6,"points":260,"escalation":null},{"models":3,"points":145,"escalation":null},{"models":6,"points":280,"escalation":null},{"models":3,"points":145,"escalation":"3rd+"},{"models":6,"points":280,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Sanguinary Priest', 75, '[{"models":1,"points":75,"escalation":null},{"models":1,"points":85,"escalation":null},{"models":1,"points":85,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'The Sanguinor', 130, '[{"models":1,"points":130,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Aggressor Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Ancient in Terminator Armour', 65, '[{"models":1,"points":65,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Apothecary', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Apothecary Biologis', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Assault Intercessor Squad', 80, '[{"models":5,"points":80,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Assault Intercessors with Jump Packs', 95, '[{"models":5,"points":95,"escalation":null},{"models":10,"points":180,"escalation":null},{"models":5,"points":105,"escalation":null},{"models":10,"points":190,"escalation":null},{"models":5,"points":105,"escalation":"3rd+"},{"models":10,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Astraeus', 525, '[{"models":1,"points":525,"escalation":null},{"models":1,"points":575,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Ballistus Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Bladeguard Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Bladeguard Veteran Squad', 85, '[{"models":3,"points":85,"escalation":null},{"models":6,"points":170,"escalation":null},{"models":3,"points":95,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":95,"escalation":"3rd+"},{"models":6,"points":180,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Brutalis Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Captain', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Captain in Gravis Armour', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Captain in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Captain in Terminator Armour', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Captain with Jump Pack', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Centurion Assault Squad', 150, '[{"models":3,"points":150,"escalation":null},{"models":6,"points":300,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Centurion Devastator Squad', 175, '[{"models":3,"points":175,"escalation":null},{"models":6,"points":350,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Chaplain', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Chaplain in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Chaplain on Bike', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Chaplain with Jump Pack', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Company Heroes', 105, '[{"models":4,"points":105,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Desolation Squad', 180, '[{"models":5,"points":180,"escalation":null},{"models":5,"points":210,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Devastator Squad', 120, '[{"models":5,"points":120,"escalation":null},{"models":10,"points":200,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Dreadnought', 135, '[{"models":1,"points":135,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Drop Pod', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Eliminator Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Eradicator Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Eradicator Squad with Heavy Bolters', 70, '[{"models":3,"points":70,"escalation":null},{"models":3,"points":80,"escalation":null},{"models":3,"points":80,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Firestrike Servo-turrets', 75, '[{"models":1,"points":75,"escalation":null},{"models":2,"points":150,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Gladiator Lancer', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Gladiator Reaper', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Gladiator Valiant', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Hammerfall Bunker', 175, '[{"models":1,"points":175,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Heavy Intercessor Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Hellblaster Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":220,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Impulsor', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Inceptor Squad', 120, '[{"models":3,"points":120,"escalation":null},{"models":6,"points":240,"escalation":null},{"models":3,"points":135,"escalation":null},{"models":6,"points":255,"escalation":null},{"models":3,"points":135,"escalation":"3rd+"},{"models":6,"points":255,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Incursor Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":150,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Infernus Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":170,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Infiltrator Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":180,"escalation":null},{"models":5,"points":120,"escalation":null},{"models":10,"points":190,"escalation":null},{"models":5,"points":120,"escalation":"3rd+"},{"models":10,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Intercessor Squad', 80, '[{"models":5,"points":80,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Invader Atv', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Invictor Tactical Warsuit', 125, '[{"models":1,"points":125,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Judiciar', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Land Raider', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Land Raider Crusader', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Land Raider Redeemer', 250, '[{"models":1,"points":250,"escalation":null},{"models":1,"points":270,"escalation":null},{"models":1,"points":270,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Land Speeder', 95, '[{"models":1,"points":95,"escalation":null},{"models":1,"points":105,"escalation":null},{"models":1,"points":105,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Librarian', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Librarian in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Librarian in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Lieutenant', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Lieutenant in Phobos Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Lieutenant in Reiver Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Lieutenant with Combi-weapon', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Outrider Squad', 75, '[{"models":3,"points":75,"escalation":null},{"models":6,"points":140,"escalation":null},{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Predator Annihilator', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Predator Destructor', 140, '[{"models":1,"points":140,"escalation":null},{"models":1,"points":150,"escalation":null},{"models":1,"points":150,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Razorback', 95, '[{"models":1,"points":95,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Redemptor Dreadnought', 195, '[{"models":1,"points":195,"escalation":null},{"models":1,"points":210,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Reiver Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Repulsor', 170, '[{"models":1,"points":170,"escalation":null},{"models":1,"points":190,"escalation":null},{"models":1,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Repulsor Executioner', 230, '[{"models":1,"points":230,"escalation":null},{"models":1,"points":250,"escalation":null},{"models":1,"points":250,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Rhino', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Scout Squad', 65, '[{"models":5,"points":65,"escalation":null},{"models":10,"points":120,"escalation":null},{"models":5,"points":75,"escalation":null},{"models":10,"points":130,"escalation":null},{"models":5,"points":75,"escalation":"3rd+"},{"models":10,"points":130,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Sternguard Veteran Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":190,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Stormhawk Interceptor', 155, '[{"models":1,"points":155,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Stormraven Gunship', 280, '[{"models":1,"points":280,"escalation":null},{"models":1,"points":300,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Storm Speeder Hailstrike', 105, '[{"models":1,"points":105,"escalation":null},{"models":1,"points":115,"escalation":null},{"models":1,"points":115,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Storm Speeder Hammerstrike', 130, '[{"models":1,"points":130,"escalation":null},{"models":1,"points":140,"escalation":null},{"models":1,"points":140,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Storm Speeder Thunderstrike', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Stormtalon Gunship', 165, '[{"models":1,"points":165,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Suppressor Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Tactical Squad', 140, '[{"models":10,"points":140,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Techmarine', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Terminator Assault Squad', 155, '[{"models":5,"points":155,"escalation":null},{"models":10,"points":310,"escalation":null},{"models":1,"points":5,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Terminator Squad', 160, '[{"models":5,"points":160,"escalation":null},{"models":10,"points":320,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Thunderhawk Gunship', 840, '[{"models":1,"points":840,"escalation":null}]'::jsonb),
  ('Blood Angels', 'Vanguard Veteran Squad with Jump Packs', 105, '[{"models":5,"points":105,"escalation":null},{"models":10,"points":210,"escalation":null},{"models":5,"points":115,"escalation":null},{"models":10,"points":220,"escalation":null},{"models":5,"points":115,"escalation":"3rd+"},{"models":10,"points":220,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Vindicator', 185, '[{"models":1,"points":185,"escalation":null},{"models":1,"points":200,"escalation":null},{"models":1,"points":200,"escalation":"3rd+"}]'::jsonb),
  ('Blood Angels', 'Whirlwind', 175, '[{"models":1,"points":175,"escalation":null},{"models":1,"points":195,"escalation":null}]'::jsonb),
  ('Dark Angels', '1st Company Task Force2dp', 30, '[{"models":1,"points":30,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Anvil Siege Force2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Armoured Speartip3dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Bastion Task Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Ceramite Sentinels3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Company of Hunters2dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Dark Age Arsenal1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Darkflight Pursuit1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Firestorm Assault Force2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Fulguris Task Force1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Gladius Task Force3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Headhunter Task Force2dp', 40, '[{"models":1,"points":40,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Inner Circle Task Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Interrogation Conclave1dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Ironstorm Spearhead2dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Librarius Conclave1dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Lion’s Blade Task Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Orbital Assault Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Stormlance Task Force3dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Subversion Assets1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Unforgiven Task Force2dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Vanguard Spearhead2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Wrath of the Rock3dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Asmodai', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Azrael', 140, '[{"models":1,"points":140,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Belial', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Deathwing Terminator Squad', 165, '[{"models":5,"points":165,"escalation":null},{"models":10,"points":330,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Ezekiel', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Inner Circle Companions', 80, '[{"models":3,"points":80,"escalation":null},{"models":6,"points":170,"escalation":null},{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":90,"escalation":"3rd+"},{"models":6,"points":180,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Land Speeder Vengeance', 120, '[{"models":1,"points":120,"escalation":null},{"models":1,"points":130,"escalation":null},{"models":1,"points":130,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Lazarus', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Lion El’jonson', 285, '[{"models":1,"points":285,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Nephilim Jetfighter', 195, '[{"models":1,"points":195,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Ravenwing Black Knights', 75, '[{"models":3,"points":75,"escalation":null},{"models":6,"points":150,"escalation":null},{"models":3,"points":85,"escalation":null},{"models":6,"points":160,"escalation":null},{"models":3,"points":85,"escalation":"3rd+"},{"models":6,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Ravenwing Command Squad', 115, '[{"models":3,"points":115,"escalation":null},{"models":3,"points":125,"escalation":null},{"models":3,"points":125,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Ravenwing Darkshroud', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Ravenwing Dark Talon', 200, '[{"models":1,"points":200,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Sammael', 105, '[{"models":1,"points":105,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Aggressor Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Ancient in Terminator Armour', 65, '[{"models":1,"points":65,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Apothecary', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Apothecary Biologis', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Assault Intercessor Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Assault Intercessors with Jump Packs', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":170,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Astraeus', 525, '[{"models":1,"points":525,"escalation":null},{"models":1,"points":575,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Ballistus Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Bladeguard Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Bladeguard Veteran Squad', 80, '[{"models":3,"points":80,"escalation":null},{"models":6,"points":160,"escalation":null},{"models":3,"points":90,"escalation":null},{"models":6,"points":170,"escalation":null},{"models":3,"points":90,"escalation":"3rd+"},{"models":6,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Brutalis Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Captain', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Captain in Gravis Armour', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Captain in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Captain in Terminator Armour', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Captain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Centurion Assault Squad', 150, '[{"models":3,"points":150,"escalation":null},{"models":6,"points":300,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Centurion Devastator Squad', 175, '[{"models":3,"points":175,"escalation":null},{"models":6,"points":350,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Chaplain', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Chaplain in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Chaplain on Bike', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Chaplain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Company Heroes', 105, '[{"models":4,"points":105,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Desolation Squad', 180, '[{"models":5,"points":180,"escalation":null},{"models":5,"points":210,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Devastator Squad', 120, '[{"models":5,"points":120,"escalation":null},{"models":10,"points":200,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Dreadnought', 135, '[{"models":1,"points":135,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Drop Pod', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Eliminator Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Eradicator Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Eradicator Squad with Heavy Bolters', 70, '[{"models":3,"points":70,"escalation":null},{"models":3,"points":80,"escalation":null},{"models":3,"points":80,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Firestrike Servo-turrets', 75, '[{"models":1,"points":75,"escalation":null},{"models":2,"points":150,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Gladiator Lancer', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Gladiator Reaper', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Gladiator Valiant', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Hammerfall Bunker', 175, '[{"models":1,"points":175,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Heavy Intercessor Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Hellblaster Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":220,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Impulsor', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Inceptor Squad', 120, '[{"models":3,"points":120,"escalation":null},{"models":6,"points":240,"escalation":null},{"models":3,"points":135,"escalation":null},{"models":6,"points":255,"escalation":null},{"models":3,"points":135,"escalation":"3rd+"},{"models":6,"points":255,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Incursor Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":150,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Infernus Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":170,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Infiltrator Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":180,"escalation":null},{"models":5,"points":120,"escalation":null},{"models":10,"points":190,"escalation":null},{"models":5,"points":120,"escalation":"3rd+"},{"models":10,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Intercessor Squad', 80, '[{"models":5,"points":80,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Invader Atv', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Invictor Tactical Warsuit', 125, '[{"models":1,"points":125,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Judiciar', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Land Raider', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Land Raider Crusader', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Land Raider Redeemer', 250, '[{"models":1,"points":250,"escalation":null},{"models":1,"points":270,"escalation":null},{"models":1,"points":270,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Land Speeder', 95, '[{"models":1,"points":95,"escalation":null},{"models":1,"points":105,"escalation":null},{"models":1,"points":105,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Librarian', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Librarian in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Librarian in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Lieutenant', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Lieutenant in Phobos Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Lieutenant in Reiver Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Lieutenant with Combi-weapon', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Outrider Squad', 70, '[{"models":3,"points":70,"escalation":null},{"models":6,"points":140,"escalation":null},{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Predator Annihilator', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Predator Destructor', 140, '[{"models":1,"points":140,"escalation":null},{"models":1,"points":150,"escalation":null},{"models":1,"points":150,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Razorback', 95, '[{"models":1,"points":95,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Redemptor Dreadnought', 195, '[{"models":1,"points":195,"escalation":null},{"models":1,"points":210,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Reiver Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Repulsor', 170, '[{"models":1,"points":170,"escalation":null},{"models":1,"points":190,"escalation":null},{"models":1,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Repulsor Executioner', 230, '[{"models":1,"points":230,"escalation":null},{"models":1,"points":250,"escalation":null},{"models":1,"points":250,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Rhino', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Scout Squad', 65, '[{"models":5,"points":65,"escalation":null},{"models":10,"points":120,"escalation":null},{"models":5,"points":75,"escalation":null},{"models":10,"points":130,"escalation":null},{"models":5,"points":75,"escalation":"3rd+"},{"models":10,"points":130,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Sternguard Veteran Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":190,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Stormhawk Interceptor', 155, '[{"models":1,"points":155,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Stormraven Gunship', 280, '[{"models":1,"points":280,"escalation":null},{"models":1,"points":300,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Storm Speeder Hailstrike', 105, '[{"models":1,"points":105,"escalation":null},{"models":1,"points":115,"escalation":null},{"models":1,"points":115,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Storm Speeder Hammerstrike', 130, '[{"models":1,"points":130,"escalation":null},{"models":1,"points":140,"escalation":null},{"models":1,"points":140,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Storm Speeder Thunderstrike', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Stormtalon Gunship', 165, '[{"models":1,"points":165,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Suppressor Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Tactical Squad', 140, '[{"models":10,"points":140,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Techmarine', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Terminator Assault Squad', 155, '[{"models":5,"points":155,"escalation":null},{"models":10,"points":310,"escalation":null},{"models":1,"points":5,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Terminator Squad', 160, '[{"models":5,"points":160,"escalation":null},{"models":10,"points":320,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Thunderhawk Gunship', 840, '[{"models":1,"points":840,"escalation":null}]'::jsonb),
  ('Dark Angels', 'Vanguard Veteran Squad with Jump Packs', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null},{"models":5,"points":110,"escalation":null},{"models":10,"points":210,"escalation":null},{"models":5,"points":110,"escalation":"3rd+"},{"models":10,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Vindicator', 185, '[{"models":1,"points":185,"escalation":null},{"models":1,"points":200,"escalation":null},{"models":1,"points":200,"escalation":"3rd+"}]'::jsonb),
  ('Dark Angels', 'Whirlwind', 175, '[{"models":1,"points":175,"escalation":null},{"models":1,"points":195,"escalation":null}]'::jsonb),
  ('Deathwatch', '1st Company Task Force2dp', 30, '[{"models":1,"points":30,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Anvil Siege Force2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Armoured Speartip3dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Bastion Task Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Black Spear Task Force3dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Ceramite Sentinels3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Firestorm Assault Force2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Fulguris Task Force1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Gladius Task Force3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Headhunter Task Force2dp', 40, '[{"models":1,"points":40,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Ironstorm Spearhead2dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Librarius Conclave1dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Orbital Assault Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Stormlance Task Force2dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Subversion Assets1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Vanguard Spearhead2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Corvus Blackstar', 180, '[{"models":1,"points":180,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Deathwatch Terminator Squad', 180, '[{"models":5,"points":180,"escalation":null},{"models":10,"points":330,"escalation":null},{"models":1,"points":5,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Deathwatch Veterans', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":190,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Decimus Kill Team', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":190,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Indomitor Kill Team', 275, '[{"models":10,"points":275,"escalation":null},{"models":10,"points":290,"escalation":null},{"models":10,"points":290,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Spectrus Kill Team', 170, '[{"models":10,"points":170,"escalation":null},{"models":10,"points":180,"escalation":null},{"models":10,"points":180,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Talonstrike Kill Team', 265, '[{"models":10,"points":265,"escalation":null},{"models":10,"points":280,"escalation":null},{"models":10,"points":280,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Watch Captain Artemis', 65, '[{"models":1,"points":65,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Watch Master', 95, '[{"models":1,"points":95,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Aggressor Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Ancient in Terminator Armour', 65, '[{"models":1,"points":65,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Apothecary', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Apothecary Biologis', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Assault Intercessor Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Assault Intercessors with Jump Packs', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":170,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Astraeus', 525, '[{"models":1,"points":525,"escalation":null},{"models":1,"points":575,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Ballistus Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Bladeguard Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Bladeguard Veteran Squad', 80, '[{"models":3,"points":80,"escalation":null},{"models":6,"points":160,"escalation":null},{"models":3,"points":90,"escalation":null},{"models":6,"points":170,"escalation":null},{"models":3,"points":90,"escalation":"3rd+"},{"models":6,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Brutalis Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Captain', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Captain in Gravis Armour', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Captain in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Captain in Terminator Armour', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Captain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Centurion Assault Squad', 150, '[{"models":3,"points":150,"escalation":null},{"models":6,"points":300,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Centurion Devastator Squad', 175, '[{"models":3,"points":175,"escalation":null},{"models":6,"points":350,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Chaplain', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Chaplain in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Chaplain on Bike', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Chaplain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Company Heroes', 105, '[{"models":4,"points":105,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Desolation Squad', 180, '[{"models":5,"points":180,"escalation":null},{"models":5,"points":210,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Dreadnought', 135, '[{"models":1,"points":135,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Drop Pod', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Eliminator Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Eradicator Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Eradicator Squad with Heavy Bolters', 70, '[{"models":3,"points":70,"escalation":null},{"models":3,"points":80,"escalation":null},{"models":3,"points":80,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Firestrike Servo-turrets', 75, '[{"models":1,"points":75,"escalation":null},{"models":2,"points":150,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Gladiator Lancer', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Gladiator Reaper', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Gladiator Valiant', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Hammerfall Bunker', 175, '[{"models":1,"points":175,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Heavy Intercessor Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Hellblaster Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":220,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Impulsor', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Inceptor Squad', 120, '[{"models":3,"points":120,"escalation":null},{"models":6,"points":240,"escalation":null},{"models":3,"points":135,"escalation":null},{"models":6,"points":255,"escalation":null},{"models":3,"points":135,"escalation":"3rd+"},{"models":6,"points":255,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Incursor Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":150,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Infernus Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":170,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Infiltrator Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":180,"escalation":null},{"models":5,"points":120,"escalation":null},{"models":10,"points":190,"escalation":null},{"models":5,"points":120,"escalation":"3rd+"},{"models":10,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Intercessor Squad', 80, '[{"models":5,"points":80,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Invader Atv', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Invictor Tactical Warsuit', 125, '[{"models":1,"points":125,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Judiciar', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Land Raider', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Land Raider Crusader', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Land Raider Redeemer', 250, '[{"models":1,"points":250,"escalation":null},{"models":1,"points":270,"escalation":null},{"models":1,"points":270,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Land Speeder', 95, '[{"models":1,"points":95,"escalation":null},{"models":1,"points":105,"escalation":null},{"models":1,"points":105,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Librarian', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Librarian in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Librarian in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Lieutenant', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Lieutenant in Phobos Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Lieutenant in Reiver Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Lieutenant with Combi-weapon', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Outrider Squad', 70, '[{"models":3,"points":70,"escalation":null},{"models":6,"points":140,"escalation":null},{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Predator Annihilator', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Predator Destructor', 140, '[{"models":1,"points":140,"escalation":null},{"models":1,"points":150,"escalation":null},{"models":1,"points":150,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Razorback', 95, '[{"models":1,"points":95,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Redemptor Dreadnought', 195, '[{"models":1,"points":195,"escalation":null},{"models":1,"points":210,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Reiver Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Repulsor', 170, '[{"models":1,"points":170,"escalation":null},{"models":1,"points":190,"escalation":null},{"models":1,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Repulsor Executioner', 230, '[{"models":1,"points":230,"escalation":null},{"models":1,"points":250,"escalation":null},{"models":1,"points":250,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Rhino', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Sternguard Veteran Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":190,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Stormhawk Interceptor', 155, '[{"models":1,"points":155,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Stormraven Gunship', 280, '[{"models":1,"points":280,"escalation":null},{"models":1,"points":300,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Storm Speeder Hailstrike', 105, '[{"models":1,"points":105,"escalation":null},{"models":1,"points":115,"escalation":null},{"models":1,"points":115,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Storm Speeder Hammerstrike', 130, '[{"models":1,"points":130,"escalation":null},{"models":1,"points":140,"escalation":null},{"models":1,"points":140,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Storm Speeder Thunderstrike', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Stormtalon Gunship', 165, '[{"models":1,"points":165,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Suppressor Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Techmarine', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Thunderhawk Gunship', 840, '[{"models":1,"points":840,"escalation":null}]'::jsonb),
  ('Deathwatch', 'Vanguard Veteran Squad with Jump Packs', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null},{"models":5,"points":110,"escalation":null},{"models":10,"points":210,"escalation":null},{"models":5,"points":110,"escalation":"3rd+"},{"models":10,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Vindicator', 185, '[{"models":1,"points":185,"escalation":null},{"models":1,"points":200,"escalation":null},{"models":1,"points":200,"escalation":"3rd+"}]'::jsonb),
  ('Deathwatch', 'Whirlwind', 175, '[{"models":1,"points":175,"escalation":null},{"models":1,"points":195,"escalation":null}]'::jsonb),
  ('Space Wolves', '1st Company Task Force2dp', 30, '[{"models":1,"points":30,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Anvil Siege Force2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Armoured Speartip3dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Bastion Task Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Ceramite Sentinels3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Champions of Fenris1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Firestorm Assault Force2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Fulguris Task Force1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Gladius Task Force3dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Headhunter Task Force2dp', 40, '[{"models":1,"points":40,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Ironstorm Spearhead2dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":10,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Legends of Saga and Song1dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Librarius Conclave1dp', 35, '[{"models":1,"points":35,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Orbital Assault Force2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Saga of the Beastslayer2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Saga of the Bold2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Saga of the Great Wolf2dp', 25, '[{"models":1,"points":25,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Saga of the Hunter2dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":20,"escalation":null},{"models":1,"points":5,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Stormlance Task Force3dp', 10, '[{"models":1,"points":10,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":25,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Subversion Assets1dp', 15, '[{"models":1,"points":15,"escalation":null},{"models":1,"points":20,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Vanguard Spearhead2dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null},{"models":1,"points":30,"escalation":null},{"models":1,"points":25,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Veterans of the Fang1dp', 20, '[{"models":1,"points":20,"escalation":null},{"models":1,"points":15,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Arjac Rockfist', 105, '[{"models":1,"points":105,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Bjorn the Fell-handed', 160, '[{"models":1,"points":160,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Blood Claws', 135, '[{"models":10,"points":135,"escalation":null},{"models":20,"points":270,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Fenrisian Wolves', 45, '[{"models":5,"points":45,"escalation":null},{"models":10,"points":75,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Grey Hunters', 165, '[{"models":10,"points":165,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Iron Priest', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Logan Grimnar', 110, '[{"models":1,"points":110,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Murderfang', 150, '[{"models":1,"points":150,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Njal Stormcaller', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Ragnar Blackmane', 100, '[{"models":1,"points":100,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Thunderwolf Cavalry', 100, '[{"models":3,"points":100,"escalation":null},{"models":6,"points":200,"escalation":null},{"models":3,"points":110,"escalation":null},{"models":6,"points":210,"escalation":null},{"models":1,"points":5,"escalation":null},{"models":3,"points":110,"escalation":"3rd+"},{"models":6,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Ulrik the Slayer', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Venerable Dreadnought', 125, '[{"models":1,"points":125,"escalation":null},{"models":1,"points":135,"escalation":null},{"models":1,"points":135,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Wolf Guard Battle Leader', 65, '[{"models":1,"points":65,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Wolf Guard Headtakers', 85, '[{"models":1,"points":85,"escalation":null},{"models":1,"points":115,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":230,"escalation":null},{"models":1,"points":95,"escalation":null},{"models":1,"points":125,"escalation":null},{"models":1,"points":180,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":95,"escalation":"3rd+"},{"models":1,"points":125,"escalation":"3rd+"},{"models":1,"points":180,"escalation":"3rd+"},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Wolf Guard Terminators', 150, '[{"models":5,"points":150,"escalation":null},{"models":10,"points":300,"escalation":null},{"models":5,"points":160,"escalation":null},{"models":10,"points":310,"escalation":null},{"models":1,"points":5,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Wolf Priest', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Wolf Scouts', 95, '[{"models":6,"points":95,"escalation":null},{"models":12,"points":190,"escalation":null},{"models":6,"points":105,"escalation":null},{"models":12,"points":200,"escalation":null},{"models":6,"points":105,"escalation":"3rd+"},{"models":12,"points":200,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Wulfen', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":170,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":180,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":180,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Wulfen Dreadnought', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Wulfen with Storm Shields', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null},{"models":5,"points":110,"escalation":null},{"models":10,"points":210,"escalation":null},{"models":5,"points":110,"escalation":"3rd+"},{"models":10,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Aggressor Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Ancient in Terminator Armour', 65, '[{"models":1,"points":65,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Assault Intercessor Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Assault Intercessors with Jump Packs', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":170,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Astraeus', 525, '[{"models":1,"points":525,"escalation":null},{"models":1,"points":575,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Ballistus Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Bladeguard Ancient', 40, '[{"models":1,"points":40,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Bladeguard Veteran Squad', 80, '[{"models":3,"points":80,"escalation":null},{"models":6,"points":160,"escalation":null},{"models":3,"points":90,"escalation":null},{"models":6,"points":170,"escalation":null},{"models":3,"points":90,"escalation":"3rd+"},{"models":6,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Brutalis Dreadnought', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Captain', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Captain in Gravis Armour', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Captain in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Captain in Terminator Armour', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Captain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Centurion Assault Squad', 150, '[{"models":3,"points":150,"escalation":null},{"models":6,"points":300,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Centurion Devastator Squad', 175, '[{"models":3,"points":175,"escalation":null},{"models":6,"points":350,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Chaplain', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Chaplain in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Chaplain on Bike', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Chaplain with Jump Pack', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Company Heroes', 105, '[{"models":4,"points":105,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Desolation Squad', 180, '[{"models":5,"points":180,"escalation":null},{"models":5,"points":210,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Dreadnought', 135, '[{"models":1,"points":135,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Drop Pod', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Eliminator Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Eradicator Squad', 90, '[{"models":3,"points":90,"escalation":null},{"models":6,"points":180,"escalation":null},{"models":3,"points":100,"escalation":null},{"models":6,"points":190,"escalation":null},{"models":3,"points":100,"escalation":"3rd+"},{"models":6,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Eradicator Squad with Heavy Bolters', 70, '[{"models":3,"points":70,"escalation":null},{"models":3,"points":80,"escalation":null},{"models":3,"points":80,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Firestrike Servo-turrets', 75, '[{"models":1,"points":75,"escalation":null},{"models":2,"points":150,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Gladiator Lancer', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Gladiator Reaper', 160, '[{"models":1,"points":160,"escalation":null},{"models":1,"points":170,"escalation":null},{"models":1,"points":170,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Gladiator Valiant', 150, '[{"models":1,"points":150,"escalation":null},{"models":1,"points":160,"escalation":null},{"models":1,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Hammerfall Bunker', 175, '[{"models":1,"points":175,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Heavy Intercessor Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Hellblaster Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":220,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Impulsor', 80, '[{"models":1,"points":80,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Inceptor Squad', 120, '[{"models":3,"points":120,"escalation":null},{"models":6,"points":240,"escalation":null},{"models":3,"points":135,"escalation":null},{"models":6,"points":255,"escalation":null},{"models":3,"points":135,"escalation":"3rd+"},{"models":6,"points":255,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Incursor Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":150,"escalation":null},{"models":5,"points":95,"escalation":null},{"models":10,"points":160,"escalation":null},{"models":5,"points":95,"escalation":"3rd+"},{"models":10,"points":160,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Infernus Squad', 85, '[{"models":5,"points":85,"escalation":null},{"models":10,"points":170,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Infiltrator Squad', 110, '[{"models":5,"points":110,"escalation":null},{"models":10,"points":180,"escalation":null},{"models":5,"points":120,"escalation":null},{"models":10,"points":190,"escalation":null},{"models":5,"points":120,"escalation":"3rd+"},{"models":10,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Intercessor Squad', 80, '[{"models":5,"points":80,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Invader Atv', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Invictor Tactical Warsuit', 125, '[{"models":1,"points":125,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Judiciar', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Land Raider', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Land Raider Crusader', 220, '[{"models":1,"points":220,"escalation":null},{"models":1,"points":240,"escalation":null},{"models":1,"points":240,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Land Raider Redeemer', 250, '[{"models":1,"points":250,"escalation":null},{"models":1,"points":270,"escalation":null},{"models":1,"points":270,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Land Speeder', 95, '[{"models":1,"points":95,"escalation":null},{"models":1,"points":105,"escalation":null},{"models":1,"points":105,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Librarian', 60, '[{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Librarian in Phobos Armour', 70, '[{"models":1,"points":70,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Librarian in Terminator Armour', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Lieutenant', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Lieutenant in Phobos Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Lieutenant in Reiver Armour', 45, '[{"models":1,"points":45,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Lieutenant with Combi-weapon', 85, '[{"models":1,"points":85,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Outrider Squad', 70, '[{"models":3,"points":70,"escalation":null},{"models":6,"points":140,"escalation":null},{"models":1,"points":60,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Predator Annihilator', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Predator Destructor', 140, '[{"models":1,"points":140,"escalation":null},{"models":1,"points":150,"escalation":null},{"models":1,"points":150,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Razorback', 95, '[{"models":1,"points":95,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Redemptor Dreadnought', 195, '[{"models":1,"points":195,"escalation":null},{"models":1,"points":210,"escalation":null},{"models":1,"points":10,"escalation":null},{"models":1,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Reiver Squad', 75, '[{"models":5,"points":75,"escalation":null},{"models":10,"points":150,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Repulsor', 170, '[{"models":1,"points":170,"escalation":null},{"models":1,"points":190,"escalation":null},{"models":1,"points":190,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Repulsor Executioner', 230, '[{"models":1,"points":230,"escalation":null},{"models":1,"points":250,"escalation":null},{"models":1,"points":250,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Rhino', 75, '[{"models":1,"points":75,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Scout Squad', 65, '[{"models":5,"points":65,"escalation":null},{"models":10,"points":120,"escalation":null},{"models":5,"points":75,"escalation":null},{"models":10,"points":130,"escalation":null},{"models":5,"points":75,"escalation":"3rd+"},{"models":10,"points":130,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Sternguard Veteran Squad', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":190,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Stormhawk Interceptor', 155, '[{"models":1,"points":155,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Stormraven Gunship', 280, '[{"models":1,"points":280,"escalation":null},{"models":1,"points":300,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Storm Speeder Hailstrike', 105, '[{"models":1,"points":105,"escalation":null},{"models":1,"points":115,"escalation":null},{"models":1,"points":115,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Storm Speeder Hammerstrike', 130, '[{"models":1,"points":130,"escalation":null},{"models":1,"points":140,"escalation":null},{"models":1,"points":140,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Storm Speeder Thunderstrike', 135, '[{"models":1,"points":135,"escalation":null},{"models":1,"points":145,"escalation":null},{"models":1,"points":145,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Stormtalon Gunship', 165, '[{"models":1,"points":165,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Suppressor Squad', 75, '[{"models":3,"points":75,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Techmarine', 55, '[{"models":1,"points":55,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Terminator Assault Squad', 155, '[{"models":5,"points":155,"escalation":null},{"models":10,"points":310,"escalation":null},{"models":1,"points":5,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Terminator Squad', 160, '[{"models":5,"points":160,"escalation":null},{"models":10,"points":320,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Thunderhawk Gunship', 840, '[{"models":1,"points":840,"escalation":null}]'::jsonb),
  ('Space Wolves', 'Vanguard Veteran Squad with Jump Packs', 100, '[{"models":5,"points":100,"escalation":null},{"models":10,"points":200,"escalation":null},{"models":5,"points":110,"escalation":null},{"models":10,"points":210,"escalation":null},{"models":5,"points":110,"escalation":"3rd+"},{"models":10,"points":210,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Vindicator', 185, '[{"models":1,"points":185,"escalation":null},{"models":1,"points":200,"escalation":null},{"models":1,"points":200,"escalation":"3rd+"}]'::jsonb),
  ('Space Wolves', 'Whirlwind', 175, '[{"models":1,"points":175,"escalation":null},{"models":1,"points":195,"escalation":null}]'::jsonb);