-- Munitorum Field Manual v4.4 - Complete Unit Points Registry
-- Generated 2026-06-06T06:16:30.350Z
-- Total units: 1388

DELETE FROM unit_points;

INSERT INTO unit_points (faction, unit_name, base_points)
VALUES
  ('Adepta Sororitas', 'Aestred Thurga and Agathae Dolan', 70),
  ('Adepta Sororitas', 'Penitent Engines', 75),
  ('Adepta Sororitas', 'Arco-flagellants', 45),
  ('Adepta Sororitas', 'Repentia Squad', 75),
  ('Adepta Sororitas', 'Battle Sisters Squad', 105),
  ('Adepta Sororitas', 'Retributor Squad', 120),
  ('Adepta Sororitas', 'Canoness', 60),
  ('Adepta Sororitas', 'Saint Celestine', 150),
  ('Adepta Sororitas', 'Canoness with Jump Pack', 75),
  ('Adepta Sororitas', 'Sanctifiers', 110),
  ('Adepta Sororitas', 'Castigator', 160),
  ('Adepta Sororitas', 'Seraphim Squad', 80),
  ('Adepta Sororitas', 'Celestian Insidiants', 120),
  ('Adepta Sororitas', 'Sisters Novitiate Squad', 100),
  ('Adepta Sororitas', 'Celestian Sacresants', 70),
  ('Adepta Sororitas', 'Sororitas Rhino', 75),
  ('Adepta Sororitas', 'Daemonifuge', 85),
  ('Adepta Sororitas', 'Triumph of Saint Katherine', 235),
  ('Adepta Sororitas', 'Dialogus', 40),
  ('Adepta Sororitas', 'Zephyrim Squad', 80),
  ('Adepta Sororitas', 'Dogmata', 45),
  ('Adepta Sororitas', 'Dominion Squad', 120),
  ('Adepta Sororitas', 'Exorcist', 210),
  ('Adepta Sororitas', 'Hospitaller', 60),
  ('Adepta Sororitas', 'Imagifier', 65),
  ('Adepta Sororitas', 'Immolator', 115),
  ('Adepta Sororitas', 'Intranzia Fraye', 150),
  ('Adepta Sororitas', 'Junith Eruita', 80),
  ('Adepta Sororitas', 'Ministorum Priest', 50),
  ('Adepta Sororitas', 'Mortifiers', 70),
  ('Adepta Sororitas', 'Morvenn Vahl', 185),
  ('Adepta Sororitas', 'Palatine', 50),
  ('Adepta Sororitas', 'Paragon Warsuits', 210),
  ('Adeptus Custodes', 'Aleya', 65),
  ('Adeptus Custodes', 'Agamatus Custodians', 225),
  ('Adeptus Custodes', 'Allarus Custodians', 110),
  ('Adeptus Custodes', 'Aquilon Custodians', 195),
  ('Adeptus Custodes', 'Anathema Psykana Rhino', 75),
  ('Adeptus Custodes', 'Ares Gunship', 580),
  ('Adeptus Custodes', 'Blade Champion', 120),
  ('Adeptus Custodes', 'Caladius Grav-tank', 215),
  ('Adeptus Custodes', 'Custodian Guard', 160),
  ('Adeptus Custodes', 'Contemptor-Achillus Dreadnought', 155),
  ('Adeptus Custodes', 'Custodian Wardens', 210),
  ('Adeptus Custodes', 'Contemptor-Galatus Dreadnought', 165),
  ('Adeptus Custodes', 'Coronus Grav-carrier', 200),
  ('Adeptus Custodes', 'Knight-Centura', 55),
  ('Adeptus Custodes', 'Custodian Guard with Adrasite and Pyrithite Spears', 250),
  ('Adeptus Custodes', 'Prosecutors', 40),
  ('Adeptus Custodes', 'Orion Assault Dropship', 690),
  ('Adeptus Custodes', 'Pallas Grav-attack', 105),
  ('Adeptus Custodes', 'Shield-Captain', 120),
  ('Adeptus Custodes', 'Sagittarum Custodians', 225),
  ('Adeptus Custodes', 'Shield-Captain in Allarus Terminator Armour', 130),
  ('Adeptus Custodes', 'Telemon Heavy Dreadnought', 225),
  ('Adeptus Custodes', 'Shield-Captain on Dawneagle Jetbike', 150),
  ('Adeptus Custodes', 'Venatari Custodians', 165),
  ('Adeptus Custodes', 'Trajann Valoris', 140),
  ('Adeptus Custodes', 'Valerian', 110),
  ('Adeptus Custodes', 'Venerable Contemptor Dreadnought', 170),
  ('Adeptus Custodes', 'Venerable Land Raider', 220),
  ('Adeptus Custodes', 'Vertus Praetors', 150),
  ('Adeptus Custodes', 'Vigilators', 45),
  ('Adeptus Custodes', 'Witchseekers', 45),
  ('Adeptus Mechanicus', 'Archaeopter Fusilave', 160),
  ('Adeptus Mechanicus', 'Sicarian Ruststalkers', 80),
  ('Adeptus Mechanicus', 'Archaeopter Stratoraptor', 185),
  ('Adeptus Mechanicus', 'Skitarii Marshal', 35),
  ('Adeptus Mechanicus', 'Archaeopter Transvector', 150),
  ('Adeptus Mechanicus', 'Skitarii Rangers', 85),
  ('Adeptus Mechanicus', 'Belisarius Cawl', 210),
  ('Adeptus Mechanicus', 'Skitarii Vanguard', 95),
  ('Adeptus Mechanicus', 'Corpuscarii Electro-Priests', 65),
  ('Adeptus Mechanicus', 'Skorpius Disintegrator', 165),
  ('Adeptus Mechanicus', 'Cybernetica Datasmith', 35),
  ('Adeptus Mechanicus', 'Skorpius Dunerider', 85),
  ('Adeptus Mechanicus', 'Fulgurite Electro-Priests', 70),
  ('Adeptus Mechanicus', 'Sydonian Dragoons with Radium Jezzails', 55),
  ('Adeptus Mechanicus', 'Hastarii Exterminators', 135),
  ('Adeptus Mechanicus', 'Sydonian Dragoons with Taser Lances', 65),
  ('Adeptus Mechanicus', 'Hastarii Fusiliers', 145),
  ('Adeptus Mechanicus', 'Ironstrider Ballistarii', 85),
  ('Adeptus Mechanicus', 'Sydonian Skatros', 50),
  ('Adeptus Mechanicus', 'Tech-Priest Dominus', 65),
  ('Adeptus Mechanicus', 'Kastelan Robots', 180),
  ('Adeptus Mechanicus', 'Tech-Priest Enginseer', 55),
  ('Adeptus Mechanicus', 'Kataphron Breachers', 160),
  ('Adeptus Mechanicus', 'Tech-Priest Manipulus', 60),
  ('Adeptus Mechanicus', 'Technoarcheologist', 45),
  ('Adeptus Mechanicus', 'Kataphron Destroyers', 105),
  ('Adeptus Mechanicus', 'Thulia Ghuld', 210),
  ('Adeptus Mechanicus', 'Onager Dunecrawler', 155),
  ('Adeptus Mechanicus', 'Pteraxii Skystalkers', 75),
  ('Adeptus Mechanicus', 'Pteraxii Sterylizors', 80),
  ('Adeptus Mechanicus', 'Serberys Raiders', 60),
  ('Adeptus Mechanicus', 'Serberys Sulphurhounds', 55),
  ('Adeptus Mechanicus', 'Servitor Battleclade', 60),
  ('Adeptus Mechanicus', 'Sicarian Infiltrators', 75),
  ('Adeptus Titanicus', 'Reaver Titan', 2200),
  ('Adeptus Titanicus', 'Warbringer Nemesis Titan', 2600),
  ('Adeptus Titanicus', 'Warhound Titan', 1100),
  ('Adeptus Titanicus', 'Warlord Titan', 3500),
  ('Aeldari', 'Asurmen', 135),
  ('Aeldari', 'Howling Banshees', 95),
  ('Aeldari', 'Autarch', 85),
  ('Aeldari', 'Jain Zar', 120),
  ('Aeldari', 'Autarch Wayleaper', 80),
  ('Aeldari', 'Kharseth', 95),
  ('Aeldari', 'Avatar of Khaine', 280),
  ('Aeldari', 'Lhykhis', 135),
  ('Aeldari', 'Baharroth', 115),
  ('Aeldari', 'Maugan Ra', 100),
  ('Aeldari', 'Corsair Skyreavers', 75),
  ('Aeldari', 'Night Spinner', 190),
  ('Aeldari', 'Corsair Voidreavers', 65),
  ('Aeldari', 'Prince Yriel', 95),
  ('Aeldari', 'Rangers', 55),
  ('Aeldari', 'Corsair Voidscarred', 80),
  ('Aeldari', 'Shadow Weaver Platform', 75),
  ('Aeldari', 'Crimson Hunter', 160),
  ('Aeldari', 'Shadowseer', 60),
  ('Aeldari', 'D-cannon Platform', 125),
  ('Aeldari', 'Shining Spears', 110),
  ('Aeldari', 'Dark Reapers', 90),
  ('Aeldari', 'Shroud Runners', 80),
  ('Aeldari', 'Death Jester', 90),
  ('Aeldari', 'Dire Avengers', 75),
  ('Aeldari', 'Skyweavers', 95),
  ('Aeldari', 'Eldrad Ulthran', 120),
  ('Aeldari', 'Solitaire', 115),
  ('Aeldari', 'Falcon', 130),
  ('Aeldari', 'Spiritseer', 65),
  ('Aeldari', 'Farseer', 70),
  ('Aeldari', 'Starweaver', 80),
  ('Aeldari', 'Farseer Skyrunner', 80),
  ('Aeldari', 'Starfang', 75),
  ('Aeldari', 'Fire Dragons', 120),
  ('Aeldari', 'Storm Guardians', 110),
  ('Aeldari', 'Fire Prism', 150),
  ('Aeldari', 'Striking Scorpions', 85),
  ('Aeldari', 'Fuegan', 120),
  ('Aeldari', 'Swooping Hawks', 95),
  ('Aeldari', 'Guardian Defenders', 100),
  ('Aeldari', 'Hemlock Wraithfighter', 155),
  ('Aeldari', 'Troupe', 85),
  ('Aeldari', 'Troupe Master', 75),
  ('Aeldari', 'Vibro Cannon Platform', 60),
  ('Aeldari', 'Voidweaver', 125),
  ('Aeldari', 'Vyper', 75),
  ('Aeldari', 'War Walker', 85),
  ('Aeldari', 'Warlock', 45),
  ('Aeldari', 'Warlock Conclave', 55),
  ('Aeldari', 'Warlock Skyrunners', 45),
  ('Aeldari', 'Warp Spiders', 105),
  ('Aeldari', 'Wave Serpent', 125),
  ('Aeldari', 'Windriders', 80),
  ('Aeldari', 'Wraithblades', 150),
  ('Aeldari', 'Wraithguard', 160),
  ('Aeldari', 'Wraithknight', 435),
  ('Aeldari', 'Wraithknight with Ghostglaive', 420),
  ('Aeldari', 'Wraithlord', 130),
  ('Aeldari', 'The Visarch', 90),
  ('Aeldari', 'The Yncarne', 260),
  ('Aeldari', 'Ynnari Archon', 85),
  ('Aeldari', 'Ynnari Incubi', 85),
  ('Aeldari', 'Ynnari Kabalite Warriors', 110),
  ('Aeldari', 'Ynnari Raider', 80),
  ('Aeldari', 'Ynnari Reavers', 65),
  ('Aeldari', 'Ynnari Succubus', 45),
  ('Aeldari', 'Ynnari Venom', 70),
  ('Aeldari', 'Ynnari Wyches', 90),
  ('Aeldari', 'Yvraine', 100),
  ('Aeldari', 'Phantom Titan', 2100),
  ('Aeldari', 'Revenant Titan', 1100),
  ('Astra Militarum', 'Aegis Defence Line', 145),
  ('Astra Militarum', 'Commissar Yarrick', 150),
  ('Astra Militarum', 'Armoured Sentinels', 65),
  ('Astra Militarum', 'Death Korps of Krieg', 65),
  ('Astra Militarum', 'Artillery Team', 95),
  ('Astra Militarum', 'Death Riders', 60),
  ('Astra Militarum', 'Attilan Rough Riders', 60),
  ('Astra Militarum', 'Deathstrike', 145),
  ('Astra Militarum', 'Baneblade', 450),
  ('Astra Militarum', 'Doomhammer', 415),
  ('Astra Militarum', 'Banehammer', 420),
  ('Astra Militarum', 'Field Ordnance Battery', 110),
  ('Astra Militarum', 'Banesword', 450),
  ('Astra Militarum', 'Gaunt’s Ghosts', 100),
  ('Astra Militarum', 'Basilisk', 140),
  ('Astra Militarum', 'Hellhammer', 420),
  ('Astra Militarum', 'Bullgryn Squad', 100),
  ('Astra Militarum', 'Hellhound', 125),
  ('Astra Militarum', 'Hippogriff AFV', 70),
  ('Astra Militarum', 'Cadian Castellan', 55),
  ('Astra Militarum', 'Cadian Command Squad', 65),
  ('Astra Militarum', 'Hydra', 95),
  ('Astra Militarum', 'Cadian Heavy Weapons Squad', 65),
  ('Astra Militarum', 'Kasrkin', 110),
  ('Astra Militarum', 'Cadian Recon Squad', 80),
  ('Astra Militarum', 'Krieg Combat Engineers', 60),
  ('Astra Militarum', 'Cadian Shock Troops', 65),
  ('Astra Militarum', 'Krieg Command Squad', 65),
  ('Astra Militarum', 'Catachan Command Squad', 65),
  ('Astra Militarum', 'Krieg Heavy Weapons Squad', 75),
  ('Astra Militarum', 'Catachan Heavy Weapons Squad', 65),
  ('Astra Militarum', 'Leman Russ Battle Tank', 185),
  ('Astra Militarum', 'Catachan Jungle Fighters', 65),
  ('Astra Militarum', 'Leman Russ Commander', 235),
  ('Astra Militarum', 'Leman Russ Demolisher', 190),
  ('Astra Militarum', 'Centaur RSV', 85),
  ('Astra Militarum', 'Leman Russ Eradicator', 170),
  ('Astra Militarum', 'Chimera', 85),
  ('Astra Militarum', 'Leman Russ Executioner', 170),
  ('Astra Militarum', 'Commissar', 30),
  ('Astra Militarum', 'Leman Russ Exterminator', 180),
  ('Astra Militarum', 'Commissar Graves', 110),
  ('Astra Militarum', 'Leman Russ Punisher', 150),
  ('Astra Militarum', 'Commissar Graves on Foot', 65),
  ('Astra Militarum', 'Leman Russ Vanquisher', 145),
  ('Astra Militarum', 'Lord Marshal Dreir', 100),
  ('Astra Militarum', 'Lord Solar Leontus', 130),
  ('Astra Militarum', 'Manticore', 165),
  ('Astra Militarum', 'Militarum Tempestus Command Squad', 85),
  ('Astra Militarum', 'Ministorum Priest', 35),
  ('Astra Militarum', 'Nork Deddog', 60),
  ('Astra Militarum', 'Ogryn Bodyguard', 40),
  ('Astra Militarum', 'Ogryn Squad', 60),
  ('Astra Militarum', 'Primaris Psyker', 60),
  ('Astra Militarum', 'Ratlings', 60),
  ('Astra Militarum', 'Rogal Dorn Battle Tank', 260),
  ('Astra Militarum', 'Rogal Dorn Commander', 290),
  ('Astra Militarum', 'Scout Sentinels', 55),
  ('Astra Militarum', 'Shadowsword', 410),
  ('Astra Militarum', 'Sly Marbo', 55),
  ('Astra Militarum', 'Stormlord', 430),
  ('Astra Militarum', 'Stormsword', 465),
  ('Astra Militarum', 'Taurox', 75),
  ('Astra Militarum', 'Taurox Prime', 90),
  ('Astra Militarum', 'Tech-priest Enginseer', 45),
  ('Astra Militarum', 'Tempestus Aquilons', 100),
  ('Astra Militarum', 'Tempestus Scions', 70),
  ('Astra Militarum', 'Ursula Creed', 85),
  ('Astra Militarum', 'Valkyrie', 190),
  ('Astra Militarum', 'Wyvern', 110),
  ('Astra Militarum', 'Avenger Strike Fighter', 130),
  ('Astra Militarum', 'Cyclops Demolition Vehicle', 25),
  ('Black Templars', 'Castellan', 70),
  ('Black Templars', 'Chaplain Grimaldus', 110),
  ('Black Templars', 'Crusade Ancient', 55),
  ('Black Templars', 'Emperor’s Champion', 100),
  ('Black Templars', 'Execrator', 60),
  ('Black Templars', 'Gladiator Lancer', 160),
  ('Black Templars', 'Gladiator Reaper', 160),
  ('Black Templars', 'Gladiator Valiant', 150),
  ('Black Templars', 'High Marshal Helbrecht', 120),
  ('Black Templars', 'Impulsor', 85),
  ('Black Templars', 'Land Raider Crusader', 220),
  ('Black Templars', 'Marshal', 80),
  ('Black Templars', 'Sternguard Veteran Squad', 85),
  ('Black Templars', 'Sword Brethren', 105),
  ('Black Templars', 'Terminator Squad', 175),
  ('Black Templars', 'Repulsor', 180),
  ('Black Templars', 'Repulsor Executioner', 235),
  ('Blood Angels', 'Astorath', 85),
  ('Blood Angels', 'Baal Predator', 125),
  ('Blood Angels', 'Blood Angels Captain', 80),
  ('Blood Angels', 'Chief Librarian Mephiston', 120),
  ('Blood Angels', 'Commander Dante', 120),
  ('Blood Angels', 'Death Company Captain', 70),
  ('Blood Angels', 'Death Company Captain with Jump Pack', 75),
  ('Blood Angels', 'Death Company Dreadnought', 160),
  ('Blood Angels', 'Death Company Marines', 85),
  ('Blood Angels', 'Death Company Marines with Bolt Rifles', 85),
  ('Blood Angels', 'Death Company Marines with Jump Packs', 120),
  ('Blood Angels', 'Lemartes', 100),
  ('Blood Angels', 'Sanguinary Guard', 125),
  ('Blood Angels', 'Sanguinary Priest', 75),
  ('Blood Angels', 'The Sanguinor', 130),
  ('Chaos Daemons', 'Beasts of Nurgle', 65),
  ('Chaos Daemons', 'Hellflayers', 80),
  ('Chaos Daemons', 'Be’lakor', 375),
  ('Chaos Daemons', 'Horticulous Slimux', 120),
  ('Chaos Daemons', 'Bloodcrushers', 110),
  ('Chaos Daemons', 'Infernal Enrapturess', 60),
  ('Chaos Daemons', 'Kairos Fateweaver', 295),
  ('Chaos Daemons', 'Bloodletters', 110),
  ('Chaos Daemons', 'Karanak', 75),
  ('Chaos Daemons', 'Bloodmaster', 65),
  ('Chaos Daemons', 'Keeper of Secrets', 240),
  ('Chaos Daemons', 'Bloodthirster', 305),
  ('Chaos Daemons', 'Lord of Change', 285),
  ('Chaos Daemons', 'Blue Horrors', 125),
  ('Chaos Daemons', 'Nurglings', 40),
  ('Chaos Daemons', 'Burning Chariot', 115),
  ('Chaos Daemons', 'Changecaster', 60),
  ('Chaos Daemons', 'Pink Horrors', 140),
  ('Chaos Daemons', 'Contorted Epitome', 100),
  ('Chaos Daemons', 'Plague Drones', 110),
  ('Chaos Daemons', 'Daemon Prince of Chaos', 190),
  ('Chaos Daemons', 'Plaguebearers', 110),
  ('Chaos Daemons', 'Daemon Prince of Chaos with Wings', 180),
  ('Chaos Daemons', 'Poxbringer', 55),
  ('Chaos Daemons', 'Daemonettes', 100),
  ('Chaos Daemons', 'Rendmaster on Blood Throne', 165),
  ('Chaos Daemons', 'Epidemius', 80),
  ('Chaos Daemons', 'Rotigus', 265),
  ('Chaos Daemons', 'Exalted Flamer', 65),
  ('Chaos Daemons', 'Screamers', 80),
  ('Chaos Daemons', 'Fateskimmer', 95),
  ('Chaos Daemons', 'Seekers', 80),
  ('Chaos Daemons', 'Feculent Gnarlmaw', 100),
  ('Chaos Daemons', 'Fiends', 95),
  ('Chaos Daemons', 'Shalaxi Helbane', 340),
  ('Chaos Daemons', 'Skarbrand', 305),
  ('Chaos Daemons', 'Flamers', 65),
  ('Chaos Daemons', 'Skull Altar', 105),
  ('Chaos Daemons', 'Flesh Hounds', 75),
  ('Chaos Daemons', 'Skull Cannon', 95),
  ('Chaos Daemons', 'Fluxmaster', 60),
  ('Chaos Daemons', 'Skullmaster', 100),
  ('Chaos Daemons', 'Great Unclean One', 250),
  ('Chaos Daemons', 'Skulltaker', 85),
  ('Chaos Daemons', 'Sloppity Bilepiper', 55),
  ('Chaos Daemons', 'Soul Grinder', 180),
  ('Chaos Daemons', 'Spoilpox Scrivener', 60),
  ('Chaos Daemons', 'Syll’esske', 120),
  ('Chaos Daemons', 'The Blue Scribes', 75),
  ('Chaos Daemons', 'The Changeling', 90),
  ('Chaos Daemons', 'The Masque of Slaanesh', 95),
  ('Chaos Daemons', 'Tormentbringer', 140),
  ('Chaos Daemons', 'Tranceweaver', 60),
  ('Chaos Knights', 'Knight Abominant', 355),
  ('Chaos Knights', 'Chaos Acastus Knight Asterius', 765),
  ('Chaos Knights', 'Knight Desecrator', 355),
  ('Chaos Knights', 'Chaos Acastus Knight Porphyrion', 700),
  ('Chaos Knights', 'Knight Despoiler', 390),
  ('Chaos Knights', 'Chaos Cerastus Knight Acheron', 385),
  ('Chaos Knights', 'Knight Rampager', 365),
  ('Chaos Knights', 'Chaos Cerastus Knight Atrapos', 395),
  ('Chaos Knights', 'Knight Ruinator', 355),
  ('Chaos Knights', 'Chaos Cerastus Knight Castigator', 385),
  ('Chaos Knights', 'Knight Tyrant', 410),
  ('Chaos Knights', 'Chaos Cerastus Knight Lancer', 385),
  ('Chaos Knights', 'War Dog Brigand', 140),
  ('Chaos Knights', 'Chaos Questoris Knight Magaera', 375),
  ('Chaos Knights', 'War Dog Executioner', 130),
  ('Chaos Knights', 'Chaos Questoris Knight Styrix', 375),
  ('Chaos Knights', 'War Dog Huntsman', 140),
  ('Chaos Knights', 'War Dog Moirax', 150),
  ('Chaos Knights', 'War Dog Karnivore', 150),
  ('Chaos Knights', 'War Dog Stalker', 140),
  ('Chaos Space Marines', 'Abaddon the Despoiler', 270),
  ('Chaos Space Marines', 'Forgefiend', 170),
  ('Chaos Space Marines', 'Accursed Cultists', 90),
  ('Chaos Space Marines', 'Haarken Worldclaimer', 90),
  ('Chaos Space Marines', 'Havocs', 125),
  ('Chaos Space Marines', 'Chaos Bikers', 70),
  ('Chaos Space Marines', 'Helbrute', 130),
  ('Chaos Space Marines', 'Chaos Land Raider', 220),
  ('Chaos Space Marines', 'Heldrake', 205),
  ('Chaos Space Marines', 'Chaos Lord', 90),
  ('Chaos Space Marines', 'Heretic Astartes Daemon Prince', 165),
  ('Chaos Space Marines', 'Chaos Lord in Terminator Armour', 85),
  ('Chaos Space Marines', 'Heretic Astartes Daemon Prince with Wings', 180),
  ('Chaos Space Marines', 'Chaos Lord with Jump Pack', 80),
  ('Chaos Space Marines', 'Huron Blackheart', 120),
  ('Chaos Space Marines', 'Chaos Predator Annihilator', 135),
  ('Chaos Space Marines', 'Khorne Lord of Skulls', 450),
  ('Chaos Space Marines', 'Chaos Predator Destructor', 140),
  ('Chaos Space Marines', 'Legionaries', 90),
  ('Chaos Space Marines', 'Chaos Rhino', 75),
  ('Chaos Space Marines', 'Chaos Spawn', 70),
  ('Chaos Space Marines', 'Lord Discordant on Helstalker', 160),
  ('Chaos Space Marines', 'Chaos Terminator Squad', 180),
  ('Chaos Space Marines', 'Master of Executions', 80),
  ('Chaos Space Marines', 'Master of Possession', 60),
  ('Chaos Space Marines', 'Chaos Vindicator', 185),
  ('Chaos Space Marines', 'Masters of the Maelstrom', 115),
  ('Chaos Space Marines', 'Chosen', 125),
  ('Chaos Space Marines', 'Maulerfiend', 130),
  ('Chaos Space Marines', 'Cultist Firebrand', 45),
  ('Chaos Space Marines', 'Mutilators', 200),
  ('Chaos Space Marines', 'Cultist Mob', 50),
  ('Chaos Space Marines', 'Nemesis Claw', 110),
  ('Chaos Space Marines', 'Cypher', 90),
  ('Chaos Space Marines', 'Noctilith Crown', 125),
  ('Chaos Space Marines', 'Dark Apostle', 65),
  ('Chaos Space Marines', 'Obliterators', 160),
  ('Chaos Space Marines', 'Dark Commune', 90),
  ('Chaos Space Marines', 'Possessed', 120),
  ('Chaos Space Marines', 'Defiler', 250),
  ('Chaos Space Marines', 'Raptors', 110),
  ('Chaos Space Marines', 'Fabius Bile', 100),
  ('Chaos Space Marines', 'Fellgor Beastmen', 70),
  ('Chaos Space Marines', 'Red Corsairs Raiders', 110),
  ('Chaos Space Marines', 'Red Corsairs Reave-Captain', 75),
  ('Chaos Space Marines', 'Sorcerer', 60),
  ('Chaos Space Marines', 'Sorcerer in Terminator Armour', 80),
  ('Chaos Space Marines', 'Traitor Enforcer', 55),
  ('Chaos Space Marines', 'Traitor Guardsmen Squad', 70),
  ('Chaos Space Marines', 'Vashtorr the Arkifane', 175),
  ('Chaos Space Marines', 'Venomcrawler', 110),
  ('Chaos Space Marines', 'Warp Talons', 125),
  ('Chaos Space Marines', 'Warpsmith', 70),
  ('Chaos Space Marines', 'Warsmith Kravek Morne', 120),
  ('Dark Angels', 'Asmodai', 70),
  ('Dark Angels', 'Lazarus', 70),
  ('Dark Angels', 'Azrael', 125),
  ('Dark Angels', 'Lion El’Jonson', 315),
  ('Dark Angels', 'Belial', 85),
  ('Dark Angels', 'Nephilim Jetfighter', 195),
  ('Dark Angels', 'Deathwing Knights', 250),
  ('Dark Angels', 'Ravenwing Black Knights', 80),
  ('Dark Angels', 'Deathwing Terminator Squad', 180),
  ('Dark Angels', 'Ravenwing Command Squad', 120),
  ('Dark Angels', 'Ezekiel', 75),
  ('Dark Angels', 'Ravenwing Dark Talon', 210),
  ('Dark Angels', 'Inner Circle Companions', 90),
  ('Dark Angels', 'Ravenwing Darkshroud', 100),
  ('Dark Angels', 'Sammael', 115),
  ('Dark Angels', 'Land Speeder Vengeance', 120),
  ('Death Guard', 'Biologus Putrifier', 60),
  ('Death Guard', 'Noxious Blightbringer', 50),
  ('Death Guard', 'Blightlord Terminators', 115),
  ('Death Guard', 'Plague Marines', 95),
  ('Death Guard', 'Chaos Land Raider', 220),
  ('Death Guard', 'Plague Surgeon', 50),
  ('Death Guard', 'Chaos Predator Annihilator', 135),
  ('Death Guard', 'Plagueburst Crawler', 210),
  ('Death Guard', 'Chaos Predator Destructor', 145),
  ('Death Guard', 'Poxwalkers', 65),
  ('Death Guard', 'Chaos Rhino', 85),
  ('Death Guard', 'Tallyman', 50),
  ('Death Guard', 'Chaos Spawn of Nurgle', 80),
  ('Death Guard', 'Typhus', 100),
  ('Death Guard', 'Daemon Prince of Nurgle', 195),
  ('Death Guard', 'PLAGUE LEGIONS Daemon Prince of Nurgle with Wings', 180),
  ('Death Guard', 'Beasts of Nurgle', 65),
  ('Death Guard', 'Deathshroud Terminators', 160),
  ('Death Guard', 'Great Unclean One', 250),
  ('Death Guard', 'Defiler', 250),
  ('Death Guard', 'Nurglings', 40),
  ('Death Guard', 'Foetid Bloat-drone', 100),
  ('Death Guard', 'Plague Drones', 115),
  ('Death Guard', 'Foetid Bloat-drone with Heavy Blight Launcher', 120),
  ('Death Guard', 'Plaguebearers', 110),
  ('Death Guard', 'Foul Blightspawn', 75),
  ('Death Guard', 'Rotigus', 265),
  ('Death Guard', 'Helbrute', 115),
  ('Death Guard', 'Icon Bearer', 45),
  ('Death Guard', 'Lord of Contagion', 120),
  ('Death Guard', 'Lord of Poxes', 75),
  ('Death Guard', 'Lord of Virulence', 100),
  ('Death Guard', 'Malignant Plaguecaster', 60),
  ('Death Guard', 'Miasmic Malignifier', 105),
  ('Death Guard', 'Mortarion', 380),
  ('Death Guard', 'Myphitic Blight-haulers', 100),
  ('Deathwatch', 'Corvus Blackstar', 180),
  ('Deathwatch', 'Deathwatch Terminator Squad', 190),
  ('Deathwatch', 'Deathwatch Veterans', 100),
  ('Deathwatch', 'Decimus Kill Team', 100),
  ('Deathwatch', 'Fortis Kill Team', 180),
  ('Deathwatch', 'Indomitor Kill Team', 265),
  ('Deathwatch', 'Spectrus Kill Team', 180),
  ('Deathwatch', 'Talonstrike Kill Team', 275),
  ('Deathwatch', 'Watch Captain Artemis', 65),
  ('Deathwatch', 'Watch Master', 95),
  ('Drukhari', 'Archon', 80),
  ('Drukhari', 'Raider', 85),
  ('Drukhari', 'Cronos', 55),
  ('Drukhari', 'Ravager', 110),
  ('Drukhari', 'Razorwing Jetfighter', 170),
  ('Drukhari', 'Drazhar', 85),
  ('Drukhari', 'Reavers', 70),
  ('Drukhari', 'Haemonculus', 60),
  ('Drukhari', 'Hand of the Archon', 125),
  ('Drukhari', 'Scourges with Heavy Weapons', 130),
  ('Drukhari', 'Hellions', 85),
  ('Drukhari', 'Scourges with Shardcarbines', 75),
  ('Drukhari', 'Succubus', 50),
  ('Drukhari', 'Incubi', 90),
  ('Drukhari', 'Talos', 80),
  ('Drukhari', 'Kabalite Warriors', 115),
  ('Drukhari', 'Venom', 70),
  ('Drukhari', 'Lady Malys', 100),
  ('Drukhari', 'Voidraven Bomber', 245),
  ('Drukhari', 'Lelith Hesperax', 85),
  ('Drukhari', 'Wracks', 60),
  ('Drukhari', 'Mandrakes', 75),
  ('Drukhari', 'Wyches', 90),
  ('Emperor''s Children', 'Chaos Land Raider', 220),
  ('Emperor''s Children', 'Daemonettes', 90),
  ('Emperor''s Children', 'Chaos Rhino', 80),
  ('Emperor''s Children', 'Fiends', 95),
  ('Emperor''s Children', 'Chaos Spawn', 70),
  ('Emperor''s Children', 'Chaos Terminators', 145),
  ('Emperor''s Children', 'Keeper of Secrets', 240),
  ('Emperor''s Children', 'Daemon Prince of Slaanesh', 180),
  ('Emperor''s Children', 'Seekers', 80),
  ('Emperor''s Children', 'Daemon Prince of Slaanesh with Wings', 215),
  ('Emperor''s Children', 'Shalaxi Helbane', 340),
  ('Emperor''s Children', 'Defiler', 250),
  ('Emperor''s Children', 'Flawless Blades', 100),
  ('Emperor''s Children', 'Fulgrim', 340),
  ('Emperor''s Children', 'Heldrake', 195),
  ('Emperor''s Children', 'Infractors', 85),
  ('Emperor''s Children', 'Lord Exultant', 80),
  ('Emperor''s Children', 'Lord Kakophonist', 70),
  ('Emperor''s Children', 'Lucius the Eternal', 150),
  ('Emperor''s Children', 'Maulerfiend', 130),
  ('Emperor''s Children', 'Noise Marines', 145),
  ('Emperor''s Children', 'Sorcerer', 60),
  ('Emperor''s Children', 'Tormentors', 85),
  ('Genestealer Cults', 'Aberrants', 135),
  ('Genestealer Cults', 'Purestrain Genestealers', 75),
  ('Genestealer Cults', 'Abominant', 85),
  ('Genestealer Cults', 'Reductus Saboteur', 65),
  ('Genestealer Cults', 'Achilles Ridgerunners', 95),
  ('Genestealer Cults', 'Sanctus', 50),
  ('Genestealer Cults', 'Acolyte Hybrids with Autopistols', 65),
  ('Genestealer Cults', 'Acolyte Hybrids with Hand Flamers', 70),
  ('Genestealer Cults', 'Acolyte Iconward', 50),
  ('Genestealer Cults', 'Atalan Jackals', 85),
  ('Genestealer Cults', 'Benefictus', 70),
  ('Genestealer Cults', 'Biophagus', 50),
  ('Genestealer Cults', 'Clamavus', 50),
  ('Genestealer Cults', 'Goliath Rockgrinder', 120),
  ('Genestealer Cults', 'Goliath Truck', 85),
  ('Genestealer Cults', 'Hybrid Metamorphs', 70),
  ('Genestealer Cults', 'Jackal Alphus', 55),
  ('Genestealer Cults', 'Kelermorph', 60),
  ('Genestealer Cults', 'Locus', 45),
  ('Genestealer Cults', 'Magus', 50),
  ('Genestealer Cults', 'Neophyte Hybrids', 65),
  ('Genestealer Cults', 'Nexos', 60),
  ('Genestealer Cults', 'Patriarch', 75),
  ('Genestealer Cults', 'Primus', 70),
  ('Grey Knights', 'Brother-Captain', 90),
  ('Grey Knights', 'Stormtalon Gunship', 170),
  ('Grey Knights', 'Brotherhood Champion', 70),
  ('Grey Knights', 'Strike Squad', 120),
  ('Grey Knights', 'Brotherhood Chaplain', 65),
  ('Grey Knights', 'Venerable Dreadnought', 140),
  ('Grey Knights', 'Brotherhood Librarian', 80),
  ('Grey Knights', 'Brotherhood Techmarine', 70),
  ('Grey Knights', 'Grey Knights Thunderhawk Gunship', 805),
  ('Grey Knights', 'Brotherhood Terminator Squad', 150),
  ('Grey Knights', 'Castellan Crowe', 90),
  ('Grey Knights', 'Grand Master', 95),
  ('Grey Knights', 'Grand Master in Nemesis Dreadknight', 225),
  ('Grey Knights', 'Grand Master Voldus', 110),
  ('Grey Knights', 'Interceptor Squad', 125),
  ('Grey Knights', 'Land Raider', 220),
  ('Grey Knights', 'Land Raider Crusader', 220),
  ('Grey Knights', 'Land Raider Redeemer', 270),
  ('Grey Knights', 'Nemesis Dreadknight', 210),
  ('Grey Knights', 'Paladin Squad', 180),
  ('Grey Knights', 'Purgation Squad', 115),
  ('Grey Knights', 'Purifier Squad', 125),
  ('Grey Knights', 'Razorback', 85),
  ('Grey Knights', 'Rhino', 80),
  ('Grey Knights', 'Stormhawk Interceptor', 160),
  ('Grey Knights', 'Stormraven Gunship', 280),
  ('Imperial Agents', 'Sisters of Battle Immolator', 100),
  ('Imperial Agents', 'AGENTS OF THE IMPERIUM Sisters of Battle Squad', 100),
  ('Imperial Agents', 'Aquila Kill Team', 100),
  ('Imperial Agents', 'Subductor Squad', 85),
  ('Imperial Agents', 'Callidus Assassin', 100),
  ('Imperial Agents', 'Vigilant Squad', 85),
  ('Imperial Agents', 'Corvus Blackstar', 180),
  ('Imperial Agents', 'Vindicare Assassin', 110),
  ('Imperial Agents', 'Culexus Assassin', 85),
  ('Imperial Agents', 'Voidsmen-at-Arms', 50),
  ('Imperial Agents', 'Deathwatch Kill Team', 100),
  ('Imperial Agents', 'Watch Captain Artemis', 65),
  ('Imperial Agents', 'Eversor Assassin', 110),
  ('Imperial Agents', 'Watch Master', 95),
  ('Imperial Agents', 'Exaction Squad', 90),
  ('Imperial Agents', 'Grey Knights Terminator Squad', 190),
  ('Imperial Agents', 'Imperial Navy Breachers', 90),
  ('Imperial Agents', 'Imperial Rhino', 75),
  ('Imperial Agents', 'Inquisitor', 55),
  ('Imperial Agents', 'Inquisitor Coteaz', 75),
  ('Imperial Agents', 'Inquisitor Draxus', 75),
  ('Imperial Agents', 'Inquisitor Greyfax', 65),
  ('Imperial Agents', 'Inquisitor Kroyle', 100),
  ('Imperial Agents', 'Inquisitorial Agents', 50),
  ('Imperial Agents', 'Inquisitorial Chimera', 70),
  ('Imperial Agents', 'Ministorum Priest', 40),
  ('Imperial Agents', 'Navigator', 60),
  ('Imperial Agents', 'Rogue Trader Entourage', 75),
  ('Imperial Agents', 'Sanctifiers', 100),
  ('Imperial Agents', 'EVERY MODEL HAS IMPERIUM KEYWORD Imperial Rhino', 75),
  ('Imperial Agents', 'Sisters of Battle Squad', 115),
  ('Imperial Knights', 'Armiger Helverin', 135),
  ('Imperial Knights', 'Acastus Knight Asterius', 765),
  ('Imperial Knights', 'Armiger Warglaive', 140),
  ('Imperial Knights', 'Acastus Knight Porphyrion', 700),
  ('Imperial Knights', 'Canis Rex', 415),
  ('Imperial Knights', 'Armiger Moirax', 150),
  ('Imperial Knights', 'Knight Castellan', 410),
  ('Imperial Knights', 'Cerastus Knight Acheron', 395),
  ('Imperial Knights', 'Knight Crusader', 385),
  ('Imperial Knights', 'Cerastus Knight Atrapos', 405),
  ('Imperial Knights', 'Knight Defender', 415),
  ('Imperial Knights', 'Cerastus Knight Castigator', 395),
  ('Imperial Knights', 'Knight Destrier', 250),
  ('Imperial Knights', 'Cerastus Knight Lancer', 395),
  ('Imperial Knights', 'Knight Errant', 355),
  ('Imperial Knights', 'Questoris Knight Magaera', 385),
  ('Imperial Knights', 'Knight Gallant', 355),
  ('Imperial Knights', 'Questoris Knight Styrix', 385),
  ('Imperial Knights', 'Knight Paladin', 375),
  ('Imperial Knights', 'Knight Preceptor', 365),
  ('Imperial Knights', 'Knight Valiant', 410),
  ('Imperial Knights', 'Knight Warden', 375),
  ('Leagues of Votann', 'Arkanyst Evaluator', 65),
  ('Leagues of Votann', 'Berehk Stornbröw', 95),
  ('Leagues of Votann', 'Brôkhyr Iron-master', 75),
  ('Leagues of Votann', 'Brôkhyr Thunderkyn', 80),
  ('Leagues of Votann', 'Buri Aegnirssen', 95),
  ('Leagues of Votann', 'Cthonian Beserks', 100),
  ('Leagues of Votann', 'Cthonian Earthshakers', 110),
  ('Leagues of Votann', 'Einhyr Champion', 70),
  ('Leagues of Votann', 'Einhyr Hearthguard', 135),
  ('Leagues of Votann', 'Grimnyr', 65),
  ('Leagues of Votann', 'Hearthkyn Warriors', 100),
  ('Leagues of Votann', 'Hekaton Land Fortress', 240),
  ('Leagues of Votann', 'Hernkyn Pioneers', 80),
  ('Leagues of Votann', 'Hernkyn Yaegirs', 90),
  ('Leagues of Votann', 'Ironkin Steeljacks with Heavy Volkanite Disintegrators', 85),
  ('Leagues of Votann', 'Ironkin Steeljacks with Melee Weapons', 85),
  ('Leagues of Votann', 'Kâhl', 65),
  ('Leagues of Votann', 'Kapricus Carrier', 75),
  ('Leagues of Votann', 'Kapricus Defenders', 70),
  ('Leagues of Votann', 'Memnyr Strategist', 45),
  ('Leagues of Votann', 'Sagitaur', 90),
  ('Leagues of Votann', 'Ûthar the Destined', 95),
  ('Necrons', 'Annihilation Barge', 105),
  ('Necrons', 'Illuminor Szeras', 165),
  ('Necrons', 'C’tan Shard of the Deceiver', 310),
  ('Necrons', 'Immortals', 70),
  ('Necrons', 'C’tan Shard of the Nightbringer', 340),
  ('Necrons', 'Imotekh the Stormlord', 100),
  ('Necrons', 'C’tan Shard of the Void Dragon', 330),
  ('Necrons', 'Lokhust Destroyers', 40),
  ('Necrons', 'Canoptek Doomstalker', 140),
  ('Necrons', 'Canoptek Macrocytes', 85),
  ('Necrons', 'Lokhust Heavy Destroyers', 55),
  ('Necrons', 'Canoptek Reanimator', 75),
  ('Necrons', 'Canoptek Scarab Swarms', 40),
  ('Necrons', 'Lokhust Lord', 80),
  ('Necrons', 'Lychguard', 85),
  ('Necrons', 'Canoptek Spyders', 75),
  ('Necrons', 'Monolith', 400),
  ('Necrons', 'Canoptek Tomb Crawlers', 50),
  ('Necrons', 'Necron Warriors', 90),
  ('Necrons', 'Canoptek Wraiths', 110),
  ('Necrons', 'Nekrosor Ammentar', 185),
  ('Necrons', 'Catacomb Command Barge', 120),
  ('Necrons', 'Night Scythe', 145),
  ('Necrons', 'Chronomancer', 65),
  ('Necrons', 'Obelisk', 300),
  ('Necrons', 'Convergence of Dominion', 60),
  ('Necrons', 'Ophydian Destroyers', 80),
  ('Necrons', 'Cryptothralls', 60),
  ('Necrons', 'Orikan the Diviner', 80),
  ('Necrons', 'Deathmarks', 60),
  ('Necrons', 'Overlord', 85),
  ('Necrons', 'Doom Scythe', 230),
  ('Necrons', 'Overlord with Translocation Shroud', 85),
  ('Necrons', 'Doomsday Ark', 200),
  ('Necrons', 'Plasmancer', 55),
  ('Necrons', 'Flayed Ones', 60),
  ('Necrons', 'Psychomancer', 55),
  ('Necrons', 'Royal Warden', 50),
  ('Necrons', 'Geomancer', 75),
  ('Necrons', 'Skorpekh Destroyers', 90),
  ('Necrons', 'Ghost Ark', 115),
  ('Necrons', 'Hexmark Destroyer', 75),
  ('Necrons', 'Skorpekh Lord', 90),
  ('Necrons', 'Technomancer', 80),
  ('Necrons', 'Tesseract Vault', 425),
  ('Necrons', 'The Silent King', 400),
  ('Necrons', 'Tomb Blades', 75),
  ('Necrons', 'Transcendent C’tan', 325),
  ('Necrons', 'Trazyn the Infinite', 75),
  ('Necrons', 'Triarch Praetorians', 90),
  ('Necrons', 'Triarch Stalker', 110),
  ('Necrons', 'Seraptek Heavy Construct', 540),
  ('Orks', 'Battlewagon', 160),
  ('Orks', 'Hunta Rig', 135),
  ('Orks', 'Beast Snagga Boyz', 95),
  ('Orks', 'Kill Rig', 155),
  ('Orks', 'Killa Kans', 125),
  ('Orks', 'Beastboss', 80),
  ('Orks', 'Beastboss on Squigosaur', 110),
  ('Orks', 'Kommandos', 120),
  ('Orks', 'Big Mek', 70),
  ('Orks', 'Kustom Boosta-blasta', 70),
  ('Orks', 'Big Mek in Mega Armour', 90),
  ('Orks', 'Big Mek with Shokk Attack Gun', 80),
  ('Orks', 'Meganobz', 65),
  ('Orks', 'Big’ed Bossbunka', 135),
  ('Orks', 'Blitza-bommer', 115),
  ('Orks', 'Megatrakk Scrapjet', 75),
  ('Orks', 'Boomdakka Snazzwagon', 70),
  ('Orks', 'Mek', 45),
  ('Orks', 'Boss Snikrot', 75),
  ('Orks', 'Mek Gunz', 50),
  ('Orks', 'Boyz', 80),
  ('Orks', 'Morkanaut', 280),
  ('Orks', 'Breaka Boyz', 140),
  ('Orks', 'Mozrog Skragbad', 145),
  ('Orks', 'Nobz', 105),
  ('Orks', 'Burna-bommer', 125),
  ('Orks', 'Painboss', 70),
  ('Orks', 'Dakkajet', 135),
  ('Orks', 'Painboy', 80),
  ('Orks', 'Deff Dread', 120),
  ('Orks', 'Rukkatrukk Squigbuggy', 95),
  ('Orks', 'Deffkilla Wartrike', 80),
  ('Orks', 'Shokkjump Dragsta', 70),
  ('Orks', 'Deffkoptas', 80),
  ('Orks', 'Squighog Boyz', 150),
  ('Orks', 'Flash Gitz', 80),
  ('Orks', 'Stompa', 800),
  ('Orks', 'Ghazghkull Thraka', 235),
  ('Orks', 'Stormboyz', 65),
  ('Orks', 'Gorkanaut', 265),
  ('Orks', 'Tankbustas', 140),
  ('Orks', 'Gretchin', 40),
  ('Orks', 'Trukk', 70),
  ('Orks', 'Warbikers', 65),
  ('Orks', 'Warboss', 75),
  ('Orks', 'Warboss in Mega Armour', 80),
  ('Orks', 'Wazbom Blastajet', 175),
  ('Orks', 'Wazdakka Gutsmek', 175),
  ('Orks', 'Weirdboy', 65),
  ('Orks', 'Wurrboy', 60),
  ('Orks', 'Zodgrod Wortsnagga', 90),
  ('Orks', 'Gargantuan Squiggoth', 440),
  ('Space Marines', 'Adrax Agatone', 85),
  ('Space Marines', 'Chaplain', 60),
  ('Space Marines', 'Aethon Shaan', 110),
  ('Space Marines', 'Chaplain in Terminator Armour', 75),
  ('Space Marines', 'Aggressor Squad', 95),
  ('Space Marines', 'Chaplain on Bike', 75),
  ('Space Marines', 'Chaplain with Jump Pack', 75),
  ('Space Marines', 'Ancient', 50),
  ('Space Marines', 'Chief Librarian Tigurius', 75),
  ('Space Marines', 'Ancient in Terminator Armour', 75),
  ('Space Marines', 'Company Heroes', 105),
  ('Space Marines', 'Apothecary', 50),
  ('Space Marines', 'Darnath Lysander', 100),
  ('Space Marines', 'Apothecary Biologis', 70),
  ('Space Marines', 'Desolation Squad', 200),
  ('Space Marines', 'Assault Intercessor Squad', 75),
  ('Space Marines', 'Devastator Squad', 120),
  ('Space Marines', 'Assault Intercessors with Jump Packs', 90),
  ('Space Marines', 'Dreadnought', 135),
  ('Space Marines', 'Ballistus Dreadnought', 150),
  ('Space Marines', 'Drop Pod', 70),
  ('Space Marines', 'Bladeguard Ancient', 45),
  ('Space Marines', 'Eliminator Squad', 85),
  ('Space Marines', 'Bladeguard Veteran Squad', 80),
  ('Space Marines', 'Eradicator Squad', 90),
  ('Space Marines', 'Brutalis Dreadnought', 160),
  ('Space Marines', 'Firestrike Servo-turrets', 75),
  ('Space Marines', 'Caanok Var', 100),
  ('Space Marines', 'Gladiator Lancer', 160),
  ('Space Marines', 'Captain', 80),
  ('Space Marines', 'Gladiator Reaper', 160),
  ('Space Marines', 'Captain in Gravis Armour', 80),
  ('Space Marines', 'Gladiator Valiant', 150),
  ('Space Marines', 'Captain in Phobos Armour', 70),
  ('Space Marines', 'Hammerfall Bunker', 175),
  ('Space Marines', 'Captain in Terminator Armour', 95),
  ('Space Marines', 'Heavy Intercessor Squad', 100),
  ('Space Marines', 'Captain Titus', 90),
  ('Space Marines', 'Captain with Jump Pack', 75),
  ('Space Marines', 'Hellblaster Squad', 110),
  ('Space Marines', 'Cato Sicarius', 95),
  ('Space Marines', 'Impulsor', 80),
  ('Space Marines', 'Centurion Assault Squad', 150),
  ('Space Marines', 'Inceptor Squad', 120),
  ('Space Marines', 'Centurion Devastator Squad', 175),
  ('Space Marines', 'Incursor Squad', 80),
  ('Space Marines', 'Infernus Squad', 90),
  ('Space Marines', 'Infiltrator Squad', 100),
  ('Space Marines', 'Intercessor Squad', 80),
  ('Space Marines', 'Invader ATV', 60),
  ('Space Marines', 'Invictor Tactical Warsuit', 125),
  ('Space Marines', 'Iron Father Feirros', 95),
  ('Space Marines', 'Judiciar', 70),
  ('Space Marines', 'Kayvaan Shrike', 100),
  ('Space Marines', 'Kor’sarro Khan', 60),
  ('Space Marines', 'Land Raider', 220),
  ('Space Marines', 'Land Raider Crusader', 220),
  ('Space Marines', 'Land Raider Redeemer', 270),
  ('Space Marines', 'Librarian', 65),
  ('Space Marines', 'Librarian in Phobos Armour', 70),
  ('Space Marines', 'Librarian in Terminator Armour', 75),
  ('Space Marines', 'Lieutenant', 55),
  ('Space Marines', 'Lieutenant in Phobos Armour', 55),
  ('Space Marines', 'Lieutenant in Reiver Armour', 55),
  ('Space Marines', 'Lieutenant with Combi-weapon', 85),
  ('Space Marines', 'Marneus Calgar in Armour of Antilochus', 140),
  ('Space Marines', 'Outrider Squad', 80),
  ('Space Marines', 'Pedro Kantor', 90),
  ('Space Marines', 'Predator Annihilator', 135),
  ('Space Marines', 'Vanguard Veteran Squad with Jump Packs', 100),
  ('Space Marines', 'Predator Destructor', 140),
  ('Space Marines', 'Victrix Honour Guard', 110),
  ('Space Marines', 'Razorback', 95),
  ('Space Marines', 'Vindicator', 185),
  ('Space Marines', 'Redemptor Dreadnought', 205),
  ('Space Marines', 'Vulkan He’stan', 100),
  ('Space Marines', 'Reiver Squad', 80),
  ('Space Marines', 'Wardens of Ultramar', 105),
  ('Space Marines', 'Repulsor', 180),
  ('Space Marines', 'Whirlwind', 190),
  ('Space Marines', 'Repulsor Executioner', 230),
  ('Space Marines', 'Rhino', 75),
  ('Space Marines', 'Astraeus', 525),
  ('Space Marines', 'Roboute Guilliman', 340),
  ('Space Marines', 'Thunderhawk Gunship', 840),
  ('Space Marines', 'Scout Squad', 70),
  ('Space Marines', 'Sternguard Veteran Squad', 100),
  ('Space Marines', 'Storm Speeder Hailstrike', 115),
  ('Space Marines', 'Storm Speeder Hammerstrike', 125),
  ('Space Marines', 'Storm Speeder Thunderstrike', 135),
  ('Space Marines', 'Stormhawk Interceptor', 155),
  ('Space Marines', 'Stormraven Gunship', 280),
  ('Space Marines', 'Stormtalon Gunship', 165),
  ('Space Marines', 'Suboden Khan', 115),
  ('Space Marines', 'Suppressor Squad', 75),
  ('Space Marines', 'Tactical Squad', 140),
  ('Space Marines', 'Techmarine', 55),
  ('Space Marines', 'Terminator Assault Squad', 180),
  ('Space Marines', 'Terminator Squad', 170),
  ('Space Marines', 'Tor Garadon', 90),
  ('Space Marines', 'Uriel Ventris', 95),
  ('Space Wolves', 'Arjac Rockfist', 105),
  ('Space Wolves', 'Bjorn the Fell-Handed', 160),
  ('Space Wolves', 'Blood Claws', 135),
  ('Space Wolves', 'Wolf Guard Terminators', 170),
  ('Space Wolves', 'Fenrisian Wolves', 40),
  ('Space Wolves', 'Wolf Priest', 70),
  ('Space Wolves', 'Grey Hunters', 165),
  ('Space Wolves', 'Wolf Scouts', 105),
  ('Space Wolves', 'Iron Priest', 55),
  ('Space Wolves', 'Wulfen', 85),
  ('Space Wolves', 'Logan Grimnar', 110),
  ('Space Wolves', 'Murderfang', 150),
  ('Space Wolves', 'Wulfen Dreadnought', 135),
  ('Space Wolves', 'Njal Stormcaller', 85),
  ('Space Wolves', 'Wulfen with Storm Shields', 100),
  ('Space Wolves', 'Ragnar Blackmane', 100),
  ('Space Wolves', 'Thunderwolf Cavalry', 115),
  ('Space Wolves', 'Ulrik the Slayer', 70),
  ('Space Wolves', 'Venerable Dreadnought', 130),
  ('Space Wolves', 'Wolf Guard Battle Leader', 65),
  ('T''au Empire', 'Breacher Team', 90),
  ('T''au Empire', 'Krootox Rampagers', 85),
  ('T''au Empire', 'Broadside Battlesuits', 80),
  ('T''au Empire', 'Krootox Riders', 40),
  ('T''au Empire', 'Cadre Fireblade', 50),
  ('T''au Empire', 'Pathfinder Team', 90),
  ('T''au Empire', 'Commander Farsight', 85),
  ('T''au Empire', 'Piranhas', 60),
  ('T''au Empire', 'Commander in Coldstar Battlesuit', 95),
  ('T''au Empire', 'Commander in Enforcer Battlesuit', 80),
  ('T''au Empire', 'Razorshark Strike Fighter', 170),
  ('T''au Empire', 'Commander Shadowsun', 100),
  ('T''au Empire', 'Riptide Battlesuit', 200),
  ('T''au Empire', 'Crisis Fireknife Battlesuits', 120),
  ('T''au Empire', 'Sky Ray Gunship', 150),
  ('T''au Empire', 'Crisis Starscythe Battlesuits', 110),
  ('T''au Empire', 'Stealth Battlesuits', 100),
  ('T''au Empire', 'Crisis Sunforge Battlesuits', 140),
  ('T''au Empire', 'Stormsurge', 360),
  ('T''au Empire', 'Darkstrider', 60),
  ('T''au Empire', 'Strike Team', 70),
  ('T''au Empire', 'Devilfish', 85),
  ('T''au Empire', 'Sun Shark Bomber', 160),
  ('T''au Empire', 'Ethereal', 50),
  ('T''au Empire', 'The Twin Lance', 185),
  ('T''au Empire', 'Firesight Team', 60),
  ('T''au Empire', 'Tidewall Droneport', 85),
  ('T''au Empire', 'Ghostkeel Battlesuit', 160),
  ('T''au Empire', 'Tidewall Gunrig', 90),
  ('T''au Empire', 'Hammerhead Gunship', 145),
  ('T''au Empire', 'Tidewall Shieldline', 85),
  ('T''au Empire', 'Kroot Carnivores', 65),
  ('T''au Empire', 'Vespid Stingwings', 65),
  ('T''au Empire', 'Kroot Farstalkers', 85),
  ('T''au Empire', 'Kroot Flesh Shaper', 45),
  ('T''au Empire', 'AX-1-0 Tiger Shark', 315),
  ('T''au Empire', 'Kroot Hounds', 40),
  ('T''au Empire', 'Manta', 2100),
  ('T''au Empire', 'Kroot Lone-spear', 80),
  ('T''au Empire', 'Ta’unar Supremacy Armour', 790),
  ('T''au Empire', 'Kroot Trail Shaper', 55),
  ('T''au Empire', 'Tiger Shark', 325),
  ('T''au Empire', 'Kroot War Shaper', 50),
  ('Thousand Sons', 'Ahriman', 100),
  ('Thousand Sons', 'Tzaangor Enlightened', 45),
  ('Thousand Sons', 'Chaos Land Raider', 220),
  ('Thousand Sons', 'Tzaangor Enlightened with Fatecaster Greatbows', 55),
  ('Thousand Sons', 'Chaos Predator Annihilator', 130),
  ('Thousand Sons', 'Chaos Predator Destructor', 130),
  ('Thousand Sons', 'Tzaangor Shaman', 60),
  ('Thousand Sons', 'Chaos Rhino', 90),
  ('Thousand Sons', 'Tzaangors', 70),
  ('Thousand Sons', 'Chaos Spawn', 65),
  ('Thousand Sons', 'SCINTILLATING LEGIONS Chaos Vindicator', 185),
  ('Thousand Sons', 'Blue Horrors', 90),
  ('Thousand Sons', 'Daemon Prince of Tzeentch', 180),
  ('Thousand Sons', 'Flamers', 65),
  ('Thousand Sons', 'Daemon Prince of Tzeentch with Wings', 170),
  ('Thousand Sons', 'Kairos Fateweaver', 295),
  ('Thousand Sons', 'Defiler', 250),
  ('Thousand Sons', 'Lord of Change', 285),
  ('Thousand Sons', 'Exalted Sorcerer', 80),
  ('Thousand Sons', 'Pink Horrors', 115),
  ('Thousand Sons', 'Exalted Sorcerer on Disc of Tzeentch', 100),
  ('Thousand Sons', 'Screamers', 80),
  ('Thousand Sons', 'Forgefiend', 130),
  ('Thousand Sons', 'Heldrake', 215),
  ('Thousand Sons', 'Helbrute', 110),
  ('Thousand Sons', 'Infernal Master', 95),
  ('Thousand Sons', 'Magnus the Red', 435),
  ('Thousand Sons', 'Maulerfiend', 120),
  ('Thousand Sons', 'Mutalith Vortex Beast', 170),
  ('Thousand Sons', 'Rubric Marines', 100),
  ('Thousand Sons', 'Scarab Occult Terminators', 180),
  ('Thousand Sons', 'Sekhetar Robots', 80),
  ('Thousand Sons', 'Sorcerer', 80),
  ('Thousand Sons', 'Sorcerer in Terminator Armour', 85),
  ('Tyranids', 'Barbgaunts', 55),
  ('Tyranids', 'Neurotyrant', 105),
  ('Tyranids', 'Norn Assimilator', 275),
  ('Tyranids', 'Biovores', 50),
  ('Tyranids', 'Norn Emissary', 260),
  ('Tyranids', 'Old One Eye', 150),
  ('Tyranids', 'Broodlord', 80),
  ('Tyranids', 'Parasite of Mortrex', 80),
  ('Tyranids', 'Carnifexes', 90),
  ('Tyranids', 'Psychophage', 110),
  ('Tyranids', 'Deathleaper', 80),
  ('Tyranids', 'Pyrovores', 40),
  ('Tyranids', 'Exocrine', 140),
  ('Tyranids', 'Gargoyles', 85),
  ('Tyranids', 'Raveners', 125),
  ('Tyranids', 'Ripper Swarms', 25),
  ('Tyranids', 'Genestealers', 75),
  ('Tyranids', 'Harpy', 215),
  ('Tyranids', 'Screamer-Killer', 125),
  ('Tyranids', 'Haruspex', 125),
  ('Tyranids', 'Spore MInes', 55),
  ('Tyranids', 'Hive Crone', 200),
  ('Tyranids', 'Sporocyst', 145),
  ('Tyranids', 'Hive Guard', 90),
  ('Tyranids', 'Termagants', 60),
  ('Tyranids', 'Hive Tyrant', 195),
  ('Tyranids', 'Tervigon', 160),
  ('Tyranids', 'Hormagaunts', 65),
  ('Tyranids', 'The Red Terror', 130),
  ('Tyranids', 'Hyperadapted Raveners', 165),
  ('Tyranids', 'The Swarmlord', 220),
  ('Tyranids', 'Lictor', 60),
  ('Tyranids', 'Toxicrene', 150),
  ('Tyranids', 'Maleceptor', 170),
  ('Tyranids', 'Trygon', 140),
  ('Tyranids', 'Mawloc', 135),
  ('Tyranids', 'Tyranid Prime with Lash Whip', 65),
  ('Tyranids', 'Mucolid Spores', 30),
  ('Tyranids', 'Tyranid Warriors with Melee Bio-weapons', 75),
  ('Tyranids', 'Neurogaunts', 45),
  ('Tyranids', 'Tyranid Warriors with Ranged Bio-weapons', 65),
  ('Tyranids', 'Neurolictor', 70),
  ('Tyranids', 'Tyrannocyte', 105),
  ('Tyranids', 'Tyrannofex', 200),
  ('Tyranids', 'Tyrant Guard', 80),
  ('Tyranids', 'Venomthropes', 70),
  ('Tyranids', 'Von Ryan’s Leapers', 70),
  ('Tyranids', 'Winged Hive Tyrant', 170),
  ('Tyranids', 'Winged Tyranid Prime', 65),
  ('Tyranids', 'Zoanthropes', 100),
  ('Tyranids', 'Harridan', 610),
  ('Tyranids', 'Hierophant', 810),
  ('World Eaters', 'Angron', 340),
  ('World Eaters', 'Maulerfiend', 150),
  ('World Eaters', 'Chaos Land Raider', 220),
  ('World Eaters', 'Slaughterbound', 100),
  ('World Eaters', 'Chaos Predator Annihilator', 145),
  ('World Eaters', 'BLOOD LEGIONS Bloodcrushers', 110),
  ('World Eaters', 'Chaos Predator Destructor', 145),
  ('World Eaters', 'Chaos Rhino', 85),
  ('World Eaters', 'Bloodletters', 90),
  ('World Eaters', 'Chaos Spawn', 90),
  ('World Eaters', 'Bloodthirster', 305),
  ('World Eaters', 'Chaos Terminators', 175),
  ('World Eaters', 'Flesh Hounds', 75),
  ('World Eaters', 'Daemon Prince of Khorne', 200),
  ('World Eaters', 'Skarbrand', 305),
  ('World Eaters', 'Daemon Prince of Khorne with Wings', 180),
  ('World Eaters', 'Defiler', 250),
  ('World Eaters', 'Eightbound', 135),
  ('World Eaters', 'Exalted Eightbound', 140),
  ('World Eaters', 'Forgefiend', 165),
  ('World Eaters', 'Goremongers', 75),
  ('World Eaters', 'Helbrute', 120),
  ('World Eaters', 'Heldrake', 200),
  ('World Eaters', 'Jakhals', 65),
  ('World Eaters', 'Khârn the Betrayer', 100),
  ('World Eaters', 'Khorne Berzerkers', 180),
  ('World Eaters', 'Khorne Lord of Skulls', 505),
  ('World Eaters', 'Lord Invocatus', 110),
  ('World Eaters', 'Lord on Juggernaut', 105),
  ('World Eaters', 'Master of Executions', 60),
  ('Adepta Sororitas', 'Battle Sanctum', 170),
  ('Adepta Sororitas', 'Celestian Sacresant Aveline', 45),
  ('Adepta Sororitas', 'Crusaders', 40),
  ('Adepta Sororitas', 'Death Cult Assassins', 55),
  ('Adepta Sororitas', 'Repressor', 130),
  ('Adeptus Mechanicus', 'Secutarii Hoplites', 65),
  ('Adeptus Mechanicus', 'Secutarii Peltasts', 50),
  ('Adeptus Mechanicus', 'Servitors', 50),
  ('Adeptus Mechanicus', 'Terrax-pattern Termite', 200),
  ('Adeptus Mechanicus', 'X-101', 40),
  ('Aeldari', 'Amallyn Shadowguide', 75),
  ('Aeldari', 'Vampire Raider', 430),
  ('Aeldari', 'Autarch Skyrunner', 90),
  ('Aeldari', 'Warp Hunter', 145),
  ('Aeldari', 'Bonesinger', 45),
  ('Aeldari', 'Wasp Assault Walkers', 95),
  ('Aeldari', 'Cobra', 415),
  ('Aeldari', 'Webway Gate', 105),
  ('Aeldari', 'Corsair Cloud Dancer Band', 105),
  ('Aeldari', 'Wraithseer', 160),
  ('Aeldari', 'Corsair Reaver Band', 125),
  ('Aeldari', 'Corsair Skyreaver Band', 125),
  ('Aeldari', 'Firestorm', 115),
  ('Aeldari', 'Hornet', 100),
  ('Aeldari', 'Illic Nightspear', 70),
  ('Aeldari', 'Irillyth', 105),
  ('Aeldari', 'Karandras', 90),
  ('Aeldari', 'Lynx', 180),
  ('Aeldari', 'Nightwing', 150),
  ('Aeldari', 'Phoenix', 175),
  ('Aeldari', 'Scorpion', 410),
  ('Aeldari', 'Skathach Wraithknight', 490),
  ('Aeldari', 'Vampire Hunter', 460),
  ('Astra Militarum', 'Aquila Lander', 120),
  ('Astra Militarum', 'Macharius Omega', 310),
  ('Astra Militarum', 'Arkurian Stormhammer', 480),
  ('Astra Militarum', 'Macharius Vanquisher', 285),
  ('Astra Militarum', 'Armageddon-pattern Medusa', 105),
  ('Astra Militarum', 'Macharius Vulcan', 310),
  ('Astra Militarum', 'Arvus Lighter', 95),
  ('Astra Militarum', 'Malcador', 250),
  ('Astra Militarum', 'Atlas Recovery Vehicle', 80),
  ('Astra Militarum', 'Malcador Annihilator', 270),
  ('Astra Militarum', 'Carnadon', 160),
  ('Astra Militarum', 'Malcador Defender', 310),
  ('Astra Militarum', 'Centaur Light Carrier', 40),
  ('Astra Militarum', 'Malcador Infernus', 235),
  ('Astra Militarum', 'Colossus', 160),
  ('Astra Militarum', 'Manticore Platform', 95),
  ('Astra Militarum', 'Crassus', 180),
  ('Astra Militarum', 'Marauder Bomber', 345),
  ('Astra Militarum', 'Death Korps Grenadier Squad', 110),
  ('Astra Militarum', 'Marauder Destroyer', 375),
  ('Astra Militarum', 'Death Rider Commissar', 35),
  ('Astra Militarum', 'Medusa Carriage Battery', 125),
  ('Astra Militarum', 'Dominus Armoured Siege Bombard', 325),
  ('Astra Militarum', 'Minotaur', 225),
  ('Astra Militarum', 'Earthshaker Carriage Battery', 120),
  ('Astra Militarum', 'Mukaali Riders', 110),
  ('Astra Militarum', 'Earthshaker Platform', 110),
  ('Astra Militarum', 'Munitorum Servitors', 35),
  ('Astra Militarum', 'Elysian Drop Sentinel', 85),
  ('Astra Militarum', 'Praetor', 275),
  ('Astra Militarum', 'Elysian Sniper Squad', 65),
  ('Astra Militarum', 'Provisionally Prepared', 40),
  ('Astra Militarum', 'Gorgon Heavy Transport', 275),
  ('Astra Militarum', 'Quartermaster Cadre Squad', 45),
  ('Astra Militarum', 'Griffon Mortar Carrier', 115),
  ('Astra Militarum', 'Rapier Laser Destroyer Battery', 35),
  ('Astra Militarum', 'Hades Breaching Drill', 110),
  ('Astra Militarum', 'Regimental Attachés', 40),
  ('Astra Militarum', 'Heavy Mortar Team', 50),
  ('Astra Militarum', 'Rein and Raus', 50),
  ('Astra Militarum', 'Heavy Quad Launcher Team', 50),
  ('Astra Militarum', 'Sabre Weapons Battery', 45),
  ('Astra Militarum', 'Hydra Platform', 95),
  ('Astra Militarum', '‘Iron Hand’ Straken', 55),
  ('Astra Militarum', 'Salamander Command Vehicle', 80),
  ('Astra Militarum', 'Macharius', 310),
  ('Astra Militarum', 'Salamander Scout Vehicle', 95),
  ('Astra Militarum', 'Sentinel Powerlifter', 55),
  ('Astra Militarum', 'Sergeant Harker', 40),
  ('Astra Militarum', 'Stormblade', 415),
  ('Astra Militarum', 'Storm Chimera', 90),
  ('Astra Militarum', 'Stygies Destroyer Tank Hunter', 180),
  ('Astra Militarum', 'Tarantula Battery', 40),
  ('Astra Militarum', 'Tauros Assault Vehicle', 50),
  ('Astra Militarum', 'Tauros Venator', 50),
  ('Astra Militarum', 'Trojan Support Vehicle', 80),
  ('Astra Militarum', 'Valdor', 285),
  ('Astra Militarum', 'Valkyrie Sky Talon', 185),
  ('Astra Militarum', 'Vendetta Gunship', 255),
  ('Astra Militarum', 'Voss-pattern Lightning', 130),
  ('Astra Militarum', 'Vulture Gunship', 225),
  ('Chaos Daemons', 'Aetaos’rau’keres', 315),
  ('Chaos Daemons', 'An’ggrath the Unbound', 415),
  ('Chaos Daemons', 'Exalted Seeker Chariot', 115),
  ('Chaos Daemons', 'Furies', 40),
  ('Chaos Daemons', 'Giant Chaos Spawn', 130),
  ('Chaos Daemons', 'Hellflayer', 105),
  ('Chaos Daemons', 'Herald of Slaanesh on Steed of Slaanesh', 70),
  ('Chaos Daemons', 'Plague Toads', 120),
  ('Chaos Daemons', 'Pox Riders', 160),
  ('Chaos Daemons', 'Scabeiathrax the Bloated', 275),
  ('Chaos Daemons', 'Seeker Chariot', 65),
  ('Chaos Daemons', 'Spined Chaos Beast', 145),
  ('Chaos Daemons', 'Tormentbringer on Exalted Seeker Chariot', 140),
  ('Chaos Daemons', 'Zarakynel', 320),
  ('Chaos Space Marines', 'Blood Slaughterer', 160),
  ('Chaos Space Marines', 'Renegade Ogryn Beast Handler', 40),
  ('Chaos Space Marines', 'Chaos Deimos Predator', 115),
  ('Chaos Space Marines', 'Renegade Ogryn Brutes', 95),
  ('Chaos Space Marines', 'Chaos Lord on Bike', 95),
  ('Chaos Space Marines', 'Renegade Plague Ogryns', 95),
  ('Chaos Space Marines', 'Chaos Lord on Disc of Tzeentch', 100),
  ('Chaos Space Marines', 'Rogue Psyker', 60),
  ('Chaos Space Marines', 'Chaos Lord on Juggernaut', 115),
  ('Chaos Space Marines', 'Sorcerer on Bike', 75),
  ('Chaos Space Marines', 'Chaos Lord on Palanquin of Nurgle', 90),
  ('Chaos Space Marines', 'Sorcerer on Disc of Tzeentch', 80),
  ('Chaos Space Marines', 'Chaos Lord on Steed of Slaanesh', 100),
  ('Chaos Space Marines', 'Sorcerer on Palanquin of Nurgle', 80),
  ('Chaos Space Marines', 'Chaos Thunderhawk', 840),
  ('Chaos Space Marines', 'Sorcerer on Steed of Slaanesh', 85),
  ('Chaos Space Marines', 'Cultist Mob with Firearms', 50),
  ('Chaos Space Marines', 'Decimator', 165),
  ('Chaos Space Marines', 'Dreadclaw Drop Pod', 115),
  ('Chaos Space Marines', 'Exalted Champion', 70),
  ('Chaos Space Marines', 'Gellerpox Infected', 125),
  ('Chaos Space Marines', 'Greater Blight Drone', 150),
  ('Chaos Space Marines', 'Greater Brass Scorpion', 500),
  ('Chaos Space Marines', 'Hell Blade', 115),
  ('Chaos Space Marines', 'Hell Talon', 140),
  ('Chaos Space Marines', 'Kharybdis Assault Claw', 300),
  ('Chaos Space Marines', 'Kytan Ravager', 400),
  ('Chaos Space Marines', 'Mutoid Vermin', 85),
  ('Chaos Space Marines', 'Negavolt Cultists', 55),
  ('Chaos Space Marines', 'Renegade Enforcer', 65),
  ('Chaos Space Marines', 'Renegade Heavy Weapons Squad', 75),
  ('Death Guard', 'Death Guard Chaos Lord', 65),
  ('Death Guard', 'Death Guard Chaos Lord in Terminator Armour', 85),
  ('Death Guard', 'Death Guard Cultists', 50),
  ('Death Guard', 'Death Guard Possessed', 155),
  ('Death Guard', 'Death Guard Sorcerer in Terminator Armour', 70),
  ('Drukhari', 'Beastmaster', 135),
  ('Drukhari', 'Court of the Archon', 95),
  ('Drukhari', 'Grotesques', 80),
  ('Drukhari', 'Raven Strike Fighter', 170),
  ('Drukhari', 'Reaper', 115),
  ('Drukhari', 'Tantalus', 230),
  ('Drukhari', 'Urien Rakarth', 80),
  ('Genestealer Cults', 'Tectonic Fragdrill', 125),
  ('Grey Knights', 'Brother-Captain Stern', 90),
  ('Grey Knights', 'Grey Knights Dreadnought', 160),
  ('Grey Knights', 'Grey Knights Relic Razorback', 95),
  ('Grey Knights', 'Kaldor Draigo', 125),
  ('Imperial Agents', 'Damned Legionnaires', 90),
  ('Imperial Agents', 'Daemonhost', 40),
  ('Imperial Agents', 'Deathwatch Terminator Squad', 210),
  ('Imperial Agents', 'Fortis Kill Team', 100),
  ('Imperial Agents', 'Indomitor Kill Team', 120),
  ('Imperial Agents', 'Inquisitor Eisenhorn', 65),
  ('Imperial Agents', 'Inquisitor in Terminator Armour', 70),
  ('Imperial Agents', 'Inquisitor Karamazov', 140),
  ('Imperial Agents', 'Inquisitor Ostromandeus', 65),
  ('Imperial Agents', 'Janus Draik', 40),
  ('Imperial Agents', 'Jokaero Weaponsmith', 30),
  ('Imperial Agents', 'Kill Team Cassius', 220),
  ('Imperial Agents', 'Neyam Shai Murad', 40),
  ('Imperial Agents', 'Proteus Kill Team', 160),
  ('Imperial Agents', 'Spectrus Kill Team', 90),
  ('Imperial Agents', 'UR-025', 55),
  ('Imperial Agents', 'Veteran Bike Squad', 70),
  ('Necrons', 'Anrakyr the Traveller', 95),
  ('Necrons', 'Canoptek Acanthrites', 85),
  ('Necrons', 'Canoptek Tomb Sentinel', 115),
  ('Necrons', 'Canoptek Tomb Stalker', 130),
  ('Necrons', 'Gauss Pylon', 210),
  ('Necrons', 'Lord', 65),
  ('Necrons', 'Nemesor Zahndrekh', 85),
  ('Necrons', 'Night Shroud', 140),
  ('Necrons', 'Sentry Pylons', 120),
  ('Necrons', 'Tesseract Ark', 130),
  ('Necrons', 'Vargard Obyron', 85),
  ('Orks', 'Attack Fighta', 100),
  ('Orks', 'Nob with Waaagh! Banner', 70),
  ('Orks', 'Big Gunz', 20),
  ('Orks', 'Nobz on Warbikes', 125),
  ('Orks', 'Painboy on Warbike', 85),
  ('Orks', 'Big Mek on Warbike', 105),
  ('Orks', 'Skorchas', 45),
  ('Orks', 'Big Mek with Kustom Force Field', 55),
  ('Orks', 'Big Trakk', 90),
  ('Orks', 'Squiggoth', 150),
  ('Orks', 'Boss Zagstruk', 90),
  ('Orks', 'Ufthak Blackhawk', 70),
  ('Orks', 'Chinork Warkopta', 105),
  ('Orks', 'Warboss on Warbike', 75),
  ('Orks', 'Da Red Gobbo', 40),
  ('Orks', 'Warbuggies', 40),
  ('Orks', 'Deff Rolla Battle Fortress', 250),
  ('Orks', 'Wartrakks', 50),
  ('Orks', 'Deffkoptas with Big Shootas', 130),
  ('Orks', 'Fighta-Bommer', 100),
  ('Orks', 'Grot Bomm Launcha', 50),
  ('Orks', 'Grot Mega-tank', 110),
  ('Orks', 'Grot Tanks', 155),
  ('Orks', 'Kannonwagon', 115),
  ('Orks', 'Kaptin Badrukk', 80),
  ('Orks', 'Kill Krusha', 230),
  ('Orks', 'Kill Tank', 295),
  ('Orks', 'Lifta Wagon', 135),
  ('Orks', 'Mad Dok Grotsnik', 65),
  ('Orks', 'Mega Dread', 225),
  ('Orks', 'Meka-dread', 210),
  ('Orks', 'Mekboy Workshop', 80),
  ('Space Marines', 'Ancient on Bike', 90),
  ('Space Marines', 'Fellblade', 480),
  ('Space Marines', 'Apothecary on Bike', 65),
  ('Space Marines', 'Fire Raptor Gunship', 290),
  ('Space Marines', 'Assault Squad', 95),
  ('Space Marines', 'Hunter', 100),
  ('Space Marines', 'Imperial Space Marine', 40),
  ('Space Marines', 'Assault Squad with Jump Packs', 115),
  ('Space Marines', 'Ironclad Dreadnought', 150),
  ('Space Marines', 'Astartes Servitors', 55),
  ('Space Marines', 'Javelin Attack Speeder', 110),
  ('Space Marines', 'Attack Bike Squad', 55),
  ('Space Marines', 'Kratos', 240),
  ('Space Marines', 'Land Raider Achilles', 230),
  ('Space Marines', 'Bike Squad', 80),
  ('Space Marines', 'Land Raider Excelsior', 250),
  ('Space Marines', 'Land Raider Helios', 220),
  ('Space Marines', 'Caestus Assault Ram', 215),
  ('Space Marines', 'Land Raider Prometheus', 250),
  ('Space Marines', 'Captain on Bike', 95),
  ('Space Marines', 'Land Raider Proteus', 220),
  ('Space Marines', 'Carab Culln the Risen', 250),
  ('Space Marines', 'Land Speeder', 80),
  ('Space Marines', 'Cerberus', 270),
  ('Space Marines', 'Land Speeder Storm', 70),
  ('Space Marines', 'Chaplain Cassius', 80),
  ('Space Marines', 'Land Speeder Tempest', 95),
  ('Space Marines', 'Chaplain Venerable Dreadnought', 150),
  ('Space Marines', 'Land Speeder Tornado', 95),
  ('Space Marines', 'Command Squad', 165),
  ('Space Marines', 'Land Speeder Typhoon', 100),
  ('Space Marines', 'Company Champion on Bike', 60),
  ('Space Marines', 'Leviathan Dreadnought', 160),
  ('Space Marines', 'Company Veterans on Bikes', 110),
  ('Space Marines', 'Librarian on Bike', 80),
  ('Space Marines', 'Deathstorm Drop Pod', 95),
  ('Space Marines', 'Librarian with Jump Pack', 75),
  ('Space Marines', 'Deimos Predator', 115),
  ('Space Marines', 'Mastodon', 540),
  ('Space Marines', 'Deredeo Dreadnought', 160),
  ('Space Marines', 'Mortis Dreadnought', 130),
  ('Space Marines', 'Dreadnought Drop Pod', 75),
  ('Space Marines', 'Primaris Company Champion', 55),
  ('Space Marines', 'Falchion', 420),
  ('Space Marines', 'Rapier Carrier', 90),
  ('Space Marines', 'Relic Contemptor Dreadnought', 140),
  ('Space Marines', 'Relic Razorback', 105),
  ('Space Marines', 'Relic Terminator Squad', 200),
  ('Space Marines', 'Rhino Primaris', 95),
  ('Space Marines', 'Scout Bike Squad', 75),
  ('Space Marines', 'Scout Sniper Squad', 75),
  ('Space Marines', 'Sergeant Chronus', 75),
  ('Space Marines', 'Sergeant Telion', 70),
  ('Space Marines', 'Sicaran Arcus', 160),
  ('Space Marines', 'Sicaran Battle Tank', 160),
  ('Space Marines', 'Sicaran Omega', 180),
  ('Space Marines', 'Sicaran Punisher', 160),
  ('Space Marines', 'Sicaran Venator', 180),
  ('Space Marines', 'Sokar-pattern Stormbird', 900),
  ('Space Marines', 'Spartan', 300),
  ('Space Marines', 'Stalker', 140),
  ('Space Marines', 'Storm Eagle Gunship', 250),
  ('Space Marines', 'Tarantula Air Defence Battery', 70),
  ('Space Marines', 'Tarantula Sentry Battery', 30),
  ('Space Marines', 'Techmarine on Bike', 110),
  ('Space Marines', 'Terminus Ultra', 285),
  ('Space Marines', 'Terrax-pattern Termite', 200),
  ('Dark Angels', 'Thunderfire Cannon', 90),
  ('Dark Angels', 'Deathwing Command Squad', 200),
  ('Dark Angels', 'Thunderhawk Transporter', 495),
  ('Dark Angels', 'Typhon', 320),
  ('Dark Angels', 'Deathwing Strikemaster', 80),
  ('Dark Angels', 'Tyrannic War Veterans', 85),
  ('Dark Angels', 'Ravenwing Talonmaster', 105),
  ('Dark Angels', 'Vanguard Veteran Squad', 120),
  ('Space Wolves', 'Canis Wolfborn', 75),
  ('Space Wolves', 'Cyberwolf', 20),
  ('Space Wolves', 'Vindicator Laser Destroyer', 175),
  ('Space Wolves', 'Harald Deathwolf', 85),
  ('Space Wolves', 'Whirlwind Scorpius', 115),
  ('Space Wolves', 'Krom Dragongaze', 65),
  ('Space Wolves', 'Xiphon Interceptor', 115),
  ('Space Wolves', 'Iron Priest on Thunderwolf', 95),
  ('Blood Angels', 'Logan Grimnar on Stormrider', 180),
  ('Blood Angels', 'Brother Corbulo', 75),
  ('Blood Angels', 'Lukas the Trickster', 50),
  ('Blood Angels', 'Captain Tycho', 75),
  ('Blood Angels', 'Skyclaws', 90),
  ('Blood Angels', 'Death Company Dreadnought with Magna-grapple', 145),
  ('Blood Angels', 'Death Company Marines with Boltguns', 125),
  ('Blood Angels', 'Stormfang Gunship', 300),
  ('Blood Angels', 'Stormwolf', 250),
  ('Blood Angels', 'Death Company Marines with Boltguns and Jump Packs', 140),
  ('Blood Angels', 'Wolf Guard', 85),
  ('Blood Angels', 'Furioso Dreadnought', 150),
  ('Blood Angels', 'Wolf Guard Battle Leader in Terminator Armour', 75),
  ('Blood Angels', 'Gabriel Seth', 90),
  ('Blood Angels', 'Wolf Guard Battle Leader on Thunderwolf', 80),
  ('Blood Angels', 'Librarian Dreadnought', 170),
  ('Blood Angels', 'Wolf Guard Pack Leader', 30),
  ('Blood Angels', 'Sanguinary Priest on Bike', 135),
  ('Blood Angels', 'Wolf Guard Pack Leader in Terminator Armour', 40),
  ('Blood Angels', 'Sanguinary Priest with Jump Pack', 100),
  ('Blood Angels', 'Wolf Guard Pack Leader with Jump Pack', 35),
  ('Blood Angels', 'Tycho the Lost', 90),
  ('Blood Angels', 'Wolf Lord on Thunderwolf', 100),
  ('Ultramarines', 'Ferren Aerios', 80),
  ('Ultramarines', 'Ultramarines Honour Guard', 155),
  ('T''au Empire', 'Aun’Shi', 50),
  ('T''au Empire', 'Aun’Va', 65),
  ('T''au Empire', 'Barracuda', 220),
  ('T''au Empire', 'Commander in Crisis Battlesuit', 80),
  ('T''au Empire', 'Crisis Battlesuits', 200),
  ('T''au Empire', 'Drone Sentry Turret', 50),
  ('T''au Empire', 'Great Knarloc', 100),
  ('T''au Empire', 'Heavy Gun Drones', 45),
  ('T''au Empire', 'Knarloc Riders', 110),
  ('T''au Empire', 'Longstrike', 140),
  ('T''au Empire', 'Orca Dropship', 275),
  ('T''au Empire', 'Remora Stealth Drones', 160),
  ('T''au Empire', 'Remote Sensor Tower', 50),
  ('T''au Empire', 'R’varna Battlesuit', 200),
  ('T''au Empire', 'Shas’o R’alai', 80),
  ('T''au Empire', 'Tetras', 80),
  ('T''au Empire', 'TX42 Piranha', 60),
  ('T''au Empire', 'XV9 Hazard Battlesuits', 55),
  ('T''au Empire', 'Y’vahra Battlesuit', 210),
  ('Tyranids', 'Barbed Hierodule', 340),
  ('Tyranids', 'Dimachaeron', 200),
  ('Tyranids', 'Malanthrope', 75),
  ('Tyranids', 'Scythed Hierodule', 330),
  ('Tyranids', 'Sky-slasher Swarms', 60),
  ('Unaligned Forces', 'Aegis Defence Line with Weapon Emplacement', 145),
  ('Unaligned Forces', 'Ambull', 85),
  ('Unaligned Forces', 'Bastion', 275),
  ('Unaligned Forces', 'Firestorm Redoubt', 260),
  ('Unaligned Forces', 'Fortress of Redemption', 480),
  ('Unaligned Forces', 'Guardian Drone', 45),
  ('Unaligned Forces', 'Macro-cannon Aquila Strongpoint', 550),
  ('Unaligned Forces', 'Plasma Obliterator', 225),
  ('Unaligned Forces', 'Primaris Redoubt', 220),
  ('Unaligned Forces', 'Skyshield Landing Pad', 125),
  ('Unaligned Forces', 'Spindle Drones', 35),
  ('Unaligned Forces', 'The Archivist', 70),
  ('Unaligned Forces', 'Vengeance Weapon Battery', 140),
  ('Unaligned Forces', 'Void Shield Generator', 155),
  ('Unaligned Forces', 'Vortex Missile Strongpoint', 525),
  ('Unaligned Forces', 'Wall of Martyrs Bunker', 180),
  ('Unaligned Forces', 'Wall of Martyrs Defence Emplacement', 140),
  ('Unaligned Forces', 'Wall of Martyrs Defence Line', 140);
