-- Fuzzy bridging missing components
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Space Marines' AND unit_name = 'Bladeguard Veterans' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Space Marines' AND unit_name = 'Tartaros Terminator Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Blood Angels' AND unit_name = 'Death Company Chaplain' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Blood Angels' AND unit_name = 'Sanguinary Ancient' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Black Templars' AND unit_name = 'The Emperor''s Champion' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Black Templars' AND unit_name = 'Marshall' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Deathwatch' AND unit_name = 'Watch Captain in Terminator Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Grey Knights' AND unit_name = 'Brother-Captain in Terminator Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Astra Militarum' AND unit_name = 'Heavy Weapons Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Astra Militarum' AND unit_name = 'Armoured Sentinel' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Astra Militarum' AND unit_name = 'Scout Sentinel' AND base_points = 0;
UPDATE public.unit_points SET base_points = 210 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Custodian Warden' AND base_points = 0;
UPDATE public.unit_points SET base_points = 210 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Custodian Warden Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Agents of the Imperium' AND unit_name = 'Culexis Assassin' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Chaos Sicaran Battle Tank' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'World Eaters' AND unit_name = 'Kharn the Betrayer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Death Guard' AND unit_name = 'Myphitic Blight-Haulers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Death Guard' AND unit_name = 'Foetid Bloat-Drones' AND base_points = 0;
UPDATE public.unit_points SET base_points = 210 WHERE faction = 'Death Guard' AND unit_name = 'Plagueburst Crawlers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Aeldari' AND unit_name = 'Crimson Hunters' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Aeldari' AND unit_name = 'Guardians Defender Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 110 WHERE faction = 'Aeldari' AND unit_name = 'Storm Guardian Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Aeldari' AND unit_name = 'War Walker' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Aeldari' AND unit_name = 'Starweavers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Aeldari' AND unit_name = 'Voidweavers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 115 WHERE faction = 'Drukhari' AND unit_name = 'Kabalite Warrior' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Orks' AND unit_name = 'Mek with Shokk Attack Gun' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Orks' AND unit_name = 'Warbikes' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Tyranids' AND unit_name = 'Lictors' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Genestealer Cults' AND unit_name = 'Achilles Ridgerunner' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'T''au Empire' AND unit_name = 'Commander in Firestorm Battlesuit' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'T''au Empire' AND unit_name = 'Commander in XV86 Coldstar Battlesuit' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'T''au Empire' AND unit_name = 'Kroot Shaper' AND base_points = 0;
UPDATE public.unit_points SET base_points = 200 WHERE faction = 'T''au Empire' AND unit_name = 'XV8 Crisis Battlesuits' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'T''au Empire' AND unit_name = 'XV25 Stealth Battlesuits' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'T''au Empire' AND unit_name = 'XV88 Broadside Battlesuits' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'T''au Empire' AND unit_name = 'XV95 Ghostkeel Battlesuit' AND base_points = 0;
UPDATE public.unit_points SET base_points = 200 WHERE faction = 'T''au Empire' AND unit_name = 'XV104 Riptide Battlesuit' AND base_points = 0;
UPDATE public.unit_points SET base_points = 200 WHERE faction = 'T''au Empire' AND unit_name = 'XV107 R''varna Battlesuit' AND base_points = 0;
UPDATE public.unit_points SET base_points = 210 WHERE faction = 'T''au Empire' AND unit_name = 'XV109 Y''vahra Battlesuit' AND base_points = 0;
UPDATE public.unit_points SET base_points = 360 WHERE faction = 'T''au Empire' AND unit_name = 'KV128 Stormsurge' AND base_points = 0;
UPDATE public.unit_points SET base_points = 790 WHERE faction = 'T''au Empire' AND unit_name = 'KX139 Ta''unar Supremacy Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Leagues of Votann' AND unit_name = 'Hernkyn Yaegir' AND base_points = 0;
