-- Bridge missing points from OpenHammer API
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Space Marines' AND unit_name = 'Captain in Gravis Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Space Marines' AND unit_name = 'Captain in Phobos Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Space Marines' AND unit_name = 'Captain in Terminator Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Space Marines' AND unit_name = 'Captain with Jump Pack' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Space Marines' AND unit_name = 'Lieutenant in Phobos Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Space Marines' AND unit_name = 'Lieutenant in Reiver Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Space Marines' AND unit_name = 'Librarian' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Space Marines' AND unit_name = 'Librarian in Phobos Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Space Marines' AND unit_name = 'Chaplain' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Space Marines' AND unit_name = 'Chaplain on Bike' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Space Marines' AND unit_name = 'Chaplain with Jump Pack' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Space Marines' AND unit_name = 'Apothecary' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Space Marines' AND unit_name = 'Apothecary Biologis' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Space Marines' AND unit_name = 'Ancient' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Space Marines' AND unit_name = 'Techmarine' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Space Marines' AND unit_name = 'Judiciar' AND base_points = 0;
UPDATE public.unit_points SET base_points = 45 WHERE faction = 'Space Marines' AND unit_name = 'Bladeguard Ancient' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Space Marines' AND unit_name = 'Intercessor Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Space Marines' AND unit_name = 'Assault Intercessor Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Space Marines' AND unit_name = 'Heavy Intercessor Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'Space Marines' AND unit_name = 'Tactical Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Space Marines' AND unit_name = 'Scout Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Space Marines' AND unit_name = 'Infiltrator Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Space Marines' AND unit_name = 'Incursor Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Space Marines' AND unit_name = 'Eliminator Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Space Marines' AND unit_name = 'Reiver Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 110 WHERE faction = 'Space Marines' AND unit_name = 'Hellblaster Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Space Marines' AND unit_name = 'Eradicator Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Space Marines' AND unit_name = 'Inceptor Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Space Marines' AND unit_name = 'Sternguard Veteran Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Space Marines' AND unit_name = 'Aggressor Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 200 WHERE faction = 'Space Marines' AND unit_name = 'Desolation Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Space Marines' AND unit_name = 'Infernus Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Space Marines' AND unit_name = 'Devastator Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Space Marines' AND unit_name = 'Terminator Assault Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 170 WHERE faction = 'Space Marines' AND unit_name = 'Terminator Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Space Marines' AND unit_name = 'Outrider Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Space Marines' AND unit_name = 'Invader ATV' AND base_points = 0;
UPDATE public.unit_points SET base_points = 195 WHERE faction = 'Space Marines' AND unit_name = 'Redemptor Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Space Marines' AND unit_name = 'Brutalis Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Space Marines' AND unit_name = 'Ballistus Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 135 WHERE faction = 'Space Marines' AND unit_name = 'Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Space Marines' AND unit_name = 'Rhino' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Space Marines' AND unit_name = 'Razorback' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Space Marines' AND unit_name = 'Impulsor' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Space Marines' AND unit_name = 'Repulsor' AND base_points = 0;
UPDATE public.unit_points SET base_points = 220 WHERE faction = 'Space Marines' AND unit_name = 'Repulsor Executioner' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Space Marines' AND unit_name = 'Drop Pod' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Space Marines' AND unit_name = 'Gladiator Lancer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Space Marines' AND unit_name = 'Gladiator Reaper' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Space Marines' AND unit_name = 'Gladiator Valiant' AND base_points = 0;
UPDATE public.unit_points SET base_points = 135 WHERE faction = 'Space Marines' AND unit_name = 'Predator Annihilator' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'Space Marines' AND unit_name = 'Predator Destructor' AND base_points = 0;
UPDATE public.unit_points SET base_points = 185 WHERE faction = 'Space Marines' AND unit_name = 'Vindicator' AND base_points = 0;
UPDATE public.unit_points SET base_points = 190 WHERE faction = 'Space Marines' AND unit_name = 'Whirlwind' AND base_points = 0;
UPDATE public.unit_points SET base_points = 220 WHERE faction = 'Space Marines' AND unit_name = 'Land Raider' AND base_points = 0;
UPDATE public.unit_points SET base_points = 220 WHERE faction = 'Space Marines' AND unit_name = 'Land Raider Crusader' AND base_points = 0;
UPDATE public.unit_points SET base_points = 270 WHERE faction = 'Space Marines' AND unit_name = 'Land Raider Redeemer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 115 WHERE faction = 'Space Marines' AND unit_name = 'Storm Speeder Hailstrike' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Space Marines' AND unit_name = 'Storm Speeder Hammerstrike' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Space Marines' AND unit_name = 'Storm Speeder Thunderstrike' AND base_points = 0;
UPDATE public.unit_points SET base_points = 155 WHERE faction = 'Space Marines' AND unit_name = 'Stormhawk Interceptor' AND base_points = 0;
UPDATE public.unit_points SET base_points = 165 WHERE faction = 'Space Marines' AND unit_name = 'Stormtalon Gunship' AND base_points = 0;
UPDATE public.unit_points SET base_points = 280 WHERE faction = 'Space Marines' AND unit_name = 'Stormraven Gunship' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Blood Angels' AND unit_name = 'Commander Dante' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Blood Angels' AND unit_name = 'Lemartes' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'Blood Angels' AND unit_name = 'The Sanguinor' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Blood Angels' AND unit_name = 'Astorath' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Blood Angels' AND unit_name = 'Sanguinary Priest' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Blood Angels' AND unit_name = 'Death Company Marines' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Blood Angels' AND unit_name = 'Death Company Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Blood Angels' AND unit_name = 'Sanguinary Guard' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Blood Angels' AND unit_name = 'Baal Predator' AND base_points = 0;
UPDATE public.unit_points SET base_points = 315 WHERE faction = 'Dark Angels' AND unit_name = 'Lion El''Jonson' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Dark Angels' AND unit_name = 'Ezekiel' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Dark Angels' AND unit_name = 'Asmodai' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Dark Angels' AND unit_name = 'Belial' AND base_points = 0;
UPDATE public.unit_points SET base_points = 115 WHERE faction = 'Dark Angels' AND unit_name = 'Sammael' AND base_points = 0;
UPDATE public.unit_points SET base_points = 250 WHERE faction = 'Dark Angels' AND unit_name = 'Deathwing Knights' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Dark Angels' AND unit_name = 'Deathwing Terminator Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Dark Angels' AND unit_name = 'Ravenwing Black Knights' AND base_points = 0;
UPDATE public.unit_points SET base_points = 210 WHERE faction = 'Dark Angels' AND unit_name = 'Ravenwing Dark Talon' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Space Wolves' AND unit_name = 'Ragnar Blackmane' AND base_points = 0;
UPDATE public.unit_points SET base_points = 170 WHERE faction = 'Space Wolves' AND unit_name = 'Bjorn the Fell-Handed' AND base_points = 0;
UPDATE public.unit_points SET base_points = 110 WHERE faction = 'Space Wolves' AND unit_name = 'Logan Grimnar' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Space Wolves' AND unit_name = 'Njal Stormcaller' AND base_points = 0;
UPDATE public.unit_points SET base_points = 105 WHERE faction = 'Space Wolves' AND unit_name = 'Arjac Rockfist' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Space Wolves' AND unit_name = 'Ulrik the Slayer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Space Wolves' AND unit_name = 'Iron Priest' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Space Wolves' AND unit_name = 'Wolf Guard Battle Leader' AND base_points = 0;
UPDATE public.unit_points SET base_points = 170 WHERE faction = 'Space Wolves' AND unit_name = 'Wolf Guard Terminators' AND base_points = 0;
UPDATE public.unit_points SET base_points = 135 WHERE faction = 'Space Wolves' AND unit_name = 'Blood Claws' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Space Wolves' AND unit_name = 'Grey Hunters' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Space Wolves' AND unit_name = 'Wulfen' AND base_points = 0;
UPDATE public.unit_points SET base_points = 40 WHERE faction = 'Space Wolves' AND unit_name = 'Fenrisian Wolves' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Black Templars' AND unit_name = 'High Marshal Helbrecht' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Black Templars' AND unit_name = 'Castellan' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Black Templars' AND unit_name = 'Crusader Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Black Templars' AND unit_name = 'Repulsor' AND base_points = 0;
UPDATE public.unit_points SET base_points = 220 WHERE faction = 'Black Templars' AND unit_name = 'Repulsor Executioner' AND base_points = 0;
UPDATE public.unit_points SET base_points = 220 WHERE faction = 'Black Templars' AND unit_name = 'Land Raider Crusader' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Deathwatch' AND unit_name = 'Watch Master' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Deathwatch' AND unit_name = 'Corvus Blackstar' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Grey Knights' AND unit_name = 'Brother-Captain' AND base_points = 0;
UPDATE public.unit_points SET base_points = 225 WHERE faction = 'Grey Knights' AND unit_name = 'Grand Master in Nemesis Dreadknight' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Grey Knights' AND unit_name = 'Grand Master' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Grey Knights' AND unit_name = 'Brotherhood Champion' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Grey Knights' AND unit_name = 'Brotherhood Librarian' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Grey Knights' AND unit_name = 'Brotherhood Chaplain' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Grey Knights' AND unit_name = 'Paladin Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Grey Knights' AND unit_name = 'Strike Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Grey Knights' AND unit_name = 'Purgation Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Grey Knights' AND unit_name = 'Purifier Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 130 WHERE faction = 'Grey Knights' AND unit_name = 'Interceptor Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 210 WHERE faction = 'Grey Knights' AND unit_name = 'Nemesis Dreadknight' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'Grey Knights' AND unit_name = 'Venerable Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 280 WHERE faction = 'Grey Knights' AND unit_name = 'Stormraven Gunship' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Grey Knights' AND unit_name = 'Rhino' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Grey Knights' AND unit_name = 'Razorback' AND base_points = 0;
UPDATE public.unit_points SET base_points = 200 WHERE faction = 'Ultramarines' AND unit_name = 'Marneus Calgar' AND base_points = 0;
UPDATE public.unit_points SET base_points = 340 WHERE faction = 'Ultramarines' AND unit_name = 'Roboute Guilliman' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Ultramarines' AND unit_name = 'Uriel Ventris' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Imperial Fists' AND unit_name = 'Darnath Lysander' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Iron Hands' AND unit_name = 'Iron Father Feirros' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Raven Guard' AND unit_name = 'Kayvaan Shrike' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Salamanders' AND unit_name = 'Vulkan He''stan' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'White Scars' AND unit_name = 'Kor''sarro Khan' AND base_points = 0;
UPDATE public.unit_points SET base_points = 170 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Morvenn Vahl' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Saint Celestine' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Canoness' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Junith Eruita' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Hospitaller' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Imagifier' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Palatine' AND base_points = 0;
UPDATE public.unit_points SET base_points = 40 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Dialogus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 45 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Arco-flagellants' AND base_points = 0;
UPDATE public.unit_points SET base_points = 105 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Retributor Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Zephyrim Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Seraphim Squad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Penitent Engines' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Mortifiers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Castigator' AND base_points = 0;
UPDATE public.unit_points SET base_points = 115 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Immolator' AND base_points = 0;
UPDATE public.unit_points SET base_points = 210 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Exorcist' AND base_points = 0;
UPDATE public.unit_points SET base_points = 210 WHERE faction = 'Adepta Sororitas' AND unit_name = 'Paragon Warsuits' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Trajann Valoris' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Shield-Captain' AND base_points = 0;
UPDATE public.unit_points SET base_points = 130 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Shield-Captain in Allarus Terminator Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Shield-Captain on Dawneagle Jetbike' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Blade Champion' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Allarus Custodians' AND base_points = 0;
UPDATE public.unit_points SET base_points = 40 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Prosecutors' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Vigilators' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Witchseekers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Knight-Centura' AND base_points = 0;
UPDATE public.unit_points SET base_points = 220 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Venerable Land Raider' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Vertus Praetors' AND base_points = 0;
UPDATE public.unit_points SET base_points = 215 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Caladius Grav-Tank' AND base_points = 0;
UPDATE public.unit_points SET base_points = 105 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Pallas Grav-Attack' AND base_points = 0;
UPDATE public.unit_points SET base_points = 200 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Coronus Grav-Carrier' AND base_points = 0;
UPDATE public.unit_points SET base_points = 225 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Telemon Heavy Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 165 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Contemptor-Galatus Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 155 WHERE faction = 'Adeptus Custodes' AND unit_name = 'Contemptor-Achillus Dreadnought' AND base_points = 0;
UPDATE public.unit_points SET base_points = 175 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Belisarius Cawl' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Tech-Priest Dominus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Tech-Priest Manipulus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Tech-Priest Enginseer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 45 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Technoarcheologist' AND base_points = 0;
UPDATE public.unit_points SET base_points = 35 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Cybernetica Datasmith' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Tech-Priest Manipulus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 35 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Skitarii Marshal' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Skitarii Rangers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Skitarii Vanguard' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Sicarian Ruststalkers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Sicarian Infiltrators' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Corpuscarii Electro-Priests' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Fulgurite Electro-Priests' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Pteraxii Sterylizors' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Pteraxii Skystalkers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Serberys Raiders' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Serberys Sulphurhounds' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Ironstrider Ballistarii' AND base_points = 0;
UPDATE public.unit_points SET base_points = 155 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Onager Dunecrawler' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Kastelan Robots' AND base_points = 0;
UPDATE public.unit_points SET base_points = 165 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Skorpius Disintegrator' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Skorpius Dunerider' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Archaeopter Fusilave' AND base_points = 0;
UPDATE public.unit_points SET base_points = 185 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Archaeopter Stratoraptor' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Adeptus Mechanicus' AND unit_name = 'Archaeopter Transvector' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Agents of the Imperium' AND unit_name = 'Inquisitor' AND base_points = 0;
UPDATE public.unit_points SET base_points = 45 WHERE faction = 'Agents of the Imperium' AND unit_name = 'Vindicare Assassin' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Agents of the Imperium' AND unit_name = 'Callidus Assassin' AND base_points = 0;
UPDATE public.unit_points SET base_points = 110 WHERE faction = 'Agents of the Imperium' AND unit_name = 'Eversor Assassin' AND base_points = 0;
UPDATE public.unit_points SET base_points = 270 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Abaddon the Despoiler' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Haarken Worldclaimer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Chaos Lord' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Chaos Lord in Terminator Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Sorcerer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Sorcerer in Terminator Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Dark Apostle' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Master of Executions' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Master of Possession' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Warpsmith' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Legionaries' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Cultist Mob' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Accursed Cultists' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Chosen' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Possessed' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Chaos Spawn' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Obliterators' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Raptors' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Warp Talons' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Havocs' AND base_points = 0;
UPDATE public.unit_points SET base_points = 190 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Defiler' AND base_points = 0;
UPDATE public.unit_points SET base_points = 130 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Maulerfiend' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Forgefiend' AND base_points = 0;
UPDATE public.unit_points SET base_points = 110 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Venomcrawler' AND base_points = 0;
UPDATE public.unit_points SET base_points = 205 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Heldrake' AND base_points = 0;
UPDATE public.unit_points SET base_points = 130 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Helbrute' AND base_points = 0;
UPDATE public.unit_points SET base_points = 220 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Chaos Land Raider' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Chaos Rhino' AND base_points = 0;
UPDATE public.unit_points SET base_points = 185 WHERE faction = 'Chaos Space Marines' AND unit_name = 'Chaos Vindicator' AND base_points = 0;
UPDATE public.unit_points SET base_points = 360 WHERE faction = 'World Eaters' AND unit_name = 'Angron' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'World Eaters' AND unit_name = 'Lord on Juggernaut' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'World Eaters' AND unit_name = 'Master of Executions' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'World Eaters' AND unit_name = 'Jakhals' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'World Eaters' AND unit_name = 'Exalted Eightbound' AND base_points = 0;
UPDATE public.unit_points SET base_points = 135 WHERE faction = 'World Eaters' AND unit_name = 'Eightbound' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'World Eaters' AND unit_name = 'Helbrute' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'World Eaters' AND unit_name = 'Defiler' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'World Eaters' AND unit_name = 'Maulerfiend' AND base_points = 0;
UPDATE public.unit_points SET base_points = 380 WHERE faction = 'Death Guard' AND unit_name = 'Mortarion' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Death Guard' AND unit_name = 'Typhus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Death Guard' AND unit_name = 'Malignant Plaguecaster' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Death Guard' AND unit_name = 'Plague Surgeon' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Death Guard' AND unit_name = 'Foul Blightspawn' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Death Guard' AND unit_name = 'Noxious Blightbringer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Death Guard' AND unit_name = 'Lord of Virulence' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Death Guard' AND unit_name = 'Lord of Contagion' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Death Guard' AND unit_name = 'Biologus Putrifier' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Death Guard' AND unit_name = 'Tallyman' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Death Guard' AND unit_name = 'Plague Marines' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Death Guard' AND unit_name = 'Poxwalkers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 115 WHERE faction = 'Death Guard' AND unit_name = 'Blightlord Terminators' AND base_points = 0;
UPDATE public.unit_points SET base_points = 115 WHERE faction = 'Death Guard' AND unit_name = 'Helbrute' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Death Guard' AND unit_name = 'Chaos Spawn' AND base_points = 0;
UPDATE public.unit_points SET base_points = 195 WHERE faction = 'Death Guard' AND unit_name = 'Daemon Prince of Nurgle' AND base_points = 0;
UPDATE public.unit_points SET base_points = 435 WHERE faction = 'Thousand Sons' AND unit_name = 'Magnus the Red' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Thousand Sons' AND unit_name = 'Exalted Sorcerer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Thousand Sons' AND unit_name = 'Sorcerer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Thousand Sons' AND unit_name = 'Infernal Master' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Thousand Sons' AND unit_name = 'Sorcerer in Terminator Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 105 WHERE faction = 'Thousand Sons' AND unit_name = 'Rubric Marines' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Thousand Sons' AND unit_name = 'Scarab Occult Terminators' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Thousand Sons' AND unit_name = 'Tzaangors' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Thousand Sons' AND unit_name = 'Tzaangor Enlightened' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Thousand Sons' AND unit_name = 'Tzaangor Shaman' AND base_points = 0;
UPDATE public.unit_points SET base_points = 175 WHERE faction = 'Thousand Sons' AND unit_name = 'Mutalith Vortex Beast' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Thousand Sons' AND unit_name = 'Chaos Spawn' AND base_points = 0;
UPDATE public.unit_points SET base_points = 110 WHERE faction = 'Thousand Sons' AND unit_name = 'Helbrute' AND base_points = 0;
UPDATE public.unit_points SET base_points = 180 WHERE faction = 'Thousand Sons' AND unit_name = 'Daemon Prince of Tzeentch' AND base_points = 0;
UPDATE public.unit_points SET base_points = 340 WHERE faction = 'Emperor''s Children' AND unit_name = 'Fulgrim' AND base_points = 0;
UPDATE public.unit_points SET base_points = 150 WHERE faction = 'Emperor''s Children' AND unit_name = 'Lucius the Eternal' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Emperor''s Children' AND unit_name = 'Sorcerer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 145 WHERE faction = 'Emperor''s Children' AND unit_name = 'Noise Marines' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Emperor''s Children' AND unit_name = 'Chaos Spawn' AND base_points = 0;
UPDATE public.unit_points SET base_points = 235 WHERE faction = 'Orks' AND unit_name = 'Ghazghkull Thraka' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Orks' AND unit_name = 'Zodgrod Wortsnagga' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Orks' AND unit_name = 'Boss Snikrot' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Orks' AND unit_name = 'Warboss' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Orks' AND unit_name = 'Painboy' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Orks' AND unit_name = 'Weirdboy' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Orks' AND unit_name = 'Wurrboy' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Orks' AND unit_name = 'Big Mek' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Orks' AND unit_name = 'Big Mek in Mega Armour' AND base_points = 0;
UPDATE public.unit_points SET base_points = 45 WHERE faction = 'Orks' AND unit_name = 'Mek' AND base_points = 0;
UPDATE public.unit_points SET base_points = 145 WHERE faction = 'Orks' AND unit_name = 'Mozrog Skragbad' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Orks' AND unit_name = 'Boyz' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Orks' AND unit_name = 'Beast Snagga Boyz' AND base_points = 0;
UPDATE public.unit_points SET base_points = 105 WHERE faction = 'Orks' AND unit_name = 'Nobz' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Orks' AND unit_name = 'Kommandos' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Orks' AND unit_name = 'Meganobz' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Orks' AND unit_name = 'Flash Gitz' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Orks' AND unit_name = 'Burna Boyz' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'Orks' AND unit_name = 'Tankbustas' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Orks' AND unit_name = 'Lootas' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Orks' AND unit_name = 'Stormboyz' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Orks' AND unit_name = 'Deff Dread' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Orks' AND unit_name = 'Killa Kans' AND base_points = 0;
UPDATE public.unit_points SET base_points = 265 WHERE faction = 'Orks' AND unit_name = 'Gorkanaut' AND base_points = 0;
UPDATE public.unit_points SET base_points = 280 WHERE faction = 'Orks' AND unit_name = 'Morkanaut' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'Orks' AND unit_name = 'Battlewagon' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Orks' AND unit_name = 'Trukk' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Orks' AND unit_name = 'Warbikers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Orks' AND unit_name = 'Deffkoptas' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Orks' AND unit_name = 'Mek Gunz' AND base_points = 0;
UPDATE public.unit_points SET base_points = 135 WHERE faction = 'Orks' AND unit_name = 'Dakkajet' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Orks' AND unit_name = 'Burna-Bommer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 115 WHERE faction = 'Orks' AND unit_name = 'Blitza-Bommer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 175 WHERE faction = 'Orks' AND unit_name = 'Wazbom Blastajet' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Necrons' AND unit_name = 'Imotekh the Stormlord' AND base_points = 0;
UPDATE public.unit_points SET base_points = 165 WHERE faction = 'Necrons' AND unit_name = 'Illuminor Szeras' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Necrons' AND unit_name = 'Trazyn the Infinite' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Necrons' AND unit_name = 'Orikan the Diviner' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Necrons' AND unit_name = 'Overlord' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Necrons' AND unit_name = 'Overlord with Translocation Shroud' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Necrons' AND unit_name = 'Royal Warden' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Necrons' AND unit_name = 'Psychomancer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Necrons' AND unit_name = 'Technomancer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Necrons' AND unit_name = 'Plasmancer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Necrons' AND unit_name = 'Chronomancer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Necrons' AND unit_name = 'Lokhust Lord' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Necrons' AND unit_name = 'Skorpekh Lord' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Necrons' AND unit_name = 'Necron Warriors' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Necrons' AND unit_name = 'Immortals' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Necrons' AND unit_name = 'Triarch Praetorians' AND base_points = 0;
UPDATE public.unit_points SET base_points = 110 WHERE faction = 'Necrons' AND unit_name = 'Triarch Stalker' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Necrons' AND unit_name = 'Deathmarks' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Necrons' AND unit_name = 'Lychguard' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Necrons' AND unit_name = 'Flayed Ones' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Necrons' AND unit_name = 'Tomb Blades' AND base_points = 0;
UPDATE public.unit_points SET base_points = 40 WHERE faction = 'Necrons' AND unit_name = 'Lokhust Destroyers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Necrons' AND unit_name = 'Lokhust Heavy Destroyers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'Necrons' AND unit_name = 'Skorpekh Destroyers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Necrons' AND unit_name = 'Ophydian Destroyers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Necrons' AND unit_name = 'Canoptek Spyders' AND base_points = 0;
UPDATE public.unit_points SET base_points = 110 WHERE faction = 'Necrons' AND unit_name = 'Canoptek Wraiths' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Necrons' AND unit_name = 'Canoptek Reanimator' AND base_points = 0;
UPDATE public.unit_points SET base_points = 265 WHERE faction = 'Necrons' AND unit_name = 'C''tan Shard of the Deceiver' AND base_points = 0;
UPDATE public.unit_points SET base_points = 305 WHERE faction = 'Necrons' AND unit_name = 'C''tan Shard of the Nightbringer' AND base_points = 0;
UPDATE public.unit_points SET base_points = 300 WHERE faction = 'Necrons' AND unit_name = 'C''tan Shard of the Void Dragon' AND base_points = 0;
UPDATE public.unit_points SET base_points = 105 WHERE faction = 'Necrons' AND unit_name = 'Annihilation Barge' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Necrons' AND unit_name = 'Catacomb Command Barge' AND base_points = 0;
UPDATE public.unit_points SET base_points = 200 WHERE faction = 'Necrons' AND unit_name = 'Doomsday Ark' AND base_points = 0;
UPDATE public.unit_points SET base_points = 115 WHERE faction = 'Necrons' AND unit_name = 'Ghost Ark' AND base_points = 0;
UPDATE public.unit_points SET base_points = 200 WHERE faction = 'Necrons' AND unit_name = 'Doomsday Ark' AND base_points = 0;
UPDATE public.unit_points SET base_points = 145 WHERE faction = 'Necrons' AND unit_name = 'Night Scythe' AND base_points = 0;
UPDATE public.unit_points SET base_points = 230 WHERE faction = 'Necrons' AND unit_name = 'Doom Scythe' AND base_points = 0;
UPDATE public.unit_points SET base_points = 400 WHERE faction = 'Necrons' AND unit_name = 'Monolith' AND base_points = 0;
UPDATE public.unit_points SET base_points = 300 WHERE faction = 'Necrons' AND unit_name = 'Obelisk' AND base_points = 0;
UPDATE public.unit_points SET base_points = 425 WHERE faction = 'Necrons' AND unit_name = 'Tesseract Vault' AND base_points = 0;
UPDATE public.unit_points SET base_points = 170 WHERE faction = 'Tyranids' AND unit_name = 'Winged Hive Tyrant' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Tyranids' AND unit_name = 'Parasite of Mortrex' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Tyranids' AND unit_name = 'Deathleaper' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Tyranids' AND unit_name = 'Gargoyles' AND base_points = 0;
UPDATE public.unit_points SET base_points = 125 WHERE faction = 'Tyranids' AND unit_name = 'Raveners' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'Tyranids' AND unit_name = 'Trygon' AND base_points = 0;
UPDATE public.unit_points SET base_points = 135 WHERE faction = 'Tyranids' AND unit_name = 'Mawloc' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Genestealer Cults' AND unit_name = 'Magus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Genestealer Cults' AND unit_name = 'Primus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Genestealer Cults' AND unit_name = 'Nexos' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Genestealer Cults' AND unit_name = 'Clamavus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 45 WHERE faction = 'Genestealer Cults' AND unit_name = 'Locus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'Genestealer Cults' AND unit_name = 'Biophagus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 55 WHERE faction = 'Genestealer Cults' AND unit_name = 'Jackal Alphus' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'Genestealer Cults' AND unit_name = 'Kelermorph' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Genestealer Cults' AND unit_name = 'Abominant' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Genestealer Cults' AND unit_name = 'Neophyte Hybrids' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Genestealer Cults' AND unit_name = 'Hybrid Metamorphs' AND base_points = 0;
UPDATE public.unit_points SET base_points = 135 WHERE faction = 'Genestealer Cults' AND unit_name = 'Aberrants' AND base_points = 0;
UPDATE public.unit_points SET base_points = 120 WHERE faction = 'Genestealer Cults' AND unit_name = 'Goliath Rockgrinder' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Genestealer Cults' AND unit_name = 'Goliath Truck' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'Genestealer Cults' AND unit_name = 'Atalan Jackals' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'T''au Empire' AND unit_name = 'Commander in Coldstar Battlesuit' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'T''au Empire' AND unit_name = 'Commander in Enforcer Battlesuit' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'T''au Empire' AND unit_name = 'Commander Farsight' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'T''au Empire' AND unit_name = 'Commander Shadowsun' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'T''au Empire' AND unit_name = 'Ethereal' AND base_points = 0;
UPDATE public.unit_points SET base_points = 50 WHERE faction = 'T''au Empire' AND unit_name = 'Cadre Fireblade' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'T''au Empire' AND unit_name = 'Kroot Carnivores' AND base_points = 0;
UPDATE public.unit_points SET base_points = 40 WHERE faction = 'T''au Empire' AND unit_name = 'Kroot Hounds' AND base_points = 0;
UPDATE public.unit_points SET base_points = 40 WHERE faction = 'T''au Empire' AND unit_name = 'Krootox Riders' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'T''au Empire' AND unit_name = 'Vespid Stingwings' AND base_points = 0;
UPDATE public.unit_points SET base_points = 90 WHERE faction = 'T''au Empire' AND unit_name = 'Pathfinder Team' AND base_points = 0;
UPDATE public.unit_points SET base_points = 85 WHERE faction = 'T''au Empire' AND unit_name = 'Devilfish' AND base_points = 0;
UPDATE public.unit_points SET base_points = 145 WHERE faction = 'T''au Empire' AND unit_name = 'Hammerhead Gunship' AND base_points = 0;
UPDATE public.unit_points SET base_points = 140 WHERE faction = 'T''au Empire' AND unit_name = 'Sky Ray Gunship' AND base_points = 0;
UPDATE public.unit_points SET base_points = 60 WHERE faction = 'T''au Empire' AND unit_name = 'Piranha' AND base_points = 0;
UPDATE public.unit_points SET base_points = 170 WHERE faction = 'T''au Empire' AND unit_name = 'Razorshark Strike Fighter' AND base_points = 0;
UPDATE public.unit_points SET base_points = 160 WHERE faction = 'T''au Empire' AND unit_name = 'Sun Shark Bomber' AND base_points = 0;
UPDATE public.unit_points SET base_points = 325 WHERE faction = 'T''au Empire' AND unit_name = 'Tiger Shark' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Leagues of Votann' AND unit_name = 'Ûthar the Destined' AND base_points = 0;
UPDATE public.unit_points SET base_points = 65 WHERE faction = 'Leagues of Votann' AND unit_name = 'Grimnyr' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Leagues of Votann' AND unit_name = 'Kâhl' AND base_points = 0;
UPDATE public.unit_points SET base_points = 75 WHERE faction = 'Leagues of Votann' AND unit_name = 'Brôkhyr Iron-Master' AND base_points = 0;
UPDATE public.unit_points SET base_points = 70 WHERE faction = 'Leagues of Votann' AND unit_name = 'Einhyr Champion' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Leagues of Votann' AND unit_name = 'Brôkhyr Thunderkyn' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Leagues of Votann' AND unit_name = 'Hearthkyn Warriors' AND base_points = 0;
UPDATE public.unit_points SET base_points = 135 WHERE faction = 'Leagues of Votann' AND unit_name = 'Einhyr Hearthguard' AND base_points = 0;
UPDATE public.unit_points SET base_points = 80 WHERE faction = 'Leagues of Votann' AND unit_name = 'Hernkyn Pioneers' AND base_points = 0;
UPDATE public.unit_points SET base_points = 100 WHERE faction = 'Leagues of Votann' AND unit_name = 'Cthonian Beserks' AND base_points = 0;
UPDATE public.unit_points SET base_points = 95 WHERE faction = 'Leagues of Votann' AND unit_name = 'Sagitaur' AND base_points = 0;
UPDATE public.unit_points SET base_points = 240 WHERE faction = 'Leagues of Votann' AND unit_name = 'Hekaton Land Fortress' AND base_points = 0;
