-- Update Database with Real Base Points
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Captain in Gravis Armour';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Captain in Phobos Armour';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Captain in Terminator Armour';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Captain with Jump Pack';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Lieutenant in Phobos Armour';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Lieutenant in Reiver Armour';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Librarian';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Librarian in Phobos Armour';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Chaplain';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Chaplain on Bike';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Chaplain with Jump Pack';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Apothecary';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Apothecary Biologis';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Ancient';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Techmarine';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Judiciar';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Bladeguard Ancient';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Heavy Intercessor Squad';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Tactical Squad';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Scout Squad';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Infiltrator Squad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Incursor Squad';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Eliminator Squad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Reiver Squad';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Hellblaster Squad';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Eradicator Squad';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Inceptor Squad';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Sternguard Veteran Squad';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Vanguard Veteran Squad';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Aggressor Squad';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Desolation Squad';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Infernus Squad';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Assault Squad';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Devastator Squad';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Company Heroes';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Terminator Assault Squad';
UPDATE public.unit_points SET base_points = 175 WHERE unit_name = 'Terminator Squad';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Outrider Squad';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Attack Bike Squad';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Bike Squad';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Invader ATV';
UPDATE public.unit_points SET base_points = 205 WHERE unit_name = 'Redemptor Dreadnought';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Brutalis Dreadnought';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Ballistus Dreadnought';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Ironclad Dreadnought';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'Venerable Dreadnought';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Dreadnought';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Rhino';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Razorback';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Impulsor';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Repulsor';
UPDATE public.unit_points SET base_points = 235 WHERE unit_name = 'Repulsor Executioner';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Drop Pod';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Gladiator Lancer';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Gladiator Reaper';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Gladiator Valiant';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Predator Annihilator';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Predator Destructor';
UPDATE public.unit_points SET base_points = 185 WHERE unit_name = 'Vindicator';
UPDATE public.unit_points SET base_points = 190 WHERE unit_name = 'Whirlwind';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Thunderfire Cannon';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'Land Raider';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'Land Raider Crusader';
UPDATE public.unit_points SET base_points = 270 WHERE unit_name = 'Land Raider Redeemer';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Land Speeder';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Land Speeder Storm';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Land Speeder Tempest';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Storm Speeder Hailstrike';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Storm Speeder Hammerstrike';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Storm Speeder Thunderstrike';
UPDATE public.unit_points SET base_points = 155 WHERE unit_name = 'Stormhawk Interceptor';
UPDATE public.unit_points SET base_points = 165 WHERE unit_name = 'Stormtalon Gunship';
UPDATE public.unit_points SET base_points = 280 WHERE unit_name = 'Stormraven Gunship';
UPDATE public.unit_points SET base_points = 290 WHERE unit_name = 'Fire Raptor Gunship';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Commander Dante';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Tycho the Lost';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Lemartes';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'The Sanguinor';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Astorath';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Sanguinary Priest';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Captain with Jump Pack';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Death Company Marines';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Death Company Dreadnought';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Sanguinary Guard';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Baal Predator';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Furioso Dreadnought';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Librarian Dreadnought';
UPDATE public.unit_points SET base_points = 315 WHERE unit_name = 'Lion El''Jonson';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Ezekiel';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Asmodai';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Belial';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Sammael';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Ravenwing Talonmaster';
UPDATE public.unit_points SET base_points = 250 WHERE unit_name = 'Deathwing Knights';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Deathwing Terminator Squad';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Deathwing Command Squad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Ravenwing Black Knights';
UPDATE public.unit_points SET base_points = 210 WHERE unit_name = 'Ravenwing Dark Talon';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Ragnar Blackmane';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Bjorn the Fell-Handed';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Logan Grimnar';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Canis Wolfborn';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Njal Stormcaller';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Arjac Rockfist';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Ulrik the Slayer';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Lukas the Trickster';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Iron Priest';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Wolf Guard Battle Leader';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Wolf Guard Terminators';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Blood Claws';
UPDATE public.unit_points SET base_points = 165 WHERE unit_name = 'Grey Hunters';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Long Fangs';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Skyclaws';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Thunderwolf Cavalry';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Wulfen';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Fenrisian Wolves';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Hounds of Morkai';
UPDATE public.unit_points SET base_points = 20 WHERE unit_name = 'Cyberwolf';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Land Speeder Vengeance';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'High Marshal Helbrecht';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Castellan';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Chaplain';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Crusader Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Repulsor';
UPDATE public.unit_points SET base_points = 235 WHERE unit_name = 'Repulsor Executioner';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'Land Raider Crusader';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Watch Master';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Librarian';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Chaplain';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Vanguard Veteran Squad';
UPDATE public.unit_points SET base_points = 175 WHERE unit_name = 'Terminator Squad';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Dreadnought';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'Venerable Dreadnought';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Corvus Blackstar';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Repulsor';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'Land Raider';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Brother-Captain';
UPDATE public.unit_points SET base_points = 225 WHERE unit_name = 'Grand Master in Nemesis Dreadknight';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Grand Master';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Brotherhood Champion';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Brotherhood Librarian';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Brotherhood Chaplain';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Paladin Squad';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Strike Squad';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Purgation Squad';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Purifier Squad';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Interceptor Squad';
UPDATE public.unit_points SET base_points = 175 WHERE unit_name = 'Terminator Squad';
UPDATE public.unit_points SET base_points = 210 WHERE unit_name = 'Nemesis Dreadknight';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Dreadnought';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'Venerable Dreadnought';
UPDATE public.unit_points SET base_points = 280 WHERE unit_name = 'Stormraven Gunship';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Rhino';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Razorback';
UPDATE public.unit_points SET base_points = 340 WHERE unit_name = 'Roboute Guilliman';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Uriel Ventris';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Darnath Lysander';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Iron Father Feirros';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Kayvaan Shrike';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Vanguard Veteran Squad';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Scout Squad';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Vulkan He''stan';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Aggressor Squad';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Eradicator Squad';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Kor''sarro Khan';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Outrider Squad';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Bike Squad';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Attack Bike Squad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Intercessor Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Assault Intercessor Squad';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'Lord Solar Leontus';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Ursula Creed';
UPDATE public.unit_points SET base_points = 30 WHERE unit_name = 'Commissar';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Primaris Psyker';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Tech-Priest Enginseer';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Militarum Tempestus Command Squad';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Gaunts Ghosts';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Cadian Shock Troops';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Catachan Jungle Fighters';
UPDATE public.unit_points SET base_points = 165 WHERE unit_name = 'Command Squad';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Ratlings';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Ogryn Bodyguard';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Nork Deddog';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Chimera';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Taurox';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Taurox Prime';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Hellhound';
UPDATE public.unit_points SET base_points = 185 WHERE unit_name = 'Leman Russ Battle Tank';
UPDATE public.unit_points SET base_points = 190 WHERE unit_name = 'Leman Russ Demolisher';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Leman Russ Punisher';
UPDATE public.unit_points SET base_points = 145 WHERE unit_name = 'Leman Russ Vanquisher';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Leman Russ Executioner';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Leman Russ Exterminator';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Leman Russ Eradicator';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Basilisk';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Wyvern';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Hydra';
UPDATE public.unit_points SET base_points = 165 WHERE unit_name = 'Manticore';
UPDATE public.unit_points SET base_points = 145 WHERE unit_name = 'Deathstrike';
UPDATE public.unit_points SET base_points = 450 WHERE unit_name = 'Baneblade';
UPDATE public.unit_points SET base_points = 410 WHERE unit_name = 'Shadowsword';
UPDATE public.unit_points SET base_points = 465 WHERE unit_name = 'Stormsword';
UPDATE public.unit_points SET base_points = 415 WHERE unit_name = 'Stormblade';
UPDATE public.unit_points SET base_points = 420 WHERE unit_name = 'Hellhammer';
UPDATE public.unit_points SET base_points = 420 WHERE unit_name = 'Banehammer';
UPDATE public.unit_points SET base_points = 415 WHERE unit_name = 'Doomhammer';
UPDATE public.unit_points SET base_points = 190 WHERE unit_name = 'Valkyrie';
UPDATE public.unit_points SET base_points = 185 WHERE unit_name = 'Morvenn Vahl';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Saint Celestine';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Canoness';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Junith Eruita';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Hospitaller';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Imagifier';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Palatine';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Dialogus';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Battle Sisters Squad';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Celestian Sacresants';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Arco-flagellants';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Crusaders';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Death Cult Assassins';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Dominion Squad';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Retributor Squad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Zephyrim Squad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Seraphim Squad';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Penitent Engines';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Mortifiers';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Castigator';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Immolator';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Rhino';
UPDATE public.unit_points SET base_points = 210 WHERE unit_name = 'Exorcist';
UPDATE public.unit_points SET base_points = 210 WHERE unit_name = 'Paragon Warsuits';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Trajann Valoris';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Shield-Captain';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'Shield-Captain in Allarus Terminator Armour';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Shield-Captain on Dawneagle Jetbike';
UPDATE public.unit_points SET base_points = 285 WHERE unit_name = 'Valdor';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Blade Champion';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Allarus Custodians';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Prosecutors';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Vigilators';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Witchseekers';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Knight-Centura';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'Venerable Land Raider';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Vertus Praetors';
UPDATE public.unit_points SET base_points = 215 WHERE unit_name = 'Caladius Grav-Tank';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Pallas Grav-Attack';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Coronus Grav-Carrier';
UPDATE public.unit_points SET base_points = 225 WHERE unit_name = 'Telemon Heavy Dreadnought';
UPDATE public.unit_points SET base_points = 165 WHERE unit_name = 'Contemptor-Galatus Dreadnought';
UPDATE public.unit_points SET base_points = 155 WHERE unit_name = 'Contemptor-Achillus Dreadnought';
UPDATE public.unit_points SET base_points = 210 WHERE unit_name = 'Belisarius Cawl';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Tech-Priest Dominus';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Tech-Priest Manipulus';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Tech-Priest Enginseer';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Technoarcheologist';
UPDATE public.unit_points SET base_points = 35 WHERE unit_name = 'Cybernetica Datasmith';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Tech-Priest Manipulus';
UPDATE public.unit_points SET base_points = 35 WHERE unit_name = 'Skitarii Marshal';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Skitarii Rangers';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Skitarii Vanguard';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Sicarian Ruststalkers';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Sicarian Infiltrators';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Corpuscarii Electro-Priests';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Fulgurite Electro-Priests';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Pteraxii Sterylizors';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Pteraxii Skystalkers';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Serberys Raiders';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Serberys Sulphurhounds';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Ironstrider Ballistarii';
UPDATE public.unit_points SET base_points = 155 WHERE unit_name = 'Onager Dunecrawler';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Kastelan Robots';
UPDATE public.unit_points SET base_points = 165 WHERE unit_name = 'Skorpius Disintegrator';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Skorpius Dunerider';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Archaeopter Fusilave';
UPDATE public.unit_points SET base_points = 185 WHERE unit_name = 'Archaeopter Stratoraptor';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Archaeopter Transvector';
UPDATE public.unit_points SET base_points = 375 WHERE unit_name = 'Knight Paladin';
UPDATE public.unit_points SET base_points = 355 WHERE unit_name = 'Knight Errant';
UPDATE public.unit_points SET base_points = 385 WHERE unit_name = 'Knight Crusader';
UPDATE public.unit_points SET base_points = 355 WHERE unit_name = 'Knight Gallant';
UPDATE public.unit_points SET base_points = 375 WHERE unit_name = 'Knight Warden';
UPDATE public.unit_points SET base_points = 365 WHERE unit_name = 'Knight Preceptor';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Armiger Warglaive';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Armiger Helverin';
UPDATE public.unit_points SET base_points = 415 WHERE unit_name = 'Canis Rex';
UPDATE public.unit_points SET base_points = 395 WHERE unit_name = 'Cerastus Knight-Lancer';
UPDATE public.unit_points SET base_points = 395 WHERE unit_name = 'Cerastus Knight-Castigator';
UPDATE public.unit_points SET base_points = 700 WHERE unit_name = 'Acastus Knight Porphyrion';
UPDATE public.unit_points SET base_points = 765 WHERE unit_name = 'Acastus Knight Asterius';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Inquisitor';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Inquisitor in Terminator Armour';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Vindicare Assassin';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Callidus Assassin';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Eversor Assassin';
UPDATE public.unit_points SET base_points = 270 WHERE unit_name = 'Abaddon the Despoiler';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Haarken Worldclaimer';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Lucius the Eternal';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Chaos Lord';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Chaos Lord in Terminator Armour';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Chaos Lord on Bike';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Sorcerer';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Sorcerer in Terminator Armour';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Dark Apostle';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Master of Executions';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Master of Possession';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Warpsmith';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Legionaries';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Cultist Mob';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Accursed Cultists';
UPDATE public.unit_points SET base_points = 175 WHERE unit_name = 'Chaos Terminators';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Chosen';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Possessed';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Chaos Spawn';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Mutilators';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Obliterators';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Raptors';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Warp Talons';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Havocs';
UPDATE public.unit_points SET base_points = 185 WHERE unit_name = 'Vindicator';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'Land Raider';
UPDATE public.unit_points SET base_points = 250 WHERE unit_name = 'Defiler';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Maulerfiend';
UPDATE public.unit_points SET base_points = 165 WHERE unit_name = 'Forgefiend';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Venomcrawler';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Heldrake';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Helbrute';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Rhino';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Predator Annihilator';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Predator Destructor';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'Chaos Land Raider';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Chaos Rhino';
UPDATE public.unit_points SET base_points = 185 WHERE unit_name = 'Chaos Vindicator';
UPDATE public.unit_points SET base_points = 340 WHERE unit_name = 'Angron';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Lord on Juggernaut';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Master of Executions';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Chaos Lord';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Jakhals';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Exalted Eightbound';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Eightbound';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Helbrute';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Rhino';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'Land Raider';
UPDATE public.unit_points SET base_points = 250 WHERE unit_name = 'Defiler';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Maulerfiend';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Skull Altar';
UPDATE public.unit_points SET base_points = 380 WHERE unit_name = 'Mortarion';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Typhus';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Death Guard Chaos Lord';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Malignant Plaguecaster';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Plague Surgeon';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Foul Blightspawn';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Noxious Blightbringer';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Lord of Virulence';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Lord of Contagion';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Biologus Putrifier';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Tallyman';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Plague Marines';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Poxwalkers';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Blightlord Terminators';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Helbrute';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Chaos Spawn';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Rhino';
UPDATE public.unit_points SET base_points = 195 WHERE unit_name = 'Daemon Prince of Nurgle';
UPDATE public.unit_points SET base_points = 435 WHERE unit_name = 'Magnus the Red';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Exalted Sorcerer';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Sorcerer';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Infernal Master';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Sorcerer in Terminator Armour';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Rubric Marines';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Scarab Occult Terminators';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Tzaangors';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Tzaangor Enlightened';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Tzaangor Shaman';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Mutalith Vortex Beast';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Chaos Spawn';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Helbrute';
UPDATE public.unit_points SET base_points = 180 WHERE unit_name = 'Daemon Prince of Tzeentch';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Rhino';
UPDATE public.unit_points SET base_points = 340 WHERE unit_name = 'Fulgrim';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Lucius the Eternal';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Chaos Lord';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Sorcerer';
UPDATE public.unit_points SET base_points = 145 WHERE unit_name = 'Noise Marines';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Possessed';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Raptors';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Chaos Spawn';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Rhino';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Helbrute';
UPDATE public.unit_points SET base_points = 305 WHERE unit_name = 'Skarbrand';
UPDATE public.unit_points SET base_points = 305 WHERE unit_name = 'Bloodthirster';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Skulltaker';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Bloodmaster';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Skullmaster';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Karanak';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Bloodletters';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Flesh Hounds';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Bloodcrushers';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Skull Cannon';
UPDATE public.unit_points SET base_points = 295 WHERE unit_name = 'Kairos Fateweaver';
UPDATE public.unit_points SET base_points = 285 WHERE unit_name = 'Lord of Change';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Changecaster';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Fluxmaster';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Fateskimmer';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Pink Horrors';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Blue Horrors';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Flamers';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Screamers';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Exalted Flamer';
UPDATE public.unit_points SET base_points = 265 WHERE unit_name = 'Rotigus';
UPDATE public.unit_points SET base_points = 250 WHERE unit_name = 'Great Unclean One';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Poxbringer';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Sloppity Bilepiper';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Spoilpox Scrivener';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Epidemius';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Plaguebearers';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Nurglings';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Beasts of Nurgle';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Plague Drones';
UPDATE public.unit_points SET base_points = 240 WHERE unit_name = 'Keeper of Secrets';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Infernal Enrapturess';
UPDATE public.unit_points SET base_points = 340 WHERE unit_name = 'Shalaxi Helbane';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Syll''Esske';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Daemonettes';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Seekers';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Fiends';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Seeker Chariot';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Hellflayer';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Exalted Seeker Chariot';
UPDATE public.unit_points SET base_points = 375 WHERE unit_name = 'Be''lakor';
UPDATE public.unit_points SET base_points = 175 WHERE unit_name = 'Vashtorr the Arkifane';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'War Dog Executioner';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'War Dog Brigand';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'War Dog Karnivore';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'War Dog Huntsman';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'War Dog Stalker';
UPDATE public.unit_points SET base_points = 355 WHERE unit_name = 'Knight Abominant';
UPDATE public.unit_points SET base_points = 365 WHERE unit_name = 'Knight Rampager';
UPDATE public.unit_points SET base_points = 390 WHERE unit_name = 'Knight Despoiler';
UPDATE public.unit_points SET base_points = 410 WHERE unit_name = 'Knight Tyrant';
UPDATE public.unit_points SET base_points = 355 WHERE unit_name = 'Knight Desecrator';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Eldrad Ulthran';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Yvraine';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'The Visarch';
UPDATE public.unit_points SET base_points = 260 WHERE unit_name = 'The Yncarne';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Farseer';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Autarch';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Autarch Skyrunner';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Warlock';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Spiritseer';
UPDATE public.unit_points SET base_points = 280 WHERE unit_name = 'Avatar of Khaine';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Dire Avengers';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Fire Dragons';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Howling Banshees';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Striking Scorpions';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Dark Reapers';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Warp Spiders';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Swooping Hawks';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Shining Spears';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Rangers';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Wraithguard';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Wraithblades';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'Wraithlord';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Fire Prism';
UPDATE public.unit_points SET base_points = 190 WHERE unit_name = 'Night Spinner';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'Falcon';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Wave Serpent';
UPDATE public.unit_points SET base_points = 155 WHERE unit_name = 'Hemlock Wraithfighter';
UPDATE public.unit_points SET base_points = 435 WHERE unit_name = 'Wraithknight';
UPDATE public.unit_points SET base_points = 1100 WHERE unit_name = 'Revenant Titan';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Troupe Master';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Shadowseer';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Death Jester';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Solitaire';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Troupe';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Skyweavers';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Spiritseer';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Yvraine';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'The Visarch';
UPDATE public.unit_points SET base_points = 260 WHERE unit_name = 'The Yncarne';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Archon';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Haemonculus';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Succubus';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Beastmaster';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Kabalite Warriors';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Wyches';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Hellions';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Reavers';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Wracks';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Grotesques';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Ravager';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Venom';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Raider';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Razorwing Jetfighter';
UPDATE public.unit_points SET base_points = 245 WHERE unit_name = 'Voidraven Bomber';
UPDATE public.unit_points SET base_points = 235 WHERE unit_name = 'Ghazghkull Thraka';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Zodgrod Wortsnagga';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Boss Snikrot';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Boss Zagstruk';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Mad Dok Grotsnik';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Warboss';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Warboss on Warbike';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Painboy';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Weirdboy';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Wurrboy';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Big Mek';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Big Mek in Mega Armour';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Mek';
UPDATE public.unit_points SET base_points = 145 WHERE unit_name = 'Mozrog Skragbad';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Boyz';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Gretchin';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Beast Snagga Boyz';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Nobz';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Nobz on Warbikes';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Kommandos';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Meganobz';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Flash Gitz';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Burna Boyz';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Tankbustas';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Lootas';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Storm Boyz';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Stormboyz';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Deff Dread';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Killa Kans';
UPDATE public.unit_points SET base_points = 265 WHERE unit_name = 'Gorkanaut';
UPDATE public.unit_points SET base_points = 280 WHERE unit_name = 'Morkanaut';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Squighog Boyz';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Battlewagon';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Trukk';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Warbikers';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Deffkoptas';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Mek Gunz';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Dakkajet';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Burna-Bommer';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Blitza-Bommer';
UPDATE public.unit_points SET base_points = 175 WHERE unit_name = 'Wazbom Blastajet';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Imotekh the Stormlord';
UPDATE public.unit_points SET base_points = 165 WHERE unit_name = 'Illuminor Szeras';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Trazyn the Infinite';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Orikan the Diviner';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Nemesor Zahndrekh';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Vargard Obyron';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Overlord';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Overlord with Translocation Shroud';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Royal Warden';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Psychomancer';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Technomancer';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Plasmancer';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Chronomancer';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Lord';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Lokhust Lord';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Skorpekh Lord';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Necron Warriors';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Immortals';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Triarch Praetorians';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Triarch Stalker';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Deathmarks';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Lychguard';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Flayed Ones';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Tomb Blades';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Lokhust Destroyers';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Lokhust Heavy Destroyers';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Skorpekh Destroyers';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Ophydian Destroyers';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Canoptek Spyders';
UPDATE public.unit_points SET base_points = 110 WHERE unit_name = 'Canoptek Wraiths';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Canoptek Acanthrites';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Canoptek Reanimator';
UPDATE public.unit_points SET base_points = 310 WHERE unit_name = 'C''tan Shard of the Deceiver';
UPDATE public.unit_points SET base_points = 340 WHERE unit_name = 'C''tan Shard of the Nightbringer';
UPDATE public.unit_points SET base_points = 330 WHERE unit_name = 'C''tan Shard of the Void Dragon';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Annihilation Barge';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Catacomb Command Barge';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Doomsday Ark';
UPDATE public.unit_points SET base_points = 115 WHERE unit_name = 'Ghost Ark';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Doomsday Ark';
UPDATE public.unit_points SET base_points = 130 WHERE unit_name = 'Tesseract Ark';
UPDATE public.unit_points SET base_points = 145 WHERE unit_name = 'Night Scythe';
UPDATE public.unit_points SET base_points = 230 WHERE unit_name = 'Doom Scythe';
UPDATE public.unit_points SET base_points = 400 WHERE unit_name = 'Monolith';
UPDATE public.unit_points SET base_points = 300 WHERE unit_name = 'Obelisk';
UPDATE public.unit_points SET base_points = 425 WHERE unit_name = 'Tesseract Vault';
UPDATE public.unit_points SET base_points = 220 WHERE unit_name = 'The Swarmlord';
UPDATE public.unit_points SET base_points = 195 WHERE unit_name = 'Hive Tyrant';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Winged Hive Tyrant';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Old One Eye';
UPDATE public.unit_points SET base_points = 260 WHERE unit_name = 'Norn Emissary';
UPDATE public.unit_points SET base_points = 275 WHERE unit_name = 'Norn Assimilator';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Tervigon';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Parasite of Mortrex';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Broodlord';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Deathleaper';
UPDATE public.unit_points SET base_points = 105 WHERE unit_name = 'Neurotyrant';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Termagants';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Hormagaunts';
UPDATE public.unit_points SET base_points = 25 WHERE unit_name = 'Ripper Swarms';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Gargoyles';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Genestealers';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Raveners';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Zoanthropes';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Venomthropes';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Pyrovores';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Hive Guard';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Carnifexes';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Screamer-Killer';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Maleceptor';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Toxicrene';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Exocrine';
UPDATE public.unit_points SET base_points = 125 WHERE unit_name = 'Haruspex';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Trygon';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Mawloc';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Tyrannofex';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Dimachaeron';
UPDATE public.unit_points SET base_points = 215 WHERE unit_name = 'Harpy';
UPDATE public.unit_points SET base_points = 200 WHERE unit_name = 'Hive Crone';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Magus';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Primus';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Nexos';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Clamavus';
UPDATE public.unit_points SET base_points = 45 WHERE unit_name = 'Locus';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Biophagus';
UPDATE public.unit_points SET base_points = 55 WHERE unit_name = 'Jackal Alphus';
UPDATE public.unit_points SET base_points = 60 WHERE unit_name = 'Kelermorph';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Abominant';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Neophyte Hybrids';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Hybrid Metamorphs';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Aberrants';
UPDATE public.unit_points SET base_points = 120 WHERE unit_name = 'Goliath Rockgrinder';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Goliath Truck';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Atalan Jackals';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Longstrike';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Commander in Coldstar Battlesuit';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Commander in Enforcer Battlesuit';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Commander Farsight';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Commander Shadowsun';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Aun''va';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Aun''shi';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Ethereal';
UPDATE public.unit_points SET base_points = 50 WHERE unit_name = 'Cadre Fireblade';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Kroot Carnivores';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Kroot Hounds';
UPDATE public.unit_points SET base_points = 40 WHERE unit_name = 'Krootox Riders';
UPDATE public.unit_points SET base_points = 140 WHERE unit_name = 'Longstrike';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Vespid Stingwings';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Pathfinder Team';
UPDATE public.unit_points SET base_points = 85 WHERE unit_name = 'Devilfish';
UPDATE public.unit_points SET base_points = 145 WHERE unit_name = 'Hammerhead Gunship';
UPDATE public.unit_points SET base_points = 150 WHERE unit_name = 'Sky Ray Gunship';
UPDATE public.unit_points SET base_points = 170 WHERE unit_name = 'Razorshark Strike Fighter';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Sun Shark Bomber';
UPDATE public.unit_points SET base_points = 325 WHERE unit_name = 'Tiger Shark';
UPDATE public.unit_points SET base_points = 95 WHERE unit_name = 'Ûthar the Destined';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Grimnyr';
UPDATE public.unit_points SET base_points = 65 WHERE unit_name = 'Kâhl';
UPDATE public.unit_points SET base_points = 75 WHERE unit_name = 'Brôkhyr Iron-Master';
UPDATE public.unit_points SET base_points = 70 WHERE unit_name = 'Einhyr Champion';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Brôkhyr Thunderkyn';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Hearthkyn Warriors';
UPDATE public.unit_points SET base_points = 135 WHERE unit_name = 'Einhyr Hearthguard';
UPDATE public.unit_points SET base_points = 80 WHERE unit_name = 'Hernkyn Pioneers';
UPDATE public.unit_points SET base_points = 100 WHERE unit_name = 'Cthonian Beserks';
UPDATE public.unit_points SET base_points = 90 WHERE unit_name = 'Sagitaur';
UPDATE public.unit_points SET base_points = 240 WHERE unit_name = 'Hekaton Land Fortress';
UPDATE public.unit_points SET base_points = 160 WHERE unit_name = 'Colossus';
