-- Seed Database with base units
INSERT INTO public.unit_points (faction, unit_name, base_points) VALUES
('Space Marines', 'Captain in Gravis Armour', 0),
('Space Marines', 'Captain in Phobos Armour', 0),
('Space Marines', 'Captain in Terminator Armour', 0),
('Space Marines', 'Captain with Jump Pack', 0),
('Space Marines', 'Primaris Captain', 0),
('Space Marines', 'Lieutenant in Phobos Armour', 0),
('Space Marines', 'Lieutenant in Reiver Armour', 0),
('Space Marines', 'Primaris Lieutenant', 0),
('Space Marines', 'Librarian', 0),
('Space Marines', 'Librarian in Phobos Armour', 0),
('Space Marines', 'Liturgies of Battle Chaplain', 0),
('Space Marines', 'Chaplain', 0),
('Space Marines', 'Chaplain on Bike', 0),
('Space Marines', 'Chaplain with Jump Pack', 0),
('Space Marines', 'Apothecary', 0),
('Space Marines', 'Chief Apothecary', 0),
('Space Marines', 'Apothecary Biologis', 0),
('Space Marines', 'Ancient', 0),
('Space Marines', 'Primaris Ancient', 0),
('Space Marines', 'Techmarine', 0),
('Space Marines', 'Master of the Forge', 0),
('Space Marines', 'Judiciar', 0),
('Space Marines', 'Bladeguard Ancient', 0),
('Space Marines', 'Intercessor Squad', 0),
('Space Marines', 'Assault Intercessor Squad', 0),
('Space Marines', 'Heavy Intercessor Squad', 0),
('Space Marines', 'Tactical Squad', 0),
('Space Marines', 'Scout Squad', 0),
('Space Marines', 'Infiltrator Squad', 0),
('Space Marines', 'Incursor Squad', 0),
('Space Marines', 'Eliminator Squad', 0),
('Space Marines', 'Reiver Squad', 0),
('Space Marines', 'Hellblaster Squad', 0),
('Space Marines', 'Eradicator Squad', 0),
('Space Marines', 'Inceptor Squad', 0),
('Space Marines', 'Sternguard Veteran Squad', 0),
('Space Marines', 'Vanguard Veteran Squad', 0),
('Space Marines', 'Bladeguard Veterans', 0),
('Space Marines', 'Aggressor Squad', 0),
('Space Marines', 'Suppressors', 0),
('Space Marines', 'Desolation Squad', 0),
('Space Marines', 'Infernus Squad', 0),
('Space Marines', 'Assault Squad', 0),
('Space Marines', 'Devastator Squad', 0),
('Space Marines', 'Company Heroes', 0),
('Space Marines', 'Veteran Intercessors', 0),
('Space Marines', 'Terminator Assault Squad', 0),
('Space Marines', 'Terminator Squad', 0),
('Space Marines', 'Tartaros Terminator Squad', 0),
('Space Marines', 'Cataphractii Terminator Squad', 0),
('Space Marines', 'Outrider Squad', 0),
('Space Marines', 'Attack Bike Squad', 0),
('Space Marines', 'Bike Squad', 0),
('Space Marines', 'Invader ATV', 0),
('Space Marines', 'Redemptor Dreadnought', 0),
('Space Marines', 'Brutalis Dreadnought', 0),
('Space Marines', 'Ballistus Dreadnought', 0),
('Space Marines', 'Ironclad Dreadnought', 0),
('Space Marines', 'Venerable Dreadnought', 0),
('Space Marines', 'Dreadnought', 0),
('Space Marines', 'Rhino', 0),
('Space Marines', 'Razorback', 0),
('Space Marines', 'Impulsor', 0),
('Space Marines', 'Repulsor', 0),
('Space Marines', 'Repulsor Executioner', 0),
('Space Marines', 'Drop Pod', 0),
('Space Marines', 'Gladiator Lancer', 0),
('Space Marines', 'Gladiator Reaper', 0),
('Space Marines', 'Gladiator Valiant', 0),
('Space Marines', 'Predator Annihilator', 0),
('Space Marines', 'Predator Destructor', 0),
('Space Marines', 'Vindicator', 0),
('Space Marines', 'Whirlwind', 0),
('Space Marines', 'Thunderfire Cannon', 0),
('Space Marines', 'Land Raider', 0),
('Space Marines', 'Land Raider Crusader', 0),
('Space Marines', 'Land Raider Redeemer', 0),
('Space Marines', 'Land Speeder', 0),
('Space Marines', 'Land Speeder Storm', 0),
('Space Marines', 'Land Speeder Tempest', 0),
('Space Marines', 'Storm Speeder Hailstrike', 0),
('Space Marines', 'Storm Speeder Hammerstrike', 0),
('Space Marines', 'Storm Speeder Thunderstrike', 0),
('Space Marines', 'Stormhawk Interceptor', 0),
('Space Marines', 'Stormtalon Gunship', 0),
('Space Marines', 'Stormraven Gunship', 0),
('Space Marines', 'Fire Raptor Gunship', 0),
('Blood Angels', 'Commander Dante', 0),
('Blood Angels', 'Mephiston', 0),
('Blood Angels', 'Tycho the Lost', 0),
('Blood Angels', 'Corbulo', 0),
('Blood Angels', 'Lemartes', 0),
('Blood Angels', 'The Sanguinor', 0),
('Blood Angels', 'Astorath', 0),
('Blood Angels', 'Sanguinary Priest', 0),
('Blood Angels', 'Death Company Chaplain', 0),
('Blood Angels', 'Captain with Jump Pack', 0),
('Blood Angels', 'Death Company Marines', 0),
('Blood Angels', 'Death Company Dreadnought', 0),
('Blood Angels', 'Sanguinary Guard', 0),
('Blood Angels', 'Sanguinary Ancient', 0),
('Blood Angels', 'Assault Intercessor Squad', 0),
('Blood Angels', 'Intercessor Squad', 0),
('Blood Angels', 'Baal Predator', 0),
('Blood Angels', 'Furioso Dreadnought', 0),
('Blood Angels', 'Librarian Dreadnought', 0),
('Dark Angels', 'Lion El''Jonson', 0),
('Dark Angels', 'Supreme Grand Master Azrael', 0),
('Dark Angels', 'Ezekiel', 0),
('Dark Angels', 'Asmodai', 0),
('Dark Angels', 'Belial', 0),
('Dark Angels', 'Sammael', 0),
('Dark Angels', 'Ravenwing Talonmaster', 0),
('Dark Angels', 'Deathwing Knights', 0),
('Dark Angels', 'Deathwing Terminator Squad', 0),
('Dark Angels', 'Deathwing Command Squad', 0),
('Dark Angels', 'Ravenwing Black Knights', 0),
('Dark Angels', 'Ravenwing Dark Talon', 0),
('Dark Angels', 'Ravenwing Nephilim Jetfighter', 0),
('Dark Angels', 'Ravenwing Bike Squad', 0),
('Dark Angels', 'Ravenwing Attack Bike', 0),
('Dark Angels', 'Intercessor Squad', 0),
('Dark Angels', 'Assault Intercessor Squad', 0),
('Space Wolves', 'Ragnar Blackmane', 0),
('Space Wolves', 'Bjorn the Fell-Handed', 0),
('Space Wolves', 'Logan Grimnar', 0),
('Space Wolves', 'Canis Wolfborn', 0),
('Space Wolves', 'Njal Stormcaller', 0),
('Space Wolves', 'Arjac Rockfist', 0),
('Space Wolves', 'Ulrik the Slayer', 0),
('Space Wolves', 'Lukas the Trickster', 0),
('Space Wolves', 'Wolf Lord', 0),
('Space Wolves', 'Iron Priest', 0),
('Space Wolves', 'Rune Priest', 0),
('Space Wolves', 'Wolf Guard Battle Leader', 0),
('Space Wolves', 'Wolf Guard Terminators', 0),
('Space Wolves', 'Wolf Guard Pack', 0),
('Space Wolves', 'Blood Claws', 0),
('Space Wolves', 'Grey Hunters', 0),
('Space Wolves', 'Long Fangs', 0),
('Space Wolves', 'Skyclaws', 0),
('Space Wolves', 'Swift Claws', 0),
('Space Wolves', 'Thunderwolf Cavalry', 0),
('Space Wolves', 'Wulfen', 0),
('Space Wolves', 'Fenrisian Wolves', 0),
('Space Wolves', 'Hounds of Morkai', 0),
('Space Wolves', 'Cyberwolf', 0),
('Space Wolves', 'Land Speeder Vengeance', 0),
('Space Wolves', 'Intercessor Squad', 0),
('Space Wolves', 'Assault Intercessor Squad', 0),
('Black Templars', 'High Marshal Helbrecht', 0),
('Black Templars', 'The Emperor''s Champion', 0),
('Black Templars', 'Marshall', 0),
('Black Templars', 'Castellan', 0),
('Black Templars', 'Primaris Chaplain on Bike', 0),
('Black Templars', 'Chaplain', 0),
('Black Templars', 'Sword Brethren', 0),
('Black Templars', 'Neophyte Squads', 0),
('Black Templars', 'Initiate Squad', 0),
('Black Templars', 'Crusader Squad', 0),
('Black Templars', 'Assault Intercessor Squad', 0),
('Black Templars', 'Intercessor Squad', 0),
('Black Templars', 'Primaris Crusader Squad', 0),
('Black Templars', 'Black Templars Primaris Neophytes', 0),
('Black Templars', 'Repulsor', 0),
('Black Templars', 'Repulsor Executioner', 0),
('Black Templars', 'Land Raider Crusader', 0),
('Deathwatch', 'Watch Master', 0),
('Deathwatch', 'Watch Captain', 0),
('Deathwatch', 'Watch Captain in Terminator Armour', 0),
('Deathwatch', 'Librarian', 0),
('Deathwatch', 'Chaplain', 0),
('Deathwatch', 'Kill Team', 0),
('Deathwatch', 'Veteran Squad', 0),
('Deathwatch', 'Vanguard Veteran Squad', 0),
('Deathwatch', 'Terminator Squad', 0),
('Deathwatch', 'Dreadnought', 0),
('Deathwatch', 'Venerable Dreadnought', 0),
('Deathwatch', 'Intercessor Squad', 0),
('Deathwatch', 'Assault Intercessor Squad', 0),
('Deathwatch', 'Corvus Blackstar', 0),
('Deathwatch', 'Repulsor', 0),
('Deathwatch', 'Land Raider', 0),
('Grey Knights', 'Supreme Grand Master Kaldor Draigo', 0),
('Grey Knights', 'Brother-Captain', 0),
('Grey Knights', 'Grand Master in Nemesis Dreadknight', 0),
('Grey Knights', 'Grand Master', 0),
('Grey Knights', 'Brotherhood Champion', 0),
('Grey Knights', 'Brother-Captain in Terminator Armour', 0),
('Grey Knights', 'Brotherhood Librarian', 0),
('Grey Knights', 'Brotherhood Chaplain', 0),
('Grey Knights', 'Brotherhood Apothecary', 0),
('Grey Knights', 'Brotherhood Ancient', 0),
('Grey Knights', 'Paladin Squad', 0),
('Grey Knights', 'Paladin Ancient', 0),
('Grey Knights', 'Paladins', 0),
('Grey Knights', 'Strike Squad', 0),
('Grey Knights', 'Purgation Squad', 0),
('Grey Knights', 'Purifier Squad', 0),
('Grey Knights', 'Interceptor Squad', 0),
('Grey Knights', 'Terminator Squad', 0),
('Grey Knights', 'Justicar', 0),
('Grey Knights', 'Nemesis Dreadknight', 0),
('Grey Knights', 'Dreadnought', 0),
('Grey Knights', 'Venerable Dreadnought', 0),
('Grey Knights', 'Stormraven Gunship', 0),
('Grey Knights', 'Rhino', 0),
('Grey Knights', 'Razorback', 0),
('Ultramarines', 'Marneus Calgar', 0),
('Ultramarines', 'Roboute Guilliman', 0),
('Ultramarines', 'Tigurius', 0),
('Ultramarines', 'Uriel Ventris', 0),
('Ultramarines', 'Sicarius', 0),
('Ultramarines', 'Chronus', 0),
('Ultramarines', 'Antaro Chronus', 0),
('Ultramarines', 'Victrix Guard', 0),
('Ultramarines', 'Honour Guard', 0),
('Ultramarines', 'Intercessor Squad', 0),
('Ultramarines', 'Assault Intercessor Squad', 0),
('Imperial Fists', 'Darnath Lysander', 0),
('Imperial Fists', 'Intercessor Squad', 0),
('Imperial Fists', 'Assault Intercessor Squad', 0),
('Imperial Fists', 'Fists Exemplar Breacher Squad', 0),
('Iron Hands', 'Kardan Stronos', 0),
('Iron Hands', 'Iron Father Feirros', 0),
('Iron Hands', 'Intercessor Squad', 0),
('Iron Hands', 'Assault Intercessor Squad', 0),
('Raven Guard', 'Kayvaan Shrike', 0),
('Raven Guard', 'Corvus Corax', 0),
('Raven Guard', 'Intercessor Squad', 0),
('Raven Guard', 'Assault Intercessor Squad', 0),
('Raven Guard', 'Vanguard Veteran Squad', 0),
('Raven Guard', 'Scout Squad', 0),
('Salamanders', 'Tu''Shan', 0),
('Salamanders', 'Vulkan He''stan', 0),
('Salamanders', 'Intercessor Squad', 0),
('Salamanders', 'Assault Intercessor Squad', 0),
('Salamanders', 'Aggressor Squad', 0),
('Salamanders', 'Eradicator Squad', 0),
('White Scars', 'Kor''sarro Khan', 0),
('White Scars', 'Outrider Squad', 0),
('White Scars', 'Bike Squad', 0),
('White Scars', 'Attack Bike Squad', 0),
('White Scars', 'Intercessor Squad', 0),
('White Scars', 'Assault Intercessor Squad', 0),
('Astra Militarum', 'Lord Solar Leontus', 0),
('Astra Militarum', 'Ursula Creed', 0),
('Astra Militarum', 'Commander Pask', 0),
('Astra Militarum', 'Company Commander', 0),
('Astra Militarum', 'Platoon Commander', 0),
('Astra Militarum', 'Lord Commissar', 0),
('Astra Militarum', 'Commissar', 0),
('Astra Militarum', 'Primaris Psyker', 0),
('Astra Militarum', 'Tech-Priest Enginseer', 0),
('Astra Militarum', 'Militarum Tempestus Command Squad', 0),
('Astra Militarum', 'Regimental Preacher', 0),
('Astra Militarum', 'Colour Sergeant Kell', 0),
('Astra Militarum', 'Gaunts Ghosts', 0),
('Astra Militarum', 'Tank Commander', 0),
('Astra Militarum', 'Infantry Squad', 0),
('Astra Militarum', 'Cadian Shock Troops', 0),
('Astra Militarum', 'Catachan Jungle Fighters', 0),
('Astra Militarum', 'Militarum Tempestus Scions', 0),
('Astra Militarum', 'Veteran Squad', 0),
('Astra Militarum', 'Command Squad', 0),
('Astra Militarum', 'Conscripts', 0),
('Astra Militarum', 'Ratlings', 0),
('Astra Militarum', 'Bullgryns', 0),
('Astra Militarum', 'Ogryns', 0),
('Astra Militarum', 'Ogryn Bodyguard', 0),
('Astra Militarum', 'Rough Riders', 0),
('Astra Militarum', 'Nork Deddog', 0),
('Astra Militarum', 'Heavy Weapons Squad', 0),
('Astra Militarum', 'Special Weapons Squad', 0),
('Astra Militarum', 'Sentinel', 0),
('Astra Militarum', 'Armoured Sentinel', 0),
('Astra Militarum', 'Scout Sentinel', 0),
('Astra Militarum', 'Chimera', 0),
('Astra Militarum', 'Taurox', 0),
('Astra Militarum', 'Taurox Prime', 0),
('Astra Militarum', 'Hellhound', 0),
('Astra Militarum', 'Bane Wolf', 0),
('Astra Militarum', 'Devil Dog', 0),
('Astra Militarum', 'Leman Russ Battle Tank', 0),
('Astra Militarum', 'Leman Russ Demolisher', 0),
('Astra Militarum', 'Leman Russ Punisher', 0),
('Astra Militarum', 'Leman Russ Vanquisher', 0),
('Astra Militarum', 'Leman Russ Executioner', 0),
('Astra Militarum', 'Leman Russ Exterminator', 0),
('Astra Militarum', 'Leman Russ Eradicator', 0),
('Astra Militarum', 'Leman Russ Thunderer', 0),
('Astra Militarum', 'Basilisk', 0),
('Astra Militarum', 'Wyvern', 0),
('Astra Militarum', 'Hydra', 0),
('Astra Militarum', 'Manticore', 0),
('Astra Militarum', 'Deathstrike', 0),
('Astra Militarum', 'Baneblade', 0),
('Astra Militarum', 'Shadowsword', 0),
('Astra Militarum', 'Stormsword', 0),
('Astra Militarum', 'Stormblade', 0),
('Astra Militarum', 'Hellhammer', 0),
('Astra Militarum', 'Banehammer', 0),
('Astra Militarum', 'Doomhammer', 0),
('Astra Militarum', 'Valkyrie', 0),
('Astra Militarum', 'Vendetta', 0),
('Adepta Sororitas', 'Celestine', 0),
('Adepta Sororitas', 'Morvenn Vahl', 0),
('Adepta Sororitas', 'Saint Celestine', 0),
('Adepta Sororitas', 'Canoness', 0),
('Adepta Sororitas', 'Junith Eruita', 0),
('Adepta Sororitas', 'Ephrael Stern', 0),
('Adepta Sororitas', 'Uriah Jacobus', 0),
('Adepta Sororitas', 'Sister Dogmata', 0),
('Adepta Sororitas', 'Missionary', 0),
('Adepta Sororitas', 'Hospitaller', 0),
('Adepta Sororitas', 'Imagifier', 0),
('Adepta Sororitas', 'Palatine', 0),
('Adepta Sororitas', 'Dialogus', 0),
('Adepta Sororitas', 'Battle Sisters Squad', 0),
('Adepta Sororitas', 'Celestian Sacresants', 0),
('Adepta Sororitas', 'Sisters Repentia', 0),
('Adepta Sororitas', 'Repentia Superior', 0),
('Adepta Sororitas', 'Arco-flagellants', 0),
('Adepta Sororitas', 'Crusaders', 0),
('Adepta Sororitas', 'Death Cult Assassins', 0),
('Adepta Sororitas', 'Celestian Squad', 0),
('Adepta Sororitas', 'Dominion Squad', 0),
('Adepta Sororitas', 'Retributor Squad', 0),
('Adepta Sororitas', 'Zephyrim Squad', 0),
('Adepta Sororitas', 'Seraphim Squad', 0),
('Adepta Sororitas', 'Novitiates', 0),
('Adepta Sororitas', 'Penitent Engines', 0),
('Adepta Sororitas', 'Mortifiers', 0),
('Adepta Sororitas', 'Castigator', 0),
('Adepta Sororitas', 'Immolator', 0),
('Adepta Sororitas', 'Rhino', 0),
('Adepta Sororitas', 'Exorcist', 0),
('Adepta Sororitas', 'Exorcist Domine', 0),
('Adepta Sororitas', 'Paragon Warsuits', 0),
('Adepta Sororitas', 'Sister Dogmata', 0),
('Adeptus Custodes', 'Trajann Valoris', 0),
('Adeptus Custodes', 'Shield-Captain', 0),
('Adeptus Custodes', 'Shield-Captain in Allarus Terminator Armour', 0),
('Adeptus Custodes', 'Shield-Captain on Dawneagle Jetbike', 0),
('Adeptus Custodes', 'Valdor', 0),
('Adeptus Custodes', 'Blade Champion', 0),
('Adeptus Custodes', 'Vexilus Praetor', 0),
('Adeptus Custodes', 'Vexilus Praetor in Allarus Terminator Armour', 0),
('Adeptus Custodes', 'Custodian Warden', 0),
('Adeptus Custodes', 'Sister of Silence Prosecutor', 0),
('Adeptus Custodes', 'Custodian Guard Squad', 0),
('Adeptus Custodes', 'Custodian Warden Squad', 0),
('Adeptus Custodes', 'Allarus Custodians', 0),
('Adeptus Custodes', 'Aquilan Shield', 0),
('Adeptus Custodes', 'Prosecutors', 0),
('Adeptus Custodes', 'Vigilators', 0),
('Adeptus Custodes', 'Witchseekers', 0),
('Adeptus Custodes', 'Knight-Centura', 0),
('Adeptus Custodes', 'Venerable Land Raider', 0),
('Adeptus Custodes', 'Grav-Rhino', 0),
('Adeptus Custodes', 'Dawneagle Jetbike Squadron', 0),
('Adeptus Custodes', 'Vertus Praetors', 0),
('Adeptus Custodes', 'Caladius Grav-Tank', 0),
('Adeptus Custodes', 'Pallas Grav-Attack', 0),
('Adeptus Custodes', 'Coronus Grav-Carrier', 0),
('Adeptus Custodes', 'Telemon Heavy Dreadnought', 0),
('Adeptus Custodes', 'Contemptor-Galatus Dreadnought', 0),
('Adeptus Custodes', 'Contemptor-Achillus Dreadnought', 0),
('Adeptus Mechanicus', 'Belisarius Cawl', 0),
('Adeptus Mechanicus', 'Tech-Priest Dominus', 0),
('Adeptus Mechanicus', 'Tech-Priest Manipulus', 0),
('Adeptus Mechanicus', 'Tech-Priest Enginseer', 0),
('Adeptus Mechanicus', 'Technoarcheologist', 0),
('Adeptus Mechanicus', 'Cybernetica Datasmith', 0),
('Adeptus Mechanicus', 'Tech-Priest Manipulus', 0),
('Adeptus Mechanicus', 'Skitarii Marshal', 0),
('Adeptus Mechanicus', 'Skitarii Rangers', 0),
('Adeptus Mechanicus', 'Skitarii Vanguard', 0),
('Adeptus Mechanicus', 'Sicarian Ruststalkers', 0),
('Adeptus Mechanicus', 'Sicarian Infiltrators', 0),
('Adeptus Mechanicus', 'Corpuscarii Electro-Priests', 0),
('Adeptus Mechanicus', 'Fulgurite Electro-Priests', 0),
('Adeptus Mechanicus', 'Pteraxii Sterylizors', 0),
('Adeptus Mechanicus', 'Pteraxii Skystalkers', 0),
('Adeptus Mechanicus', 'Serberys Raiders', 0),
('Adeptus Mechanicus', 'Serberys Sulphurhounds', 0),
('Adeptus Mechanicus', 'Ironstrider Ballistarii', 0),
('Adeptus Mechanicus', 'Sydonian Dragoons', 0),
('Adeptus Mechanicus', 'Onager Dunecrawler', 0),
('Adeptus Mechanicus', 'Kastelan Robots', 0),
('Adeptus Mechanicus', 'Cognis Manipulus', 0),
('Adeptus Mechanicus', 'Skorpius Disintegrator', 0),
('Adeptus Mechanicus', 'Skorpius Dunerider', 0),
('Adeptus Mechanicus', 'Archaeopter Fusilave', 0),
('Adeptus Mechanicus', 'Archaeopter Stratoraptor', 0),
('Adeptus Mechanicus', 'Archaeopter Transvector', 0),
('Adeptus Mechanicus', 'Dunerider', 0),
('Adeptus Mechanicus', 'Ballistarii', 0),
('Adeptus Mechanicus', 'Ironstrider', 0),
('Imperial Knights', 'Knight Paladin', 0),
('Imperial Knights', 'Knight Errant', 0),
('Imperial Knights', 'Knight Crusader', 0),
('Imperial Knights', 'Knight Gallant', 0),
('Imperial Knights', 'Knight Warden', 0),
('Imperial Knights', 'Knight Preceptor', 0),
('Imperial Knights', 'Knight Acheron', 0),
('Imperial Knights', 'Knight Castigator', 0),
('Imperial Knights', 'Knight Styrix', 0),
('Imperial Knights', 'Knight Magaera', 0),
('Imperial Knights', 'Knight Moirax', 0),
('Imperial Knights', 'Armiger Warglaive', 0),
('Imperial Knights', 'Armiger Helverin', 0),
('Imperial Knights', 'Canis Rex', 0),
('Imperial Knights', 'Freeblade', 0),
('Imperial Knights', 'Cerastus Knight-Lancer', 0),
('Imperial Knights', 'Cerastus Knight-Castigator', 0),
('Imperial Knights', 'Acastus Knight Porphyrion', 0),
('Imperial Knights', 'Acastus Knight Asterius', 0),
('Agents of the Imperium', 'Inquisitor', 0),
('Agents of the Imperium', 'Inquisitor in Terminator Armour', 0),
('Agents of the Imperium', 'Inquisitor on Bike', 0),
('Agents of the Imperium', 'Kyria Draxus', 0),
('Agents of the Imperium', 'Greyfax', 0),
('Agents of the Imperium', 'Vindicare Assassin', 0),
('Agents of the Imperium', 'Callidus Assassin', 0),
('Agents of the Imperium', 'Culexis Assassin', 0),
('Agents of the Imperium', 'Eversor Assassin', 0),
('Agents of the Imperium', 'Officio Assassinorum', 0),
('Agents of the Imperium', 'Celestine & Geminae Superia', 0),
('Agents of the Imperium', 'Lord Inquisitor Kyria Draxus', 0),
('Agents of the Imperium', 'Militarum Tempestus Scions', 0),
('Agents of the Imperium', 'Tempestus Command Squad', 0),
('Agents of the Imperium', 'Space Marine Heroes', 0),
('Chaos Space Marines', 'Abaddon the Despoiler', 0),
('Chaos Space Marines', 'Haarken Worldclaimer', 0),
('Chaos Space Marines', 'Lucius the Eternal', 0),
('Chaos Space Marines', 'Chaos Lord', 0),
('Chaos Space Marines', 'Chaos Lord in Terminator Armour', 0),
('Chaos Space Marines', 'Chaos Lord on Bike', 0),
('Chaos Space Marines', 'Sorcerer', 0),
('Chaos Space Marines', 'Sorcerer in Terminator Armour', 0),
('Chaos Space Marines', 'Dark Apostle', 0),
('Chaos Space Marines', 'Master of Executions', 0),
('Chaos Space Marines', 'Master of Possession', 0),
('Chaos Space Marines', 'Warpsmith', 0),
('Chaos Space Marines', 'Chaos Sorcerer', 0),
('Chaos Space Marines', 'Chaos Space Marines', 0),
('Chaos Space Marines', 'Legionaries', 0),
('Chaos Space Marines', 'Cultists', 0),
('Chaos Space Marines', 'Cultist Mob', 0),
('Chaos Space Marines', 'Accursed Cultists', 0),
('Chaos Space Marines', 'Chaos Terminators', 0),
('Chaos Space Marines', 'Chosen', 0),
('Chaos Space Marines', 'Possessed', 0),
('Chaos Space Marines', 'Chaos Spawn', 0),
('Chaos Space Marines', 'Mutilators', 0),
('Chaos Space Marines', 'Obliterators', 0),
('Chaos Space Marines', 'Raptors', 0),
('Chaos Space Marines', 'Warp Talons', 0),
('Chaos Space Marines', 'Bikers', 0),
('Chaos Space Marines', 'Havocs', 0),
('Chaos Space Marines', 'Chaos Predator', 0),
('Chaos Space Marines', 'Vindicator', 0),
('Chaos Space Marines', 'Land Raider', 0),
('Chaos Space Marines', 'Defiler', 0),
('Chaos Space Marines', 'Maulerfiend', 0),
('Chaos Space Marines', 'Forgefiend', 0),
('Chaos Space Marines', 'Venomcrawler', 0),
('Chaos Space Marines', 'Heldrake', 0),
('Chaos Space Marines', 'Helbrute', 0),
('Chaos Space Marines', 'Daemon Prince', 0),
('Chaos Space Marines', 'Daemon Prince with Wings', 0),
('Chaos Space Marines', 'Rhino', 0),
('Chaos Space Marines', 'Predator Annihilator', 0),
('Chaos Space Marines', 'Predator Destructor', 0),
('Chaos Space Marines', 'Chaos Land Raider', 0),
('Chaos Space Marines', 'Chaos Rhino', 0),
('Chaos Space Marines', 'Chaos Vindicator', 0),
('Chaos Space Marines', 'Chaos Sicaran Battle Tank', 0),
('World Eaters', 'Angron', 0),
('World Eaters', 'Kharn the Betrayer', 0),
('World Eaters', 'World Eaters Lord', 0),
('World Eaters', 'Lord on Juggernaut', 0),
('World Eaters', 'Master of Executions', 0),
('World Eaters', 'Chaos Lord', 0),
('World Eaters', 'Jakhals', 0),
('World Eaters', 'Berzerkers', 0),
('World Eaters', 'Exalted Eightbound', 0),
('World Eaters', 'Eightbound', 0),
('World Eaters', 'World Eaters Spawn', 0),
('World Eaters', 'World Eaters Daemon Prince', 0),
('World Eaters', 'Terminators', 0),
('World Eaters', 'Helbrute', 0),
('World Eaters', 'Rhino', 0),
('World Eaters', 'Land Raider', 0),
('World Eaters', 'Defiler', 0),
('World Eaters', 'Maulerfiend', 0),
('World Eaters', 'Skull Altar', 0),
('Death Guard', 'Mortarion', 0),
('Death Guard', 'Typhus', 0),
('Death Guard', 'Chaos Lord of Nurgle', 0),
('Death Guard', 'Death Guard Chaos Lord', 0),
('Death Guard', 'Malignant Plaguecaster', 0),
('Death Guard', 'Plague Surgeon', 0),
('Death Guard', 'Foul Blightspawn', 0),
('Death Guard', 'Noxious Blightbringer', 0),
('Death Guard', 'Lord of Virulence', 0),
('Death Guard', 'Lord of Contagion', 0),
('Death Guard', 'Biologus Putrifier', 0),
('Death Guard', 'Tallyman', 0),
('Death Guard', 'Plague Marines', 0),
('Death Guard', 'Poxwalkers', 0),
('Death Guard', 'Cultists of Nurgle', 0),
('Death Guard', 'Blightlord Terminators', 0),
('Death Guard', 'Deathshroud Bodyguard', 0),
('Death Guard', 'Myphitic Blight-Haulers', 0),
('Death Guard', 'Foetid Bloat-Drones', 0),
('Death Guard', 'Plagueburst Crawlers', 0),
('Death Guard', 'Bloat-Drone', 0),
('Death Guard', 'Helbrute', 0),
('Death Guard', 'Chaos Spawn', 0),
('Death Guard', 'Rhino', 0),
('Death Guard', 'Predator', 0),
('Death Guard', 'Daemon Prince of Nurgle', 0),
('Death Guard', 'Daemon of Nurgle', 0),
('Thousand Sons', 'Magnus the Red', 0),
('Thousand Sons', 'Ahzek Ahriman', 0),
('Thousand Sons', 'Exalted Sorcerer', 0),
('Thousand Sons', 'Sorcerer', 0),
('Thousand Sons', 'Infernal Master', 0),
('Thousand Sons', 'Sorcerer in Terminator Armour', 0),
('Thousand Sons', 'Rubric Marines', 0),
('Thousand Sons', 'Scarab Occult Terminators', 0),
('Thousand Sons', 'Tzaangors', 0),
('Thousand Sons', 'Tzaangor Enlightened', 0),
('Thousand Sons', 'Tzaangor Shaman', 0),
('Thousand Sons', 'Mutalith Vortex Beast', 0),
('Thousand Sons', 'Chaos Spawn', 0),
('Thousand Sons', 'Helbrute', 0),
('Thousand Sons', 'Daemon Prince of Tzeentch', 0),
('Thousand Sons', 'Rhino', 0),
('Emperor''s Children', 'Fulgrim', 0),
('Emperor''s Children', 'Lucius the Eternal', 0),
('Emperor''s Children', 'Lord of Pain', 0),
('Emperor''s Children', 'Chaos Lord', 0),
('Emperor''s Children', 'Sorcerer', 0),
('Emperor''s Children', 'Noise Marines', 0),
('Emperor''s Children', 'Chaos Space Marines', 0),
('Emperor''s Children', 'Cultists', 0),
('Emperor''s Children', 'Terminators', 0),
('Emperor''s Children', 'Possessed', 0),
('Emperor''s Children', 'Raptors', 0),
('Emperor''s Children', 'Chaos Spawn', 0),
('Emperor''s Children', 'Daemon Prince', 0),
('Emperor''s Children', 'Rhino', 0),
('Emperor''s Children', 'Helbrute', 0),
('Emperor''s Children', 'Predator', 0),
('Chaos Daemons', 'Skarbrand', 0),
('Chaos Daemons', 'Bloodthirster', 0),
('Chaos Daemons', 'Skulltaker', 0),
('Chaos Daemons', 'Bloodmaster', 0),
('Chaos Daemons', 'Skullmaster', 0),
('Chaos Daemons', 'Karanak', 0),
('Chaos Daemons', 'Bloodletters', 0),
('Chaos Daemons', 'Flesh Hounds', 0),
('Chaos Daemons', 'Bloodcrushers', 0),
('Chaos Daemons', 'Skull Cannon', 0),
('Chaos Daemons', 'Blood Throne', 0),
('Chaos Daemons', 'Burning Chariot of Khorne', 0),
('Chaos Daemons', 'Kairos Fateweaver', 0),
('Chaos Daemons', 'Lord of Change', 0),
('Chaos Daemons', 'Changecaster', 0),
('Chaos Daemons', 'Fluxmaster', 0),
('Chaos Daemons', 'Fateskimmer', 0),
('Chaos Daemons', 'Pink Horrors', 0),
('Chaos Daemons', 'Blue Horrors', 0),
('Chaos Daemons', 'Brimstone Horrors', 0),
('Chaos Daemons', 'Flamers', 0),
('Chaos Daemons', 'Screamers', 0),
('Chaos Daemons', 'Exalted Flamer', 0),
('Chaos Daemons', 'Burning Chariot of Tzeentch', 0),
('Chaos Daemons', 'Rotigus', 0),
('Chaos Daemons', 'Great Unclean One', 0),
('Chaos Daemons', 'Poxbringer', 0),
('Chaos Daemons', 'Sloppity Bilepiper', 0),
('Chaos Daemons', 'Spoilpox Scrivener', 0),
('Chaos Daemons', 'Epidemius', 0),
('Chaos Daemons', 'Plaguebearers', 0),
('Chaos Daemons', 'Nurglings', 0),
('Chaos Daemons', 'Beasts of Nurgle', 0),
('Chaos Daemons', 'Rot Fly', 0),
('Chaos Daemons', 'Plague Drones', 0),
('Chaos Daemons', 'The Masque', 0),
('Chaos Daemons', 'Keeper of Secrets', 0),
('Chaos Daemons', 'Infernal Enrapturess', 0),
('Chaos Daemons', 'Shalaxi Helbane', 0),
('Chaos Daemons', 'Syll''Esske', 0),
('Chaos Daemons', 'Daemonettes', 0),
('Chaos Daemons', 'Seekers', 0),
('Chaos Daemons', 'Fiends', 0),
('Chaos Daemons', 'Seeker Chariot', 0),
('Chaos Daemons', 'Hellflayer', 0),
('Chaos Daemons', 'Exalted Seeker Chariot', 0),
('Chaos Daemons', 'Be''lakor', 0),
('Chaos Daemons', 'Daemon Prince', 0),
('Chaos Knights', 'Vashtorr the Arkifane', 0),
('Chaos Knights', 'War Dog Executioner', 0),
('Chaos Knights', 'War Dog Brigand', 0),
('Chaos Knights', 'War Dog Karnivore', 0),
('Chaos Knights', 'War Dog Huntsman', 0),
('Chaos Knights', 'War Dog Stalker', 0),
('Chaos Knights', 'Knight Abominant', 0),
('Chaos Knights', 'Knight Rampager', 0),
('Chaos Knights', 'Knight Despoiler', 0),
('Chaos Knights', 'Knight Tyrant', 0),
('Chaos Knights', 'Knight Desecrator', 0),
('Chaos Knights', 'Chaos Knight', 0),
('Aeldari', 'Eldrad Ulthran', 0),
('Aeldari', 'Yvraine', 0),
('Aeldari', 'The Visarch', 0),
('Aeldari', 'The Yncarne', 0),
('Aeldari', 'Farseer', 0),
('Aeldari', 'Autarch', 0),
('Aeldari', 'Autarch Skyrunner', 0),
('Aeldari', 'Autarch on Foot', 0),
('Aeldari', 'Warlock', 0),
('Aeldari', 'Spiritseer', 0),
('Aeldari', 'Avatar of Khaine', 0),
('Aeldari', 'Dire Avengers', 0),
('Aeldari', 'Fire Dragons', 0),
('Aeldari', 'Howling Banshees', 0),
('Aeldari', 'Striking Scorpions', 0),
('Aeldari', 'Dark Reapers', 0),
('Aeldari', 'Warp Spiders', 0),
('Aeldari', 'Swooping Hawks', 0),
('Aeldari', 'Shining Spears', 0),
('Aeldari', 'Crimson Hunters', 0),
('Aeldari', 'Crimson Hunter Exarch', 0),
('Aeldari', 'Guardians Defender Squad', 0),
('Aeldari', 'Storm Guardian Squad', 0),
('Aeldari', 'Rangers', 0),
('Aeldari', 'Wraithguard', 0),
('Aeldari', 'Wraithblades', 0),
('Aeldari', 'Wraithlord', 0),
('Aeldari', 'Fire Prism', 0),
('Aeldari', 'Night Spinner', 0),
('Aeldari', 'War Walker', 0),
('Aeldari', 'Falcon', 0),
('Aeldari', 'Wave Serpent', 0),
('Aeldari', 'Vyper Squadron', 0),
('Aeldari', 'Hemlock Wraithfighter', 0),
('Aeldari', 'Wraithknight', 0),
('Aeldari', 'Revenant Titan', 0),
('Aeldari', 'Troupe Master', 0),
('Aeldari', 'Shadowseer', 0),
('Aeldari', 'Death Jester', 0),
('Aeldari', 'Solitaire', 0),
('Aeldari', 'Troupe', 0),
('Aeldari', 'Skyweavers', 0),
('Aeldari', 'Starweavers', 0),
('Aeldari', 'Voidweavers', 0),
('Aeldari', 'Spiritseer', 0),
('Aeldari', 'Yvraine', 0),
('Aeldari', 'The Visarch', 0),
('Aeldari', 'The Yncarne', 0),
('Drukhari', 'Supreme Overlord Asdrubael Vect', 0),
('Drukhari', 'Archon', 0),
('Drukhari', 'Haemonculus', 0),
('Drukhari', 'Succubus', 0),
('Drukhari', 'Beastmaster', 0),
('Drukhari', 'Lhamean', 0),
('Drukhari', 'Ur-Ghul', 0),
('Drukhari', 'Medusae', 0),
('Drukhari', 'Sslyth', 0),
('Drukhari', 'Kabalite Warriors', 0),
('Drukhari', 'Kabalite Trueborn', 0),
('Drukhari', 'Sybarites', 0),
('Drukhari', 'Wyches', 0),
('Drukhari', 'Bloodbride', 0),
('Drukhari', 'Hekatrix', 0),
('Drukhari', 'Hekatrix Bloodbrides', 0),
('Drukhari', 'Hellions', 0),
('Drukhari', 'Reavers', 0),
('Drukhari', 'Shardnets', 0),
('Drukhari', 'Wracks', 0),
('Drukhari', 'Grotesques', 0),
('Drukhari', 'Talos Pain Engine', 0),
('Drukhari', 'Cronos Parasite Engine', 0),
('Drukhari', 'Ravager', 0),
('Drukhari', 'Venom', 0),
('Drukhari', 'Raider', 0),
('Drukhari', 'Kabalite Warrior', 0),
('Drukhari', 'Scourges', 0),
('Drukhari', 'Razorwing Jetfighter', 0),
('Drukhari', 'Voidraven Bomber', 0),
('Orks', 'Ghazghkull Thraka', 0),
('Orks', 'Makari', 0),
('Orks', 'Zodgrod Wortsnagga', 0),
('Orks', 'Boss Snikrot', 0),
('Orks', 'Boss Zagstruk', 0),
('Orks', 'Mad Dok Grotsnik', 0),
('Orks', 'Warboss', 0),
('Orks', 'Warboss on Warbike', 0),
('Orks', 'Painboy', 0),
('Orks', 'Weirdboy', 0),
('Orks', 'Wurrboy', 0),
('Orks', 'Big Mek', 0),
('Orks', 'Big Mek in Mega Armour', 0),
('Orks', 'Mek', 0),
('Orks', 'Mek with Shokk Attack Gun', 0),
('Orks', 'Nob on Smasha Squig', 0),
('Orks', 'Mozrog Skragbad', 0),
('Orks', 'Boyz', 0),
('Orks', 'Gretchin', 0),
('Orks', 'Beast Snagga Boyz', 0),
('Orks', 'Nobz', 0),
('Orks', 'Nobz on Warbikes', 0),
('Orks', 'Kommandos', 0),
('Orks', 'Meganobz', 0),
('Orks', 'Flash Gitz', 0),
('Orks', 'Burna Boyz', 0),
('Orks', 'Tankbustas', 0),
('Orks', 'Lootas', 0),
('Orks', 'Storm Boyz', 0),
('Orks', 'Stormboyz', 0),
('Orks', 'Deff Dread', 0),
('Orks', 'Killa Kans', 0),
('Orks', 'Gorkanaut', 0),
('Orks', 'Morkanaut', 0),
('Orks', 'Painbringers', 0),
('Orks', 'Squighog Boyz', 0),
('Orks', 'Nob on Smasha Squig', 0),
('Orks', 'Battlewagon', 0),
('Orks', 'Trukk', 0),
('Orks', 'Warbikers', 0),
('Orks', 'Warbikes', 0),
('Orks', 'Deffkoptas', 0),
('Orks', 'Bonebreaka', 0),
('Orks', 'Bonecrunchas', 0),
('Orks', 'Gunwagon', 0),
('Orks', 'Looted Wagon', 0),
('Orks', 'Mek Gunz', 0),
('Orks', 'Smasha Gun', 0),
('Orks', 'Traktor Kannon', 0),
('Orks', 'Kustom Mega-Kannon', 0),
('Orks', 'Dakkajet', 0),
('Orks', 'Burna-Bommer', 0),
('Orks', 'Blitza-Bommer', 0),
('Orks', 'Wazbom Blastajet', 0),
('Necrons', 'The Szarekhan Dynasty', 0),
('Necrons', 'Szarekh The Silent King', 0),
('Necrons', 'Imotekh the Stormlord', 0),
('Necrons', 'Illuminor Szeras', 0),
('Necrons', 'Trazyn the Infinite', 0),
('Necrons', 'Orikan the Diviner', 0),
('Necrons', 'Nemesor Zahndrekh', 0),
('Necrons', 'Vargard Obyron', 0),
('Necrons', 'Overlord', 0),
('Necrons', 'Overlord with Translocation Shroud', 0),
('Necrons', 'Royal Warden', 0),
('Necrons', 'Cryptek', 0),
('Necrons', 'Psychomancer', 0),
('Necrons', 'Technomancer', 0),
('Necrons', 'Plasmancer', 0),
('Necrons', 'Chronomancer', 0),
('Necrons', 'Lord', 0),
('Necrons', 'Lokhust Lord', 0),
('Necrons', 'Skorpekh Lord', 0),
('Necrons', 'Necron Warriors', 0),
('Necrons', 'Immortals', 0),
('Necrons', 'Triarch Praetorians', 0),
('Necrons', 'Triarch Stalker', 0),
('Necrons', 'Deathmarks', 0),
('Necrons', 'Lychguard', 0),
('Necrons', 'Flayed Ones', 0),
('Necrons', 'Wraiths', 0),
('Necrons', 'Tomb Blades', 0),
('Necrons', 'Destroyers', 0),
('Necrons', 'Heavy Destroyers', 0),
('Necrons', 'Lokhust Destroyers', 0),
('Necrons', 'Lokhust Heavy Destroyers', 0),
('Necrons', 'Skorpekh Destroyers', 0),
('Necrons', 'Ophydian Destroyers', 0),
('Necrons', 'Canoptek Scarabs', 0),
('Necrons', 'Canoptek Spyders', 0),
('Necrons', 'Canoptek Wraiths', 0),
('Necrons', 'Canoptek Acanthrites', 0),
('Necrons', 'Canoptek Reanimator', 0),
('Necrons', 'C''tan Shard of the Deceiver', 0),
('Necrons', 'C''tan Shard of the Nightbringer', 0),
('Necrons', 'C''tan Shard of the Void Dragon', 0),
('Necrons', 'C''tan Shard of the Mephet''ran', 0),
('Necrons', 'Annihilation Barge', 0),
('Necrons', 'Catacomb Command Barge', 0),
('Necrons', 'Doomsday Ark', 0),
('Necrons', 'Ghost Ark', 0),
('Necrons', 'Doomsday Ark', 0),
('Necrons', 'Tesseract Ark', 0),
('Necrons', 'Night Scythe', 0),
('Necrons', 'Doom Scythe', 0),
('Necrons', 'Monolith', 0),
('Necrons', 'Obelisk', 0),
('Necrons', 'Tesseract Vault', 0),
('Tyranids', 'The Swarmlord', 0),
('Tyranids', 'Hive Tyrant', 0),
('Tyranids', 'Winged Hive Tyrant', 0),
('Tyranids', 'Old One Eye', 0),
('Tyranids', 'Norn Emissary', 0),
('Tyranids', 'Norn Assimilator', 0),
('Tyranids', 'Neurothrope', 0),
('Tyranids', 'Tervigon', 0),
('Tyranids', 'Parasite of Mortrex', 0),
('Tyranids', 'Broodlord', 0),
('Tyranids', 'Deathleaper', 0),
('Tyranids', 'The Red Terror', 0),
('Tyranids', 'Tyranid Prime', 0),
('Tyranids', 'Neurotyrant', 0),
('Tyranids', 'Termagants', 0),
('Tyranids', 'Hormagaunts', 0),
('Tyranids', 'Ripper Swarms', 0),
('Tyranids', 'Gargoyles', 0),
('Tyranids', 'Genestealers', 0),
('Tyranids', 'Raveners', 0),
('Tyranids', 'Warriors', 0),
('Tyranids', 'Tyranid Warriors', 0),
('Tyranids', 'Zoanthropes', 0),
('Tyranids', 'Neurothrope', 0),
('Tyranids', 'Venomthropes', 0),
('Tyranids', 'Lictors', 0),
('Tyranids', 'Pyrovores', 0),
('Tyranids', 'Hive Guard', 0),
('Tyranids', 'Carnifexes', 0),
('Tyranids', 'Screamer-Killer', 0),
('Tyranids', 'Stone Crusher Carnifex', 0),
('Tyranids', 'Maleceptor', 0),
('Tyranids', 'Toxicrene', 0),
('Tyranids', 'Exocrine', 0),
('Tyranids', 'Haruspex', 0),
('Tyranids', 'Trygon', 0),
('Tyranids', 'Trygon Prime', 0),
('Tyranids', 'Mawloc', 0),
('Tyranids', 'Tyrannofex', 0),
('Tyranids', 'Hierodule', 0),
('Tyranids', 'Dimachaeron', 0),
('Tyranids', 'Harpy', 0),
('Tyranids', 'Hive Crone', 0),
('Genestealer Cults', 'The Patriarch', 0),
('Genestealer Cults', 'Magus', 0),
('Genestealer Cults', 'Primus', 0),
('Genestealer Cults', 'Nexos', 0),
('Genestealer Cults', 'Clamavus', 0),
('Genestealer Cults', 'Locus', 0),
('Genestealer Cults', 'Biophagus', 0),
('Genestealer Cults', 'Jackal Alphus', 0),
('Genestealer Cults', 'Kelermorph', 0),
('Genestealer Cults', 'Abominant', 0),
('Genestealer Cults', 'Acolyte Hybrids', 0),
('Genestealer Cults', 'Neophyte Hybrids', 0),
('Genestealer Cults', 'Hybrid Metamorphs', 0),
('Genestealer Cults', 'Aberrants', 0),
('Genestealer Cults', 'Goliath Rockgrinder', 0),
('Genestealer Cults', 'Goliath Truck', 0),
('Genestealer Cults', 'Leman Russ (Cult)', 0),
('Genestealer Cults', 'Achilles Ridgerunner', 0),
('Genestealer Cults', 'Mining Laser Sentinel', 0),
('Genestealer Cults', 'Atalan Jackals', 0),
('Genestealer Cults', 'Brood Brothers Infantry Squad', 0),
('Genestealer Cults', 'Brood Brothers Heavy Weapons Squad', 0),
('Genestealer Cults', 'Brood Brothers Command Squad', 0),
('Genestealer Cults', 'Cult Ambush', 0),
('T''au Empire', 'Shadowsun', 0),
('T''au Empire', 'Farsight', 0),
('T''au Empire', 'Longstrike', 0),
('T''au Empire', 'Commander in Coldstar Battlesuit', 0),
('T''au Empire', 'Commander in Enforcer Battlesuit', 0),
('T''au Empire', 'Commander in Firestorm Battlesuit', 0),
('T''au Empire', 'Commander in XV86 Coldstar Battlesuit', 0),
('T''au Empire', 'Commander Farsight', 0),
('T''au Empire', 'Commander Shadowsun', 0),
('T''au Empire', 'Aun''va', 0),
('T''au Empire', 'Aun''shi', 0),
('T''au Empire', 'Ethereal', 0),
('T''au Empire', 'Ethereal on Hover Drone', 0),
('T''au Empire', 'Cadre Fireblade', 0),
('T''au Empire', 'Fire Warriors (Strike Team)', 0),
('T''au Empire', 'Fire Warriors (Breacher Team)', 0),
('T''au Empire', 'Kroot Carnivores', 0),
('T''au Empire', 'Kroot Hounds', 0),
('T''au Empire', 'Kroot Shaper', 0),
('T''au Empire', 'Krootox Riders', 0),
('T''au Empire', 'Longstrike', 0),
('T''au Empire', 'Vespid Stingwings', 0),
('T''au Empire', 'XV8 Crisis Battlesuits', 0),
('T''au Empire', 'XV8-02 Crisis Iridescent Battlesuit', 0),
('T''au Empire', 'XV25 Stealth Battlesuits', 0),
('T''au Empire', 'XV88 Broadside Battlesuits', 0),
('T''au Empire', 'XV95 Ghostkeel Battlesuit', 0),
('T''au Empire', 'XV104 Riptide Battlesuit', 0),
('T''au Empire', 'XV107 R''varna Battlesuit', 0),
('T''au Empire', 'XV109 Y''vahra Battlesuit', 0),
('T''au Empire', 'XV46 Vanguard Void Suit', 0),
('T''au Empire', 'XV46-1', 0),
('T''au Empire', 'KV128 Stormsurge', 0),
('T''au Empire', 'KX139 Ta''unar Supremacy Armour', 0),
('T''au Empire', 'Pathfinder Team', 0),
('T''au Empire', 'Drone Squad', 0),
('T''au Empire', 'Devilfish', 0),
('T''au Empire', 'Hammerhead Gunship', 0),
('T''au Empire', 'Sky Ray Gunship', 0),
('T''au Empire', 'Piranha', 0),
('T''au Empire', 'Razorshark Strike Fighter', 0),
('T''au Empire', 'Sun Shark Bomber', 0),
('T''au Empire', 'Tiger Shark', 0),
('T''au Empire', 'Dahyak Grekh', 0),
('Leagues of Votann', 'Ûthar the Destined', 0),
('Leagues of Votann', 'Grimnyr', 0),
('Leagues of Votann', 'Kâhl', 0),
('Leagues of Votann', 'Brôkhyr Iron-Master', 0),
('Leagues of Votann', 'Einhyr Champion', 0),
('Leagues of Votann', 'Brôkhyr Thunderkyn', 0),
('Leagues of Votann', 'Hearthkyn Warriors', 0),
('Leagues of Votann', 'Einhyr Hearthguard', 0),
('Leagues of Votann', 'Hernkyn Pioneers', 0),
('Leagues of Votann', 'Cthonian Beserks', 0),
('Leagues of Votann', 'Sagitaur', 0),
('Leagues of Votann', 'Hekaton Land Fortress', 0),
('Leagues of Votann', 'Colossus', 0),
('Leagues of Votann', 'Hernkyn Yaegir', 0),
('Leagues of Votann', 'Pioneers', 0)
ON CONFLICT (faction, unit_name) DO NOTHING;
